<div id="briefing-complemento" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Agora que sabemos mais sobre o que você gostaria de projeta, <br />
		<strong>como deseja nos passar as medidas dos ambientes?</strong>
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step1" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step1"></label>
				</div>
			</div>
			<div class="col-2-texto">
				Desejo que um <strong>vendedor da franquia física mais próxima</strong> faça as medições em minha residência.
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step2" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step2"></label>
				</div>
			</div>
			<div class="col-2-texto">
				Desejo <strong>enviar arquivos:</strong> (planta baixa, folder com medida dos espaços, etc).
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step3" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step3"></label>
				</div>
			</div>
			<div class="col-2-texto">
				<strong>Tenho conhecimento</strong>, desejo eu mesmo fazer as medições e enviar.
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step4" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step4"></label>
				</div>
			</div>
			<div class="col-2-texto">
				Não tenho muito conhecimento, gostaria de algumas dicas para eu mesmo tirar as medidas.
			</div>
		</div>
	</div>
</div>

<div id="briefing-vendedor" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Desejo que um vendedor faça as medições em minha residência.<br/>
		Por favor nos informe a data e o horário para o agendamento.<br/>
	</div>
	
	<div class="col-2 col-xs-12">
	
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-voltar pull-left">VOLTAR</button>
		<button class="btn btn-primary btn-avancar pull-right">AVANÇAR</button>
	</div>
</div>

<div id="briefing-videos" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Você selecionou a opção: <br />
		<strong>Não tenho muito conhecimento, gostaria de algumas dicas para eu mesmo tirar as medidas.</strong>
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-3">
			<a href="https://www.youtube.com/watch?v=kJQP7kiw5Fk">
				<img src="<?= $this->basePath('img/youtube.png'); ?>" class="img-responsive" />
			</a>
		</div>
		<div class="col-xs-3">
			<a href="https://www.youtube.com/watch?v=kJQP7kiw5Fk">
				<img src="<?= $this->basePath('img/youtube.png'); ?>" class="img-responsive" />
			</a>
		</div>
		<div class="col-xs-3">
			<a href="https://www.youtube.com/watch?v=kJQP7kiw5Fk">
				<img src="<?= $this->basePath('img/youtube.png'); ?>" class="img-responsive" />
			</a>
		</div>
		<div class="col-xs-3">
			<a href="https://www.youtube.com/watch?v=kJQP7kiw5Fk">
				<img src="<?= $this->basePath('img/youtube.png'); ?>" class="img-responsive" />
			</a>
		</div>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-voltar pull-left">VOLTAR</button>
		<button class="btn btn-primary btn-avancar pull-right">AVANÇAR</button>
	</div>
</div>

<div id="briefing-obrigado" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Obrigado! <3
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12" style="margin-top: 30px;">
			Agora temos as informações para poder fazer<br/>
			<strong>o projeto que se adapta ao seu desejo.</strong>
		</div>
		
		<div class="col-xs-12" style="margin-top: 30px;">
			Você receberá em breve em seu e-mail cadastrado<br/>
			as <strong>informações para visualizar as opções de projetos</strong> que estão
			esperand por você.
		</div>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-fechar pull-right">FECHAR</button>
	</div>
</div>