<div id="briefing-medidas" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Agora que sabemos mais sobre o que você gostaria de projeta, <br />
		<strong>como deseja nos passar as medidas dos ambientes?</strong>
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step1" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step1"></label>
				</div>
			</div>
			<div class="col-2-texto">
				Desejo que um <strong>vendedor da franquia física mais próxima</strong> faça as medições em minha residência.
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step2" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step2"></label>
				</div>
			</div>
			<div class="col-2-texto">
				Desejo <strong>enviar arquivos:</strong> (planta baixa, folder com medida dos espaços, etc).
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step3" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step3"></label>
				</div>
			</div>
			<div class="col-2-texto">
				<strong>Tenho conhecimento</strong>, desejo eu mesmo fazer as medições e enviar.
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step4" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step4"></label>
				</div>
			</div>
			<div class="col-2-texto">
				Não tenho muito conhecimento, gostaria de algumas dicas para eu mesmo tirar as medidas.
			</div>
		</div>
	</div>
</div>