<div id="briefing-complemento" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Agora que sabemos mais sobre o que você gostaria de projetar, <br />
		<strong>como deseja nos passar as medidas dos ambientes?</strong>
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step1" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step1"></label>
				</div>
			</div>
			<div class="col-2-texto">
				Desejo que um <strong>vendedor</strong> faça as medições.
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step2" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step2"></label>
				</div>
			</div>
			<div class="col-2-texto">
				<strong>Enviarei os arquivos das medidas e fotos:</strong> (planta baixa, folder com medida dos espaços, etc).
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step4" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step4"></label>
				</div>
			</div>
			<div class="col-2-texto">
				Quero assistir o vídeo com orientações para que <strong>eu mesmo(a) faça a medição.<strong>
			</div>
		</div>
	</div>

	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-fechar pull-right">FECHAR</button>
	</div>
</div>

<div id="briefing-cadastro" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Por favor, complete seus dados cadastrais:
	</div>
	
	<div class="col-2 col-xs-12">
		<form name="modalCadastroForm" id="modalCadastroForm" data-toggle="validator"
			class="form-briefings form-horizontal" method="post">
			<input type="hidden" name="acao" value="completa-cadastro" />
			
			<div class="form-group col-xs-12">
				<label for="nome" class="col-sm-4">Nome completo:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control disabled" name="nome" disabled>
				</div>
			</div>
				
			<div class="form-group col-xs-12">
				<label for="email" class="col-sm-4">E-mail:</label>
				<div class="col-sm-8">
					<input type="email" class="form-control disabled" name="email" disabled>
				</div>
			</div>
						
			<div class="form-group col-xs-12">
				<label for="cpf" class="col-sm-4">CPF:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control" name="cpf" placeholder="999.999.999-99" required>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="rg" class="col-sm-4">RG:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control" name="rg" required>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="datanascimento" class="col-sm-4">Data de nascimento:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control" name="datanascimento" placeholder="99/99/9999" required>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="sexo" class="col-sm-4">Sexo:</label>
				
				<div class="col-sm-8">
					<select class="form-control" name="sexo" required>
						<option value="M">Masculino</option>
						<option value="F">Feminino</option>
					</select>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="endereco" class="col-sm-4">Endereço:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control" name="endereco" required>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="numero" class="col-sm-4">Número:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control" name="numero" required>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="bairro" class="col-sm-4">Bairro:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control" name="bairro" required>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="cidade" class="col-sm-4">Cidade:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control" name="cidade" required>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="cep" class="col-sm-4">Cep:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control" name="cep" placeholder="99999-999" required>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="fone_cel" class="col-sm-4">Telefone Celular:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control disabled" name="fone_cel" disabled>
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="fone_com" class="col-sm-4">Telefone Comercial:</label>
				
				<div class="col-sm-8">
					<input type="text" class="form-control" name="fone_com" placeholder="(xx) 9xxxx-xxxx">
				</div>
			</div>
			
			<div class="form-group col-xs-12">
				<label for="obs" class="col-sm-4">Observações:</label>
				
				<div class="col-sm-8">
					<textarea class="form-control" name="obs" rows="4"></textarea>
				</div>
			</div>
		</form>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-voltar pull-left">VOLTAR</button>
		<button class="btn btn-primary btn-avancar pull-right">AVANÇAR</button>
	</div>
</div>

<div id="briefing-vendedor" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Você selecionou a opção:<br />
		<strong>Desejo que um vendedor faça as medições.</strong>
	</div>
	
	<div class="col-2 col-xs-12" style="padding-top: 40px;">
		<div class="col-xs-12" style="text-align: center;">
			<strong>Por favor, informe a data e o horário para o agendamento da medição:</strong>
		</div>
		
		<form name="agendaMedicao" id="agendaMedicao" data-toggle="validator" method="post">

			<div class="form-group col-sm-6">
				<label for="agenda-dia" class="col-sm-6" style="text-align: right;">DIA:</label>
				
				<div class="col-sm-6">
					<input type="text" class="form-control" name="dia" value="<?= $this->agendaMedicao['dia'] ?>"
						placeholder="12/12/2010" required />
				</div>
			</div>

			<div class="form-group col-sm-6">
				<label for="agenda-horas" class="col-sm-6" style="text-align: right;">A PARTIR DAS:</label>
				
				<div class="col-sm-3">
					<input type="text" class="form-control" name="horas" value="<?= $this->agendaMedicao['horas'] ?>"
						placeholder="18:00" required />
				</div>

				<div class="col-sm-3" style="text-align: left;">
					H.
				</div>
			</div>
		</form>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-voltar pull-left">VOLTAR</button>
		<button class="btn btn-primary btn-avancar pull-right">AVANÇAR</button>
	</div>
</div>

<div id="briefing-arquivos1" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Você selecionou a opção:<br />
		<strong>Enviarei os arquivos das medidas e fotos.</strong>
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12" style="text-align: center;">
			Por favor, insira o nome do ambiente em cada arquivo a ser enviado. Após o anexo do arquivo,
			utilize o botão [+] para adicionar o próximo.
		</div>
		
		<form name="formArquivosBriefings" id="formArquivosBriefings" target="iframeArquivosBriefings"
			method="post" class="form-horizontal" enctype="multipart/form-data"
				action="<?php echo $this->url('clientes', array('action' => 'uploadArquivosBriefings')); ?>">

		<?php foreach($this->listaCozinha as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia" class="col-sm-3">Nome do ambiente:</label>
					
					<div class="col-sm-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
							value="<?= $item->descricao; ?>" readonly="readonly" />
					</div>
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-3">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaAreaServico as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia" class="col-sm-3">Nome do ambiente:</label>
					
					<div class="col-sm-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
							value="<?= $item->bas_descricao; ?>" readonly="readonly" />
					</div>
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-3">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaDormitorioCasal as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia" class="col-sm-3">Nome do ambiente:</label>
					
					<div class="col-sm-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
							value="<?= $item->bdc_descricao; ?>" readonly="readonly" />
					</div>
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-3">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaDormitorioSolteiro as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia" class="col-sm-3">Nome do ambiente:</label>
					
					<div class="col-sm-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
							value="<?= $item->bds_descricao; ?>" readonly="readonly" />
					</div>
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-3">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaCloset as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia" class="col-sm-3">Nome do ambiente:</label>
					
					<div class="col-sm-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
							value="<?= $item->bcl_descricao; ?>" readonly="readonly" />
					</div>
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-3">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaBanheiro as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia" class="col-sm-3">Nome do ambiente:</label>
					
					<div class="col-sm-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
							value="<?= $item->ban_descricao; ?>" readonly="readonly" />
					</div>
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-3">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaHomeTheater as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia" class="col-sm-3">Nome do ambiente:</label>
					
					<div class="col-sm-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
							value="<?= $item->bht_descricao; ?>" readonly="readonly" />
					</div>
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-3">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaHomeOffice as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia" class="col-sm-3">Nome do ambiente:</label>
					
					<div class="col-sm-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
							value="<?= $item->bho_descricao; ?>" readonly="readonly" />
					</div>
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-9">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-3">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>
		</form>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-voltar pull-left">VOLTAR</button>
		<button class="btn btn-primary btn-avancar pull-right">AVANÇAR</button>
	</div>
</div>

<div id="briefing-videos" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Você selecionou a opção: <br />
		<strong>Quero assistir o vídeo com orientações para que eu mesmo(a) faça a medição.</strong>
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-3">
			<a data-href="https://www.youtube.com/watch?v=kJQP7kiw5Fk">
				<img src="<?= $this->basePath('img/youtube.png'); ?>" class="img-responsive" />
			</a>
		</div>
		<div class="col-xs-3">
			<a data-href="https://www.youtube.com/watch?v=kJQP7kiw5Fk">
				<img src="<?= $this->basePath('img/youtube.png'); ?>" class="img-responsive" />
			</a>
		</div>
		<div class="col-xs-3">
			<a data-href="https://www.youtube.com/watch?v=kJQP7kiw5Fk">
				<img src="<?= $this->basePath('img/youtube.png'); ?>" class="img-responsive" />
			</a>
		</div>
		<div class="col-xs-3">
			<a data-href="https://www.youtube.com/watch?v=kJQP7kiw5Fk">
				<img src="<?= $this->basePath('img/youtube.png'); ?>" class="img-responsive" />
			</a>
		</div>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-voltar pull-left">VOLTAR</button>
	</div>
</div>

<div id="briefing-obrigado" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Obrigado! <3
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12" style="margin-top: 30px;">
			Agora temos as informações para poder fazer<br/>
			<strong>o projeto que se adapta ao seu desejo.</strong>
		</div>
		
		<div class="col-xs-12" style="margin-top: 30px;">
			Num prazo de 48h após a medição você receberá a apresentação dos projetos e orçamento.
		</div>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-fechar pull-right">FECHAR</button>
	</div>
</div>

<div id="briefing-obrigado-vendedor" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Obrigado! <3
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12" style="margin-top: 30px;">
			Após a realização das medições pelo vendedor, estaremos<br/>
			com todas as informações para realizar o <strong>projeto que se adapta ao seu desejo.</strong>
		</div>
		
		<div class="col-xs-12" style="margin-top: 30px;">
			Num prazo de 48h após a medição você receberá a apresentação dos projetos e orçamento.
		</div>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-fechar pull-right">FECHAR</button>
	</div>
</div>

<div id="briefing-obrigado-arquivos" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Obrigado! <3
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12" style="margin-top: 30px;">
			Agora temos as informações para poder fazer<br/>
			<strong>o projeto que se adapta ao seu desejo.</strong>
		</div>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-fechar pull-right">FECHAR</button>
	</div>
</div>

<!-- iframeArquivosBriefings -->
<iframe name="iframeArquivosBriefings" id="iframeArquivosBriefings" class="hide"></iframe>

<!-- iframeVideosYoutube -->
<div id="btn-fechar-youtube"><button class="btn btn-primary pull-right">FECHAR VIDÊO</button></div>
<iframe name="iframeVideosYoutube" id="iframeVideosYoutube" frameborder="0" allowfullscreen></iframe>


<!-- datepicker -->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" 
	integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  		crossorigin="anonymous"></script>
<!-- timepicker -->
<link rel="stylesheet" href="<?php echo $this->basePath('lib/timepicker/jquery.timepicker.css'); ?>" />
<script src="<?php echo $this->basePath('lib/timepicker/jquery.timepicker.min.js'); ?>"></script>

<script type="text/javascript">
$(function(){
	var modalCadastroCallback = null;
	showModalCadastro = function(callback){
		modalCadastroCallback = callback;
		$.post(
			'<?=$this->url('clientes', array('action' => 'completaCadastro'));?>',
			{acao: 'checa-cadastro'},
			function(resp){
				//modalCadastroCallback();
				if(resp.data == true){
					modalCadastroCallback();					
				}else{
					$('#modalCadastroForm input[name="nome"]').val(resp.data.nome);
					$('#modalCadastroForm input[name="email"]').val(resp.data.email);
					$('#modalCadastroForm input[name="fone_cel"]').val(resp.data.fone_cel);

					$('.briefing-complemento-step').hide();
					$('#briefing-cadastro').fadeIn();
				}
			},
			'json'
		);
	};
	
	$('#briefing-cadastro .btn-avancar').click(function(e){
		$('#modalCadastroForm').submit();	
	});

	$('#modalCadastroForm').validator().on('submit', function (e) {
		if (e.isDefaultPrevented()) {
			// handle the invalid form...
		} else {
			$.post(
				'<?=$this->url('clientes', array('action' => 'completaCadastro'));?>',
				$(this).serialize(),
				function(resp){
					if(resp.data == true){
						modalCadastroCallback();
					}else{
						alert(resp.data);
					}
				},
				'json'
			);
		}
		return false;
	});

	$('#briefing-vendedor .btn-avancar').click(function(e){
		$('#agendaMedicao').submit();	
	});

	$('#agendaMedicao').validator().on('submit', function (e) {
		if (e.isDefaultPrevented()) {
			// handle the invalid form...
		} else {
			$.post(
				'<?=$this->url('clientes', array('action' => 'agendaMedicao'));?>',
				$(this).serialize(),
				function(resp){
					if(resp.data == true){
						$('.briefing-complemento-step input:checkbox').prop('checked', false);
						$('.briefing-complemento-step').hide();
						$('#briefing-obrigado-vendedor').fadeIn();
					}else{
						alert(resp.data);
					}
				},
				'json'
			);
		}
		return false;
	});

	$('#briefing-arquivos1 .btn-avancar').click(function(e){
		$('#formArquivosBriefings').submit();	
	});

	$('#iframeArquivosBriefings').on('load', function (e) {
		var response = JSON.parse($(this).contents().find('body').get(0).innerHTML);
		// caso nenhum arquivo tenha sido enviado
		// ou ocorreu um erro
		if(response.files == 0){
			alert(response.data);
		}else{
			$('.briefing-complemento-step input:checkbox').prop('checked', false);
			$('.briefing-complemento-step').hide();
			$('#briefing-obrigado-arquivos').fadeIn();
		}
	});

	$('#briefing-videos a').click(function(e){
		e.stopPropagation();

		var linkHref = $(this).attr('data-href');
		var iframe = $('#iframeVideosYoutube');
			iframe.attr('src', 'https://www.youtube.com/embed/' + linkHref.replace(/(.*)v\=/, ""));
		
		$('#background-frames').css('z-index', 100002);
		$('#btn-fechar-youtube').fadeIn();
		$(iframe).fadeIn();

		return false;
	});

	$('#btn-fechar-youtube button').click(function(){
		var iframe = $('#iframeVideosYoutube');
			iframe.attr('src','about:blank');
		
		$(iframe).fadeOut();
		$('#btn-fechar-youtube').fadeOut();
		$('#background-frames').css('z-index', 100000);
	});

	$('body').on('click', '.pesquisar-arquivo', function(){
		$(this).parent().find('input:file').click();
	});
	$('body').on('change', '#formArquivosBriefings .form-group input:file', function(){
		var arquivoPath = $(this).val();
			arquivoPath = arquivoPath.replace(/^.*(\/|\\)/, "");
			
			$(this).parents('.form-group').find('input:text').val(arquivoPath);
	});
	$('body').on('click', '.adicionar-arquivo', function(){
		var clonaArquivo = $(this).parents('.form-group').clone();
		// esconde botao add
		$(this).parents('.form-group').find('.adicionar-arquivo').hide();
		
		// limpa campos
		$(clonaArquivo).find('input:file').val('');
		$(clonaArquivo).find('input:text').val('');
		$(clonaArquivo).find('.adicionar-arquivo').show();

		// clona input
		$(this).parents('.col-md-12').append(clonaArquivo);
	});

	// mascaras medicao vendedor
	$('input[name="dia"]').datepicker({
        dateFormat: 'dd/mm/yy',
        dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
        dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
        dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
        monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
        monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
    });
	$('input[name="dia"]').mask('99/99/9999');
	$('input[name="dia"]').blur(function(){
		if(/^([0-9]{2})\/([0-9]{2})\/([0-9]{4})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
	$('input[name="horas"]').timepicker({ 'timeFormat': 'H:i' });
	$('input[name="horas"]').mask('99:99');
	$('input[name="horas"]').blur(function(){
		if(/^([0-9]{2})\:([0-9]{2})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});

	// mascaras complemento cadastro
	$('input[name="cpf"]').mask('999.999.999-99');
	$('input[name="cpf"]').blur(function(){
		if(/^([0-9]{3})\.([0-9]{3})\.([0-9]{3})\-([0-9]{2})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
	$('input[name="datanascimento"]').mask('99/99/9999');
	$('input[name="datanascimento"]').blur(function(){
		if(/^([0-9]{2})\/([0-9]{2})\/([0-9]{4})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
	$('input[name="cep"]').mask('99999-999');
	$('input[name="cep"]').blur(function(){
		if(/^([0-9]{5})\-([0-9]{3})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
	$('input[name="fone_com"]').mask('(99) 99999-9999');
	$('input[name="fone_com"]').blur(function(){
		if(/^\([0-9]{2}\) ([0-9]{5})\-([0-9]{3,4})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
});
</script>