<div class="modal fade" id="modalAreaServico" tabindex="-1" role="dialog" aria-labelledby="modalAreaServicoLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalAreaServicoLabel">Briefing Área de Serviço</h4>
      </div>
      <div class="modal-body">
      		<form name="modalAreaServicoForm" id="modalAreaServicoForm" data-toggle="validator"
      			class="form-briefings form-horizontal" method="post" enctype="multipart/form-data">
      			<input type="hidden" name="acao" value="briefing-AreaServico" />
      			<input type="hidden" name="id" value="" />
      			
				<div class="form-group col-xs-12">
				   	<!-- Descrição -->
				   	<label for="bas_descricao" class="col-sm-4">Descrição:</label>
				   	<div class="col-sm-8">
			   			<input type="text" class="form-control" name="bas_descricao" required>
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bas_preferenciacores" class="col-sm-4">Preferência de cores:</label>
            		
            		<div class="col-sm-8">
            			<div class="col-md-6">
            				<input type="checkbox" name="bas_preferenciacores[]" id="bas_preferenciacores-1" value="1">
            				<label for="bas_preferenciacores-1">Claro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bas_preferenciacores[]" id="bas_preferenciacores-2" value="2">
            				<label for="bas_preferenciacores-2">Escuro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bas_preferenciacores[]" id="bas_preferenciacores-3" value="3">
            				<label for="bas_preferenciacores-3">Amadeirado</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bas_preferenciacores[]" id="bas_preferenciacores-4" value="4">
            				<label for="bas_preferenciacores-4">Liso</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bas_preferenciacores[]" id="bas_preferenciacores-5" value="5">
            				<label for="bas_preferenciacores-5">Colorido</label>
            			</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bas_maquinalavar" class="col-sm-4">Máquina de lavar:</label>
            		
            		<div class="col-sm-8">
				   		<div class="col-md-6">
            				<input type="radio" name="bas_maquinalavar" id="bas_maquinalavar-1" value="1" class="block-subitem-cond">
            				<label for="bas_maquinalavar-1">Sim</label>
				   		</div>
            			<div class="col-md-6">
							<input type="radio" name="bas_maquinalavar" id="bas_maquinalavar-0" value="0" class="block-subitem-cond">
            				<label for="bas_maquinalavar-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Máquina de lavar cor -->
				   	<label for="bas_maquinalavarcor" class="col-sm-4 block-subitem">Cor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bas_maquinalavarcor">
				   	</div>

				   	<!-- Máquina de lavar modelo/marca -->
				   	<label for="bas_maquinalavarmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bas_maquinalavarmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bas_maquinasecar" class="col-sm-4">Máquina de secar:</label>
            		
            		<div class="col-sm-8">
				   		<div class="col-md-6">
            				<input type="radio" name="bas_maquinasecar" id="bas_maquinasecar-1" value="1" class="block-subitem-cond">
            				<label for="bas_maquinasecar-1">Sim</label>
				   		</div>
            			<div class="col-md-6">
							<input type="radio" name="bas_maquinasecar" id="bas_maquinasecar-0" value="0" class="block-subitem-cond">
            				<label for="bas_maquinasecar-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Máquina de secar cor -->
				   	<label for="bas_maquinasecarcor" class="col-sm-4 block-subitem">Cor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bas_maquinasecarcor">
				   	</div>

				   	<!-- Máquina de secar modelo/marca -->
				   	<label for="bas_maquinasecarmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bas_maquinasecarmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bas_tabuapassar" class="col-sm-4">Tábua de passar:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bas_tabuapassar" id="bas_tabuapassar-1" value="1">
            				<label for="bas_tabuapassar-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bas_tabuapassar" id="bas_tabuapassar-0" value="0">
            				<label for="bas_tabuapassar-0">Não</label>
						</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bas_aquecedoragua" class="col-sm-4">Aquecedor de água:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bas_aquecedoragua" id="bas_aquecedoragua-1" value="1" class="block-subitem-cond">
            				<label for="bas_aquecedoragua-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bas_aquecedoragua" id="bas_aquecedoragua-0" value="0" class="block-subitem-cond">
            				<label for="bas_aquecedoragua-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Aquecedor de água cor -->
				   	<label for="bas_aquecedoraguacor" class="col-sm-4 block-subitem">Cor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bas_aquecedoraguacor">
				   	</div>

				   	<!-- Aquecedor de água modelo/marca -->
				   	<label for="bas_aquecedoraguamodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bas_aquecedoraguamodelomarca">
				   	</div>

				   	<!-- dimensões -->
				   	<label for="bas_aquecedoraguadimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<div class="ss-item-required">
			   				<input type="text" class="form-control" name="bas_aquecedoraguadimensoes">
			   			</div>
				   	</div>				   					   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bas_cabideiro" class="col-sm-4">Cabideiro p/ roupa passada:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bas_cabideiro" id="bas_cabideiro-1" value="1">
            				<label for="bas_cabideiro-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bas_cabideiro" id="bas_cabideiro-0" value="0">
            				<label for="bas_cabideiro-0">Não</label>
						</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bas_baldes" class="col-sm-4">Baldes:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bas_baldes" id="bas_baldes-1" value="1">
            				<label for="bas_baldes-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bas_baldes" id="bas_baldes-0" value="0">
            				<label for="bas_baldes-0">Não</label>
						</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bas_aspiradorpo" class="col-sm-4">Aspirador de pó:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bas_aspiradorpo" id="bas_aspiradorpo-1" value="1" class="block-subitem-cond">
            				<label for="bas_aspiradorpo-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bas_aspiradorpo" id="bas_aspiradorpo-0" value="0" class="block-subitem-cond">
            				<label for="bas_aspiradorpo-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Aspirador modelo/marca -->
				   	<label for="bas_aspiradorpomodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bas_aspiradorpomodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
				   	<label for="bas_vassourasrodo" class="col-sm-4">Vassouras/Rodo:</label>
				   	
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bas_vassourasrodo" id="bas_vassourasrodo-1" value="1">
            				<label for="bas_vassourasrodo-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bas_vassourasrodo" id="bas_vassourasrodo-0" value="0">
            				<label for="bas_vassourasrodo-0">Não</label>
						</div>
				   	</div>
				</div>
								
				<div class="form-group col-xs-12">
				   	<!-- Tipo -->
				   	<label for="bas_armazenarroupasuja" class="col-sm-4">Armazenar roupa suja:</label>

            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bas_armazenarroupasuja" id="bas_armazenarroupasuja-1" value="1">
            				<label for="bas_armazenarroupasuja-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bas_armazenarroupasuja" id="bas_armazenarroupasuja-0" value="0">
            				<label for="bas_armazenarroupasuja-0">Não</label>
						</div>
				   	</div>
				</div>
								
				<div class="form-group col-xs-12">
      				<label for="bas_obs" class="col-sm-4">Observações:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="bas_obs">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12 box-imagem">
      				<label for="bas_imagem" class="col-sm-4">Gostaria de nos enviar alguma imagem para nos inspirar a fazer o seu projeto?</label>
            		
            		<div class="col-sm-8">
				   		<input type="file" class="form-control" name="bas_imagem" />
				   		
				   		<div class="col-xs-10"></div>
				   	</div>
				</div>
			</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="concluirAreaServico" class="btn btn-primary">Concluir</button>
      </div>
    </div>
  </div>
</div>