<div class="modal fade" id="modalHomeTheater" tabindex="-1" role="dialog" aria-labelledby="modalHomeTheaterLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalHomeTheaterLabel">Briefing Home Theater</h4>
      </div>
      <div class="modal-body">
      		<form name="modalHomeTheaterForm" id="modalHomeTheaterForm" data-toggle="validator"
      			class="form-briefings form-horizontal" method="post" enctype="multipart/form-data">
      			<input type="hidden" name="acao" value="briefing-hometheater" />
      			<input type="hidden" name="id" value="" />
      			
				<div class="form-group col-xs-12">
				   	<!-- Descrição -->
				   	<label for="bht_descricao" class="col-sm-4">Descrição:</label>
				   	<div class="col-sm-8">
			   			<input type="text" class="form-control" name="bht_descricao">
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bht_preferenciacores" class="col-sm-4">Preferência de cores:</label>
            		
            		<div class="col-sm-8">
            			<div class="col-md-6">
            				<input type="checkbox" name="bht_preferenciacores[]" id="bht_preferenciacores-1" value="1">
            				<label for="bht_preferenciacores-1">Claro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bht_preferenciacores[]" id="bht_preferenciacores-2" value="2">
            				<label for="bht_preferenciacores-2">Escuro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bht_preferenciacores[]" id="bht_preferenciacores-3" value="3">
            				<label for="bht_preferenciacores-3">Amadeirado</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bht_preferenciacores[]" id="bht_preferenciacores-4" value="4">
            				<label for="bht_preferenciacores-4">Liso</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bht_preferenciacores[]" id="bht_preferenciacores-5" value="5">
            				<label for="bht_preferenciacores-5">Colorido</label>
            			</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bht_sofa" class="col-sm-4">Sofá:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bht_sofa" id="bht_sofa-1" value="1" class="block-subitem-cond">
            				<label for="bht_sofa-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bht_sofa" id="bht_sofa-0" value="0" class="block-subitem-cond">
            				<label for="bht_sofa-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Sofá cor -->
				   	<label for="bht_sofacor" class="col-sm-4 block-subitem">Cor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_sofacor">
				   	</div>

				   	<!-- Dimensões -->
				   	<label for="bht_sofadimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_sofadimensoes">
				   	</div>				   					   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bht_poltrona" class="col-sm-4">Poltrona:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bht_poltrona" id="bht_poltrona-1" value="1" class="block-subitem-cond">
            				<label for="bht_poltrona-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bht_poltrona" id="bht_poltrona-0" value="0" class="block-subitem-cond">
            				<label for="bht_poltrona-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Poltrona cor -->
				   	<label for="bht_poltronacor" class="col-sm-4 block-subitem">Cor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_poltronacor">
				   	</div>

				   	<!-- Dimensões -->
				   	<label for="bht_poltronadimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_poltronadimensoes">
				   	</div>				   					   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bht_puf" class="col-sm-4">Pufs:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bht_puf" id="bht_puf-1" value="1" class="block-subitem-cond">
            				<label for="bht_puf-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bht_puf" id="bht_puf-0" value="0" class="block-subitem-cond">
            				<label for="bht_puf-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Puf cor -->
				   	<label for="bht_pufcor" class="col-sm-4 block-subitem">Cor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_pufcor">
				   	</div>

				   	<!-- Dimensões -->
				   	<label for="bht_pufdimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_pufdimensoes">
				   	</div>				   					   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bht_possuitv" class="col-sm-4">Televisor:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bht_possuitv" id="bht_possuitv-1" value="1" class="block-subitem-cond">
            				<label for="bht_possuitv-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bht_possuitv" id="bht_possuitv-0" value="0" class="block-subitem-cond">
            				<label for="bht_possuitv-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- polegadas -->
				   	<label for="bht_tvpolegadas" class="col-sm-4 block-subitem">Polegadas:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_tvpolegadas">
				   	</div>
				   	
				   	<!-- modelo/marca -->
				   	<label for="bht_tvmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_tvmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bht_possuidvd" class="col-sm-4">DVD:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bht_possuidvd" id="bht_possuidvd-1" value="1" class="block-subitem-cond">
            				<label for="bht_possuidvd-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bht_possuidvd" id="bht_possuidvd-0" value="0" class="block-subitem-cond">
            				<label for="bht_possuidvd-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- dimensões -->
				   	<label for="bht_dvddimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_dvddimensoes">
				   	</div>
				   					   	
				   	<!-- modelo/marca -->
				   	<label for="bht_dvdmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_dvdmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bht_possuisom" class="col-sm-4">Som:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bht_possuisom" id="bht_possuisom-1" value="1" class="block-subitem-cond">
            				<label for="bht_possuisom-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bht_possuisom" id="bht_possuisom-0" value="0" class="block-subitem-cond">
            				<label for="bht_possuisom-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- dimensões -->
				   	<label for="bht_somdimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_somdimensoes">
				   	</div>
				   					   	
				   	<!-- modelo/marca -->
				   	<label for="bht_sommodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_sommodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bht_possuitvcabo" class="col-sm-4">TV a cabo:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bht_possuitvcabo" id="bht_possuitvcabo-1" value="1" class="block-subitem-cond">
            				<label for="bht_possuitvcabo-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bht_possuitvcabo" id="bht_possuitvcabo-0" value="0" class="block-subitem-cond">
            				<label for="bht_possuitvcabo-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- dimensões -->
				   	<label for="bht_tvcabodimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_tvcabodimensoes">
				   	</div>
				   	
				   	<!-- modelo/marca -->
				   	<label for="bht_tvcabomodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bht_tvcabomodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bht_obs" class="col-sm-4">Observações:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="bht_obs">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12 box-imagem">
      				<label for="bht_imagem" class="col-sm-4">Gostaria de nos enviar alguma imagem para nos inspirar a fazer o seu projeto?</label>
            		
            		<div class="col-sm-8">
				   		<input type="file" class="form-control" name="bht_imagem" />
				   		
				   		<div class="col-xs-10"></div>
				   	</div>
				</div>
			</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="concluirHomeTheater" class="btn btn-primary">Concluir</button>
      </div>
    </div>
  </div>
</div>