<div class="modal fade" id="modalDormitorioInfantil" tabindex="-1" role="dialog" aria-labelledby="modalDormitorioInfantilLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalDormitorioInfantilLabel">Briefing Dormitório Infantil</h4>
      </div>
      <div class="modal-body">
      		<form name="modalDormitorioInfantilForm" id="modalDormitorioInfantilForm" data-toggle="validator"
      			class="form-briefings form-horizontal" method="post" enctype="multipart/form-data">
      			<input type="hidden" name="acao" value="briefing-dormitorioinfantil" />
      			<input type="hidden" name="id" value="" />
      			
				<div class="form-group col-xs-12">
				   	<!-- Descrição -->
				   	<label for="bdi_descricao" class="col-sm-4">Descrição:</label>
				   	<div class="col-sm-8">
			   			<input type="text" class="form-control" name="bdi_descricao" required>
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bdi_mascfem" class="col-sm-4">Masculino/Feminino:</label>
            		
            		<div class="col-sm-8">
				   		<select class="form-control" name="bdi_mascfem" required>
				   			<option value="M">Masculino</option>
				   			<option value="F">Feminino</option>
				   		</select>
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bdi_preferenciacores" class="col-sm-4">Preferência de cores:</label>
            		
            		<div class="col-sm-8">
            			<div class="col-md-6">
            				<input type="checkbox" name="bdi_preferenciacores[]" id="bdi_preferenciacores-1" value="1">
            				<label for="bdi_preferenciacores-1">Claro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bdi_preferenciacores[]" id="bdi_preferenciacores-2" value="2">
            				<label for="bdi_preferenciacores-2">Escuro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bdi_preferenciacores[]" id="bdi_preferenciacores-3" value="3">
            				<label for="bdi_preferenciacores-3">Amadeirado</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bdi_preferenciacores[]" id="bdi_preferenciacores-4" value="4">
            				<label for="bdi_preferenciacores-4">Liso</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bdi_preferenciacores[]" id="bdi_preferenciacores-5" value="5">
            				<label for="bdi_preferenciacores-5">Colorido</label>
            			</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
				   	<!-- Cama tipo -->
				   	<label for="bdi_tipocama" class="col-sm-4">Tipo de cama:</label>
				   	<div class="col-sm-8">
			   			<select class="form-control" name="bdi_tipocama">
			   				<option value="">Selecione...</option>
				   			<option value="1">Box</option>
				   			<option value="2">Tradicional</option>
				   			<option value="3">Com gavetas</option>
				   		</select>
				   	</div>
				   	
				   	<!-- Cama cor -->
				   	<label for="bdi_corcama" class="col-sm-4">Cor:</label>
				   	<div class="col-sm-8">
			   			<select class="form-control" name="bdi_corcama">
				   			<option value="">Selecione...</option>
				   			<?php include __DIR__.'/_optionsCores.phtml';?>
				   		</select>
				   	</div>
				   	
				   	<!-- Medição cama -->
				   	<label for="bdi_camamedicao" class="col-sm-4">Lagura x Altura x Profundidade:</label>
				   	<div class="col-sm-8">
			   			<input type="text" class="form-control" name="bdi_camamedicao">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bdi_penteadeira" class="col-sm-4">Penteadeira:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bdi_penteadeira" id="bdi_penteadeira-1" value="1">
            				<label for="bdi_penteadeira-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bdi_penteadeira" id="bdi_penteadeira-0" value="0">
            				<label for="bdi_penteadeira-0">Não</label>
						</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bdi_bancadaestudos" class="col-sm-4">Banca de estudos:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bdi_bancadaestudos" id="bdi_bancadaestudos-1" value="1">
            				<label for="bdi_bancadaestudos-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bdi_bancadaestudos" id="bdi_bancadaestudos-0" value="0">
            				<label for="bdi_bancadaestudos-0">Não</label>
						</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bdi_sapateiras" class="col-sm-4">Sapateiras:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bdi_sapateiras" id="bdi_sapateiras-1" value="1">
            				<label for="bdi_sapateiras-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bdi_sapateiras" id="bdi_sapateiras-0" value="0">
            				<label for="bdi_sapateiras-0">Não</label>
						</div>
				   	</div>
				</div>

				<div class="form-group col-xs-12">
      				<label for="bdi_calceiros" class="col-sm-4">Calceiros:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bdi_calceiros" id="bdi_calceiros-1" value="1">
            				<label for="bdi_calceiros-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bdi_calceiros" id="bdi_calceiros-0" value="0">
            				<label for="bdi_calceiros-0">Não</label>
						</div>
				   	</div>
				</div>

				<div class="form-group col-xs-12">
      				<label for="bdi_portascomespelho" class="col-sm-4">Portas com espelho:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bdi_portascomespelho" id="bdi_portascomespelho-1" value="1">
            				<label for="bdi_portascomespelho-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bdi_portascomespelho" id="bdi_portascomespelho-0" value="0">
            				<label for="bdi_portascomespelho-0">Não</label>
						</div>
				   	</div>
				</div>
							
				<div class="form-group col-xs-12">
      				<label for="bdi_possuitv" class="col-sm-4">Televisor:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bdi_possuitv" id="bdi_possuitv-1" value="1" class="block-subitem-cond">
            				<label for="bdi_possuitv-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bdi_possuitv" id="bdi_possuitv-0" value="0" class="block-subitem-cond">
            				<label for="bdi_possuitv-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- polegadas -->
				   	<label for="bdi_tvpolegadas" class="col-sm-4 block-subitem">Polegadas:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bdi_tvpolegadas">
				   	</div>
				   	
				   	<!-- modelo/marca -->
				   	<label for="bdi_tvmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bdi_tvmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bdi_possuidvd" class="col-sm-4">DVD:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bdi_possuidvd" id="bdi_possuidvd-1" value="1" class="block-subitem-cond">
            				<label for="bdi_possuidvd-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bdi_possuidvd" id="bdi_possuidvd-0" value="0" class="block-subitem-cond">
            				<label for="bdi_possuidvd-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- dimensões -->
				   	<label for="bdi_dvddimensao" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bdi_dvddimensao">
				   	</div>
				   					   	
				   	<!-- modelo/marca -->
				   	<label for="bdi_dvdmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bdi_dvdmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bdi_possuitvcabo" class="col-sm-4">TV a cabo:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bdi_possuitvcabo" id="bdi_possuitvcabo-1" value="1" class="block-subitem-cond">
            				<label for="bdi_possuitvcabo-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bdi_possuitvcabo" id="bdi_possuitvcabo-0" value="0" class="block-subitem-cond">
            				<label for="bdi_possuitvcabo-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- dimensão -->
				   	<label for="bdi_tvcabodimensao" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bdi_tvcabodimensao">
				   	</div>
				   	
				   	<!-- modelo/marca -->
				   	<label for="bdi_tvcabomodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bdi_tvcabomodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bdi_obs" class="col-sm-4">Observações:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="bdi_obs">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12 box-imagem">
      				<label for="bdi_imagem" class="col-sm-4">Gostaria de nos enviar alguma imagem para nos inspirar a fazer o seu projeto?</label>
            		
            		<div class="col-sm-8">
				   		<input type="file" class="form-control" name="bdi_imagem" />
				   		
				   		<div class="col-xs-10"></div>
				   	</div>
				</div>
			</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="concluirDormitorioInfantil" class="btn btn-primary">Concluir</button>
      </div>
    </div>
  </div>
</div>