<div class="modal fade" id="modalCloset" tabindex="-1" role="dialog" aria-labelledby="modalClosetLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalClosetLabel">Briefing Closet</h4>
      </div>
      <div class="modal-body">
      		<form name="modalClosetForm" id="modalClosetForm" data-toggle="validator"
      			class="form-briefings form-horizontal" method="post" enctype="multipart/form-data">
      			<input type="hidden" name="acao" value="briefing-closet" />
      			<input type="hidden" name="id" value="" />
      			
				<div class="form-group col-xs-12">
				   	<!-- Descrição -->
				   	<label for="bcl_descricao" class="col-sm-4">Descrição:</label>
				   	<div class="col-sm-8">
			   			<input type="text" class="form-control" name="bcl_descricao">
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bcl_preferenciacores" class="col-sm-4">Preferência de cores:</label>
            		
            		<div class="col-sm-8">
            			<div class="col-md-6">
            				<input type="checkbox" name="bcl_preferenciacores[]" id="bcl_preferenciacores-1" value="1">
            				<label for="bcl_preferenciacores-1">Claro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bcl_preferenciacores[]" id="bcl_preferenciacores-2" value="2">
            				<label for="bcl_preferenciacores-2">Escuro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bcl_preferenciacores[]" id="bcl_preferenciacores-3" value="3">
            				<label for="bcl_preferenciacores-3">Amadeirado</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bcl_preferenciacores[]" id="bcl_preferenciacores-4" value="4">
            				<label for="bcl_preferenciacores-4">Liso</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bcl_preferenciacores[]" id="bcl_preferenciacores-5" value="5">
            				<label for="bcl_preferenciacores-5">Colorido</label>
            			</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bcl_penteadeira" class="col-sm-4">Penteadeira:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bcl_penteadeira" id="bcl_penteadeira-1" value="1">
            				<label for="bcl_penteadeira-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bcl_penteadeira" id="bcl_penteadeira-0" value="0">
            				<label for="bcl_penteadeira-0">Não</label>
						</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bcl_qtdgavchave" class="col-sm-4">Qtd gavetas com chave:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="bcl_qtdgavchave">
				   	</div>				   	
				</div>

				<div class="form-group col-xs-12">
      				<label for="bcl_sapateiras" class="col-sm-4">Sapateiras:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bcl_sapateiras" id="bcl_sapateiras-1" value="1">
            				<label for="bcl_sapateiras-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bcl_sapateiras" id="bcl_sapateiras-0" value="0">
            				<label for="bcl_sapateiras-0">Não</label>
						</div>
				   	</div>
				</div>

				<div class="form-group col-xs-12">
      				<label for="bcl_calceiros" class="col-sm-4">Calceiros:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bcl_calceiros" id="bcl_calceiros-1" value="1">
            				<label for="bcl_calceiros-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bcl_calceiros" id="bcl_calceiros-0" value="0">
            				<label for="bcl_calceiros-0">Não</label>
						</div>
				   	</div>
				</div>

				<div class="form-group col-xs-12">
      				<label for="bcl_portajoias" class="col-sm-4">Porta-joias:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bcl_portajoias" id="bcl_portajoias-1" value="1">
            				<label for="bcl_portajoias-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bcl_portajoias" id="bcl_portajoias-0" value="0">
            				<label for="bcl_portajoias-0">Não</label>
						</div>
				   	</div>
				</div>

				<div class="form-group col-xs-12">
      				<label for="bcl_gravateiro" class="col-sm-4">Gravateiro:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bcl_gravateiro" id="bcl_gravateiro-1" value="1">
            				<label for="bcl_gravateiro-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bcl_gravateiro" id="bcl_gravateiro-0" value="0">
            				<label for="bcl_gravateiro-0">Não</label>
						</div>
				   	</div>
				</div>

				<div class="form-group col-xs-12">
      				<label for="bcl_portacintos" class="col-sm-4">Porta-cintos:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bcl_portacintos" id="bcl_portacintos-1" value="1">
            				<label for="bcl_portacintos-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bcl_portacintos" id="bcl_portacintos-0" value="0">
            				<label for="bcl_portacintos-0">Não</label>
						</div>
				   	</div>
				</div>

				<div class="form-group col-xs-12">
      				<label for="bcl_portaobjetos" class="col-sm-4">Porta-objetos:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bcl_portaobjetos" id="bcl_portaobjetos-1" value="1">
            				<label for="bcl_portaobjetos-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bcl_portaobjetos" id="bcl_portaobjetos-0" value="0">
            				<label for="bcl_portaobjetos-0">Não</label>
						</div>
				   	</div>
				</div>

				<div class="form-group col-xs-12">
      				<label for="bcl_portascomespelho" class="col-sm-4">Portas com espelho:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bcl_portascomespelho" id="bcl_portascomespelho-1" value="1">
            				<label for="bcl_portascomespelho-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bcl_portascomespelho" id="bcl_portascomespelho-0" value="0">
            				<label for="bcl_portascomespelho-0">Não</label>
						</div>
				   	</div>
				</div>
							
				<div class="form-group col-xs-12">
      				<label for="bcl_obs" class="col-sm-4">Observações:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="bcl_obs">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12 box-imagem">
      				<label for="bcl_imagem" class="col-sm-4">Gostaria de nos enviar alguma imagem para nos inspirar a fazer o seu projeto?</label>
            		
            		<div class="col-sm-8">
				   		<input type="file" class="form-control" name="bcl_imagem" />
				   		
				   		<div class="col-xs-10"></div>
				   	</div>
				</div>
			</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="concluirCloset" class="btn btn-primary">Concluir</button>
      </div>
    </div>
  </div>
</div>