<div class="modal fade" id="modalCadastro" tabindex="-1" role="dialog" aria-labelledby="modalCadastroLabel" data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalCadastroLabel">Complemento de cadastro</h4>
      </div>
      <div class="modal-body">
      		<form name="modalCadastroForm" id="modalCadastroForm" data-toggle="validator"
      			class="form-briefings form-horizontal" method="post">
      			<input type="hidden" name="acao" value="completa-cadastro" />
      			
      			<div class="form-group col-xs-12">
            		<label for="nome" class="col-sm-4">Nome completo:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control disabled" name="nome" disabled>
				   	</div>
				</div>
					
				<div class="form-group col-xs-12">
					<label for="email" class="col-sm-4">E-mail:</label>
					<div class="input-group col-sm-8">
						<span class="input-group-addon">@</span>
						<input type="email" class="form-control disabled" name="email" disabled>
					</div>
				</div>
							
      			<div class="form-group col-xs-12">
      				<label for="cpf" class="col-sm-4">CPF:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="cpf" placeholder="999.999.999-99" required>
				   	</div>
				</div>
				
      			<div class="form-group col-xs-12">
      				<label for="rg" class="col-sm-4">RG:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="rg" required>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="datanascimento" class="col-sm-4">Data de nascimento:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="datanascimento" placeholder="99/99/9999" required>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="sexo" class="col-sm-4">Sexo:</label>
            		
            		<div class="col-sm-8">
				   		<select class="form-control" name="sexo" required>
				   			<option value="M">Masculino</option>
				   			<option value="F">Feminino</option>
				   		</select>
				   	</div>
				</div>
				
      			<div class="form-group col-xs-12">
      				<label for="endereco" class="col-sm-4">Endereço:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="endereco" required>
				   	</div>
				</div>
      			
      			<div class="form-group col-xs-12">
      				<label for="numero" class="col-sm-4">Número:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="numero" required>
				   	</div>
				</div>
				
      			<div class="form-group col-xs-12">
      				<label for="bairro" class="col-sm-4">Bairro:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="bairro" required>
				   	</div>
				</div>
				
      			<div class="form-group col-xs-12">
      				<label for="cidade" class="col-sm-4">Cidade:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="cidade" required>
				   	</div>
				</div>
				
      			<div class="form-group col-xs-12">
      				<label for="cep" class="col-sm-4">Cep:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="cep" placeholder="99999-999" required>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="fone_cel" class="col-sm-4">Telefone Celular:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control disabled" name="fone_cel" disabled>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="fone_com" class="col-sm-4">Telefone Comercial:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="fone_com" placeholder="(xx) 9xxxx-xxxx">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="obs" class="col-sm-4">Observações:</label>
            		
            		<div class="col-sm-8">
				   		<textarea class="form-control" name="obs" rows="4"></textarea>
				   	</div>
				</div>
			</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="concluirCadastro" class="btn btn-primary">Concluir</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(function(){
	var modalCadastroCallback = null;
	showModalCadastro = function(callback){
		modalCadastroCallback = callback;
		$.post(
			'<?=$this->url('clientes', array('action' => 'completaCadastro'));?>',
			{acao: 'checa-cadastro'},
			function(resp){
				modalCadastroCallback();
				/*if(resp.data == true){
					modalCadastroCallback();					
				}else{
					$('#modalCadastroForm input[name="nome"]').val(resp.data.nome);
					$('#modalCadastroForm input[name="email"]').val(resp.data.email);
					$('#modalCadastroForm input[name="fone_cel"]').val(resp.data.fone_cel);
					$('#modalCadastro').modal('show');
				}*/
			},
			'json'
		);
	};
	
	$('#concluirCadastro').click(function(){
		$('#modalCadastroForm').submit();	
	});

	$('#modalCadastroForm').submit(function(){
		$('#modalCadastro').modal('hide');
		$.post(
			'<?=$this->url('clientes', array('action' => 'completaCadastro'));?>',
			$(this).serialize(),
			function(resp){
				if(resp.data == true){
					modalCadastroCallback();
				}else{
					alert(resp.data);
					$('#modalCadastro').modal('show');
				}
			},
			'json'
		);
		return false;
	});
});
</script>