<div class="modal fade" id="modalHomeOffice" tabindex="-1" role="dialog" aria-labelledby="modalHomeOfficeLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalHomeOfficeLabel">Briefing Home Office</h4>
      </div>
      <div class="modal-body">
      		<form name="modalHomeOfficeForm" id="modalHomeOfficeForm" data-toggle="validator"
      			class="form-briefings form-horizontal" method="post" enctype="multipart/form-data">
      			<input type="hidden" name="acao" value="briefing-homeoffice" />
      			<input type="hidden" name="id" value="" />
      			
				<div class="form-group col-xs-12">
				   	<!-- Descrição -->
				   	<label for="bho_descricao" class="col-sm-4">Descrição:</label>
				   	<div class="col-sm-8">
			   			<input type="text" class="form-control" name="bho_descricao">
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_preferenciacores" class="col-sm-4">Preferência de cores:</label>
            		
            		<div class="col-sm-8">
            			<div class="col-md-6">
            				<input type="checkbox" name="bho_preferenciacores[]" id="bho_preferenciacores-1" value="1">
            				<label for="bho_preferenciacores-1">Claro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bho_preferenciacores[]" id="bho_preferenciacores-2" value="2">
            				<label for="bho_preferenciacores-2">Escuro</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bho_preferenciacores[]" id="bho_preferenciacores-3" value="3">
            				<label for="bho_preferenciacores-3">Amadeirado</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bho_preferenciacores[]" id="bho_preferenciacores-4" value="4">
            				<label for="bho_preferenciacores-4">Liso</label>
            			</div>
            			<div class="col-md-6">
            				<input type="checkbox" name="bho_preferenciacores[]" id="bho_preferenciacores-5" value="5">
            				<label for="bho_preferenciacores-5">Colorido</label>
            			</div>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_sofa" class="col-sm-4">Sofá:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bho_sofa" id="bho_sofa-1" value="1" class="block-subitem-cond">
            				<label for="bho_sofa-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bho_sofa" id="bho_sofa-0" value="0" class="block-subitem-cond">
            				<label for="bho_sofa-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Sofá cor -->
				   	<label for="bho_sofacor" class="col-sm-4 block-subitem">Cor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_sofacor">
				   	</div>

				   	<!-- Dimensões -->
				   	<label for="bho_sofadimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_sofadimensoes">
				   	</div>				   					   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_poltrona" class="col-sm-4">Poltrona:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bho_poltrona" id="bho_poltrona-1" value="1" class="block-subitem-cond">
            				<label for="bho_poltrona-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bho_poltrona" id="bho_poltrona-0" value="0" class="block-subitem-cond">
            				<label for="bho_poltrona-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Poltrona cor -->
				   	<label for="bho_poltronacor" class="col-sm-4 block-subitem">Cor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_poltronacor">
				   	</div>

				   	<!-- Dimensões -->
				   	<label for="bho_poltronadimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_poltronadimensoes">
				   	</div>				   					   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_puf" class="col-sm-4">Pufs:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bho_puf" id="bho_puf-1" value="1" class="block-subitem-cond">
            				<label for="bho_puf-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bho_puf" id="bho_puf-0" value="0" class="block-subitem-cond">
            				<label for="bho_puf-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- Puf cor -->
				   	<label for="bho_pufcor" class="col-sm-4 block-subitem">Cor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_pufcor">
				   	</div>

				   	<!-- Dimensões -->
				   	<label for="bho_pufdimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_pufdimensoes">
				   	</div>				   					   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_possuitv" class="col-sm-4">Televisor:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bho_possuitv" id="bho_possuitv-1" value="1" class="block-subitem-cond">
            				<label for="bho_possuitv-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bho_possuitv" id="bho_possuitv-0" value="0" class="block-subitem-cond">
            				<label for="bho_possuitv-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- polegadas -->
				   	<label for="bho_tvpolegadas" class="col-sm-4 block-subitem">Polegadas:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_tvpolegadas">
				   	</div>
				   	
				   	<!-- modelo/marca -->
				   	<label for="bho_tvmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_tvmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_possuidvd" class="col-sm-4">DVD:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bho_possuidvd" id="bho_possuidvd-1" value="1" class="block-subitem-cond">
            				<label for="bho_possuidvd-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bho_possuidvd" id="bho_possuidvd-0" value="0" class="block-subitem-cond">
            				<label for="bho_possuidvd-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- dimensões -->
				   	<label for="bho_dvddimensaoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_dvddimensaoes">
				   	</div>
				   					   	
				   	<!-- modelo/marca -->
				   	<label for="bho_dvdmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_dvdmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_possuisom" class="col-sm-4">Som:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bho_possuisom" id="bho_possuisom-1" value="1" class="block-subitem-cond">
            				<label for="bho_possuisom-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bho_possuisom" id="bho_possuisom-0" value="0" class="block-subitem-cond">
            				<label for="bho_possuisom-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- dimensões -->
				   	<label for="bho_somdimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_somdimensoes">
				   	</div>
				   					   	
				   	<!-- modelo/marca -->
				   	<label for="bho_sommodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_sommodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_possuitvcabo" class="col-sm-4">TV a cabo:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bho_possuitvcabo" id="bho_possuitvcabo-1" value="1" class="block-subitem-cond">
            				<label for="bho_possuitvcabo-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bho_possuitvcabo" id="bho_possuitvcabo-0" value="0" class="block-subitem-cond">
            				<label for="bho_possuitvcabo-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- dimensões -->
				   	<label for="bho_tvcabodimensoes" class="col-sm-4 block-subitem">Dimensões:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_tvcabodimensoes">
				   	</div>
				   	
				   	<!-- modelo/marca -->
				   	<label for="bho_tvcabomodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_tvcabomodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_possuipc" class="col-sm-4">Possui PC:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bho_possuipc" id="bho_possuipc-1" value="1" class="block-subitem-cond">
            				<label for="bho_possuipc-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bho_possuipc" id="bho_possuipc-0" value="0" class="block-subitem-cond">
            				<label for="bho_possuipc-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- polegadas -->
				   	<label for="bho_pcpolegadasmonitor" class="col-sm-4 block-subitem">Polegadas monitor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_pcpolegadasmonitor">
				   	</div>
				   	
				   	<!-- modelo/marca -->
				   	<label for="bho_pcmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_pcmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_possuinotebook" class="col-sm-4">Possui Notebook:</label>
            		
            		<div class="col-sm-8">
						<div class="col-md-6">
            				<input type="radio" name="bho_possuinotebook" id="bho_possuinotebook-1" value="1" class="block-subitem-cond">
            				<label for="bho_possuinotebook-1">Sim</label>
						</div>
            			<div class="col-md-6">
							<input type="radio" name="bho_possuinotebook" id="bho_possuinotebook-0" value="0" class="block-subitem-cond">
            				<label for="bho_possuinotebook-0">Não</label>
						</div>
				   	</div>
				   	
				   	<!-- polegadas -->
				   	<label for="bho_notebookpolegadas" class="col-sm-4 block-subitem">Polegadas monitor:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_notebookpolegadas">
				   	</div>
				   	
				   	<!-- modelo/marca -->
				   	<label for="bho_notebookmodelomarca" class="col-sm-4 block-subitem">Modelo/Marca:</label>
				   	<div class="col-sm-8 block-subitem">
			   			<input type="text" class="form-control" name="bho_notebookmodelomarca">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="bho_obs" class="col-sm-4">Observações:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="bho_obs">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12 box-imagem">
      				<label for="bho_imagem" class="col-sm-4">Gostaria de nos enviar alguma imagem para nos inspirar a fazer o seu projeto?</label>
            		
            		<div class="col-sm-8">
				   		<input type="file" class="form-control" name="bho_imagem" />
				   		
				   		<div class="col-xs-10"></div>
				   	</div>
				</div>
			</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="concluirHomeOffice" class="btn btn-primary">Concluir</button>
      </div>
    </div>
  </div>
</div>