<div class="modal fade" id="modalBanheiro" tabindex="-1" role="dialog" aria-labelledby="modalBanheiroLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalBanheiroLabel">Briefing Banheiro</h4>
      </div>
      <div class="modal-body">
      		<form name="modalBanheiroForm" id="modalBanheiroForm" data-toggle="validator"
      			class="form-briefings form-horizontal" method="post" enctype="multipart/form-data">
      			<input type="hidden" name="acao" value="briefing-banheiro" />
      			<input type="hidden" name="id" value="" />
      			
				<div class="form-group col-xs-12">
				   	<!-- Descrição -->
				   	<label for="ban_descricao" class="col-sm-4">Descrição:</label>
				   	<div class="col-sm-8">
			   			<input type="text" class="form-control" name="ban_descricao">
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
				   	<!-- Tipo -->
				   	<label for="ban_tipo" class="col-sm-4">Tipo:</label>
				   	<div class="col-sm-8">
			   			<select class="form-control" name="ban_tipo">
			   				<option value="">Selecione...</option>
				   			<option value="1">Suíte</option>
				   			<option value="2">Feminino</option>
				   			<option value="3">Masculino</option>
				   			<option value="4">Lavabo/Social</option>
				   		</select>
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="ban_preferenciacores" class="col-sm-4">Preferência de cores:</label>
            		
            		<div class="col-sm-8">
            			<label class="col-md-6">
            				<input type="checkbox" name="ban_preferenciacores[]" value="1">
            				Claro
            			</label>
            			<label class="col-md-6">
            				<input type="checkbox" name="ban_preferenciacores[]" value="2">
            				Escuro
            			</label>
            			<label class="col-md-6">
            				<input type="checkbox" name="ban_preferenciacores[]" value="3">
            				Amadeirado
            			</label>
            			<label class="col-md-6">
            				<input type="checkbox" name="ban_preferenciacores[]" value="4">
            				Liso
            			</label>
            			<label class="col-md-6">
            				<input type="checkbox" name="ban_preferenciacores[]" value="5">
            				Colorido
            			</label>
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
				   	<!-- Cuba -->
				   	<label for="ban_cuba" class="col-sm-4">Cuba:</label>
				   	<div class="col-sm-8">
			   			<select class="form-control" name="ban_cuba">
			   				<option value="">Selecione...</option>
				   			<option value="1">Uma</option>
				   			<option value="2">Duas</option>
				   			<option value="3">Sobrepor</option>
				   			<option value="4">Normal</option>
				   		</select>
				   	</div>
				   	
				   	<!-- Medição  -->
				   	<label for="ban_cubadimensoes" class="col-sm-4">Lagura x Altura x Profundidade:</label>
				   	<div class="col-sm-8">
			   			<input type="text" class="form-control" name="ban_cubadimensoes">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="ban_secadorcabelo" class="col-sm-4">Secador de cabelo:</label>
            		
            		<div class="col-sm-8">
				   		<select class="form-control" name="ban_secadorcabelo" required>
				   			<option value="0" selected>Não</option>
				   			<option value="1">Sim</option>
				   		</select>
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="ban_chapinha" class="col-sm-4">Chapinha:</label>
            		
            		<div class="col-sm-8">
				   		<select class="form-control" name="ban_chapinha" required>
				   			<option value="0" selected>Não</option>
				   			<option value="1">Sim</option>
				   		</select>
				   	</div>				   	
				</div>
				
				<div class="form-group col-xs-12">
      				<label for="ban_barbeador" class="col-sm-4">Barbeador:</label>
            		
            		<div class="col-sm-8">
				   		<select class="form-control" name="ban_barbeador" required>
				   			<option value="0" selected>Não</option>
				   			<option value="1">Sim</option>
				   		</select>
				   	</div>				   	
				</div>

				<div class="form-group col-xs-12">
      				<label for="ban_armazenartoalhas" class="col-sm-4">Armazenar toalhas:</label>
            		
            		<div class="col-sm-8">
				   		<select class="form-control" name="ban_armazenartoalhas" required>
				   			<option value="0" selected>Não</option>
				   			<option value="1">Sim</option>
				   		</select>
				   	</div>				   	
				</div>

				<div class="form-group col-xs-12">
      				<label for="ban_armazenaroupasuja" class="col-sm-4">Armazenar roupa suja:</label>
            		
            		<div class="col-sm-8">
				   		<select class="form-control" name="ban_armazenaroupasuja" required>
				   			<option value="0" selected>Não</option>
				   			<option value="1">Sim</option>
				   		</select>
				   	</div>				   	
				</div>
							
				<div class="form-group col-xs-12">
				   	<!-- Tipo -->
				   	<label for="ban_misturadores" class="col-sm-4">Misturadores:</label>
				   	<div class="col-sm-8">
			   			<select class="form-control" name="ban_misturadores">
			   				<option value="">Selecione...</option>
				   			<option value="1">Tampo</option>
				   			<option value="2">Parede</option>
				   		</select>
				   	</div>				   	
				</div>
								
				<div class="form-group col-xs-12">
      				<label for="ban_obs" class="col-sm-4">Observações:</label>
            		
            		<div class="col-sm-8">
				   		<input type="text" class="form-control" name="ban_obs">
				   	</div>
				</div>
				
				<div class="form-group col-xs-12 box-imagem">
      				<label for="ban_imagem" class="col-sm-4">Gostaria de nos enviar alguma imagem?</label>
            		
            		<div class="col-sm-8">
				   		<input type="file" class="form-control" name="ban_imagem" />
				   		
				   		<div class="col-xs-10"></div>
				   	</div>
				</div>
			</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" id="concluirBanheiro" class="btn btn-primary">Concluir</button>
      </div>
    </div>
  </div>
</div>