<div id="briefing-complemento" class="section section-8-4 briefing-complemento-step col-lg-12">
	<div class="col-md-8">
		<div class="section-background">
			<img src="<?= $this->basePath('img/layout/B3.png'); ?>" />
		</div>
		
		<div class="col-xs-9">
			<h2>Como você deseja <br /> nos passar as medidas <br /> de seus ambientes?</h2>
			<p>Já sabemos o que você deseja, isso nos ajudará no desenvolvimento do
			ambiente de acordo com a sua vontade. Para isso, precisamos das 
			<b>medidas físicas disponíveis para acomodar o projeto.</b></p>
			<p>Por favor, selecione uma das opções ao lado.</p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="col-xs-12">
			<div class="col-xs-8 col-2-texto">
				Desejo que um <strong>vendedor</strong> faça as medições.
			</div>
			<div class="col-xs-4 col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step1" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step1"></label>
				</div>
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-xs-8 col-2-texto">
				<p>Enviarei os arquivos das medidas e fotos.</p>
				<p class="sub">Planta baixa, folder com medida dos espaços, etc.</p>
			</div>
			<div class="col-xs-4 col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step2" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step2"></label>
				</div>
			</div>
		</div>
		
		<div class="col-xs-12">
			<div class="col-xs-8 col-2-texto">
				<p>Eu farei a medição.</p>
				<p class="sub">Mas quero assistir o video com orientação antes.</p>
			</div>
			<div class="col-xs-4 col-2-controle">
				<div class="switch">
				  <input id="cmn-toggle-step4" class="cmn-toggle cmn-toggle-round" type="checkbox">
				  <label for="cmn-toggle-step4"></label>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="briefing-cadastro" tabindex="-1" role="dialog" aria-labelledby="modalbriefing-cadastroLabel" data-backdrop="static" data-keyboard="false">
  	<div class="modal-dialog" role="document">
    	<div class="modal-content">
      		<div class="modal-header">
      			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h2 id="modalbriefing-cadastroLabel">Estamos quase!</h2>
				<p>Por favor, complete os seus dados cadastrais. Mas lembre-se: <br />
				todo o processo e o orçamento gerado são <b>sem compromisso</b> de compra :)</p>
      		</div>
      		<div class="modal-body">
			  	<form name="modalCadastroForm" id="modalCadastroForm" data-toggle="validator"
					class="form-briefings form-horizontal" method="post" target="iframeCadastroForm" enctype="multipart/form-data">
					<input type="hidden" name="acao" value="completa-cadastro" />
					
					<div class="form-group col-xs-12 box-imagem">
						<label for="avatar" class="col-sm-4">Foto de perfil:</label>
						
						<div class="col-sm-8">
							<input type="file" class="form-control" name="avatar" />
							
							<div class="col-xs-10"></div>
						</div>
					</div>

					<div class="form-group col-xs-12">
						<label for="nome" class="col-sm-4">Nome completo:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control disabled" name="nome" disabled>
						</div>
					</div>
						
					<div class="form-group col-xs-12">
						<label for="email" class="col-sm-4">E-mail:</label>
						<div class="col-sm-8">
							<input type="email" class="form-control disabled" name="email" disabled>
						</div>
					</div>
								
					<div class="form-group col-xs-12">
						<label for="cpf" class="col-sm-4">CPF:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control" name="cpf" placeholder="999.999.999-99" required>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="rg" class="col-sm-4">RG:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control" name="rg" required>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="datanascimento" class="col-sm-4">Data de nascimento:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control" name="datanascimento" placeholder="99/99/9999" required>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="sexo" class="col-sm-4">Sexo:</label>
						
						<div class="col-sm-8">
							<div class="col-md-6">
								<input type="radio" name="sexo" id="sexo-m" value="M" checked>
								<label for="sexo-m">Masculino</label>
							</div>
							<div class="col-md-6">
								<input type="radio" name="sexo" id="sexo-f" value="F">
								<label for="sexo-f">Feminino</label>
							</div>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="endereco" class="col-sm-4">Endereço:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control" name="endereco" required>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="numero" class="col-sm-4">Número:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control" name="numero" required>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="bairro" class="col-sm-4">Bairro:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control" name="bairro" required>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="cidade" class="col-sm-4">Cidade:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control" name="cidade" required>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="cep" class="col-sm-4">Cep:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control" name="cep" placeholder="99999-999" required>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="fone_cel" class="col-sm-4">Telefone Celular:</label>
						
						<div class="col-sm-8">
							<!-- <input type="text" class="form-control disabled" name="fone_cel" disabled> -->
							<input type="text" class="form-control" name="fone_cel" required>
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="fone_com" class="col-sm-4">Telefone Comercial:</label>
						
						<div class="col-sm-8">
							<input type="text" class="form-control" name="fone_com" placeholder="(xx) 9xxxx-xxxx">
						</div>
					</div>
					
					<div class="form-group col-xs-12">
						<label for="obs" class="col-sm-4">Observações:</label>
						
						<div class="col-sm-8">
							<textarea class="form-control" name="obs" rows="4"></textarea>
						</div>
					</div>
				</form>
	  		</div>
	  		<div class="modal-footer">
			  	<button class="btn btn-default btn-voltar" data-dismiss="modal" aria-label="Close">FECHAR</button>
			  	<button class="btn btn-primary btn-avancar">CONCLUIR</button>
      		</div>
    	</div>
  	</div>
</div>

<div id="briefing-vendedor" class="section section-8-4 briefing-complemento-step col-lg-12">
	<div class="col-md-8">
		<div class="section-background">
			<img src="<?= $this->basePath('img/layout/B4.png'); ?>" />
		</div>
		
		<div class="col-xs-9">
			<p>Você selecionou:</p>
			<h2>Desejo que um<br>vendedor faça as<br>medições.</h2>
		</div>
	</div>

	<div class="col-md-4">
		<div class="col-xs-12">
			<strong>Informe a data e horário para<br>o agendamento da medição:</strong>
		</div>
		
		<form name="agendaMedicao" id="agendaMedicao" data-toggle="validator" method="post">

			<div class="form-group">
				<label for="agenda-dia">QUAL A MELHOR DATA PARA VOCÊ?</label>
			</div>
				
			<div class="form-group">
				<input type="text" class="form-control" name="dia" value="<?= $this->agendaMedicao['dia'] ?>"
					placeholder="12/12/2010" required />
			</div>

			<div class="form-group">
				<label for="agenda-horas" style="text-align: right;">E O MELHOR HORÁRIO?</label>
			</div>
				
			<div class="form-group">
				<input type="text" class="form-control" name="horas" value="<?= $this->agendaMedicao['horas'] ?>"
					placeholder="18:00" required />
			</div>
			
			<div class="form-group hide-mobile" style="padding-top: 60px">
				<button type="button" class="btn btn-block btn-avancar">ENVIAR</button>			
			</div>
			<div class="form-group hide-mobile">
				<button type="button" class="btn btn-block btn-voltar">VOLTAR</button>
			</div>

			<div class="form-group show-mobile">
				<div class="col-xs-6">
					<button type="button" class="btn btn-block btn-voltar-mobile">VOLTAR</button>
				</div>
				<div class="col-xs-6">
					<button type="button" class="btn btn-block btn-avancar">ENVIAR</button>			
				</div>
			</div>
		</form>
	</div>
</div>

<div id="briefing-arquivos1" class="section section-8-4 briefing-complemento-step col-lg-12">
	<div class="col-md-8">
		<div class="section-background">
			<img src="<?= $this->basePath('img/layout/B5.png'); ?>" />
		</div>
		
		<div class="col-xs-9">
			<p>Você selecionou:</p>
			<h2>Enviarei os<br>arquivos das<br>medidas e fotos.</h2>
			<p>Serão aceitos arquivos nos formatos JPG e PNG, com resolução máxima de 300dpi.</p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="col-xs-12" style="text-align: center;">
			<p>Selecione os arquivos a serem enviados conforme o ambiente.</p>
			<p class="sub">Após o anexo do arquivo, utilize o botão [+] para adicionar o próximo.</p>
		</div>
		
		<form name="formArquivosBriefings" id="formArquivosBriefings" target="iframeArquivosBriefings"
			method="post" class="form-horizontal" enctype="multipart/form-data"
				action="<?php echo $this->url('clientes', array('action' => 'uploadArquivosBriefings')); ?>">

		<?php foreach($this->listaCozinha as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia">Nome do ambiente:</label>
					<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
						value="<?= $item->descricao; ?>" readonly="readonly" />
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-8">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-4">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaAreaServico as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia">Nome do ambiente:</label>
					<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
						value="<?= $item->bas_descricao; ?>" readonly="readonly" />
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-8">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-4">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaDormitorioCasal as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia">Nome do ambiente:</label>
					<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
						value="<?= $item->bdc_descricao; ?>" readonly="readonly" />
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-8">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-4">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaDormitorioSolteiro as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia">Nome do ambiente:</label>
					<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
						value="<?= $item->bds_descricao; ?>" readonly="readonly" />
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-8">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-4">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaCloset as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia">Nome do ambiente:</label>
					<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
						value="<?= $item->bcl_descricao; ?>" readonly="readonly" />
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-8">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-4">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaBanheiro as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia">Nome do ambiente:</label>
					<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
						value="<?= $item->ban_descricao; ?>" readonly="readonly" />
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-8">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-4">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaHomeTheater as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia">Nome do ambiente:</label>
					<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
						value="<?= $item->bht_descricao; ?>" readonly="readonly" />
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-8">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-4">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

		<?php foreach($this->listaHomeOffice as $item): ?>	
			<div class="col-md-12">
				<div class="form-group col-xs-12">
					<label for="agenda-dia">Nome do ambiente:</label>
					<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][nome]" 
						value="<?= $item->bho_descricao; ?>" readonly="readonly" />
				</div>

				<div class="form-group col-xs-12">
					<div class="col-xs-8">
						<input type="text" class="form-control" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][path]" readonly="readonly" />
					</div>
					<div class="col-xs-4">
						<span class="pesquisar-arquivo pull-left">Pesquisar</span>
						<input type="file" class="form-control hide" name="briefing[<?= strtolower($item->tp)?>][<?= $item->idbriefing?>][arquivos][]" />

						<span class="adicionar-arquivo glyphicon glyphicon-plus pull-right"></span>
					</div>
				</div>
			</div>
		<?php endforeach; ?>

			<div class="form-group hide-mobile">
				<button type="button" class="btn btn-block btn-avancar">ENVIAR</button>			
			</div>
			<div class="form-group hide-mobile">
				<button type="button" class="btn btn-block btn-voltar">VOLTAR</button>
			</div>

			<div class="form-group show-mobile">
				<div class="col-xs-6">
					<button type="button" class="btn btn-block btn-voltar-mobile">VOLTAR</button>
				</div>
				<div class="col-xs-6">
					<button type="button" class="btn btn-block btn-avancar">ENVIAR</button>			
				</div>
			</div>
		</form>
	</div>
</div>

<div id="briefing-videos" class="section section-8-4 briefing-complemento-step col-lg-12">
	<div class="col-md-8">
		<div class="section-background">
			<img src="<?= $this->basePath('img/layout/B6.png'); ?>" />
		</div>
		
		<div class="col-xs-9">
			<p>Você selecionou:</p>
			<h2>Eu farei<br>a medição.</h2>
			<p>O vídeo ao lado contém orientações para que <b>você mesmo</b> faça a medição dos seus ambientes.<br>
			Para anotar as medidas que serão enviadas posteriormente através de fotos, você pode <b>imprimir o formulário orientativo</b>
			ao lado ou utilizar uma folha em branco. 
			</p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="col-xs-12">
			<p class="p1">No vídeo abaixo, <br />você encontra orientações <br />para tirar as medidas:</p>
		</div>
		
		<div class="col-xs-12 youtube hide-mobile">
			<a data-href="https://www.youtube.com/watch?v=IKjj557f4nQ">
				<img class="imgYoutube" src="<?= $this->basePath('img/youtube.png'); ?>" />
			</a>
		</div>
		<div class="col-xs-12 youtube show-mobile">
			<a data-href="https://www.youtube.com/watch?v=IKjj557f4nQ">
				<div class="icone-download">
					<img class="imgYoutube" src="<?= $this->basePath('img/iconeYoutube.png'); ?>" />
				</div>
				<p class="pdownload">Orientações de Medição</p>
			</a>
		</div>
		<div class="col-xs-12">
			<a href="<?= $this->basePath('download/FolhaMilimetrada.pdf'); ?>" download>
				<div class="icone-download">
					<img src="<?= $this->basePath('img/iconeDownload.png'); ?>" width="16" height="16" class="img-responsive"/>
				</div>
				<p class="pdownload">Download do Formulário Orientativo</p>
			</a>
		</div>
		<div class="col-xs-12">
			<h2>ATENÇÃO:</h2>
			<p class="p2">Utilize seu celular para registrar fotos das suas anotações e retorne à opção de envio de arquivos, 
			onde você também pode nos enviar imagens e detalhes dos seus ambientes. :)</p>
		</div>

		<!-- <button class="btn btn-primary btn-voltar pull-left">VOLTAR</button> -->
		<div class="form-group hide-mobile">
			<button type="button" class="btn btn-block btn-avancar">ENVIO DE ARQUIVOS</button>			
		</div>
		<div class="form-group hide-mobile">
			<button type="button" class="btn btn-block btn-voltar">VOLTAR</button>
		</div>	
		
		<div class="form-group show-mobile">
			<div class="col-xs-6">
				<button type="button" class="btn btn-block btn-voltar-mobile">VOLTAR</button>
			</div>
			<div class="col-xs-6">
				<button type="button" class="btn btn-block btn-avancar">ENVIAR</button>			
			</div>
		</div>
	</div>
</div>

<!-- 
<div id="briefing-obrigado" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Obrigado! <3
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12" style="margin-top: 30px;">
			Agora temos as informações para poder fazer<br/>
			<strong>o projeto que se adapta ao seu desejo.</strong>
		</div>
		
		<div class="col-xs-12" style="margin-top: 30px;">
			Num prazo de 48h após a medição você receberá a apresentação dos projetos e orçamento.
		</div>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-fechar pull-right">FECHAR</button>
	</div>
</div>

<div id="briefing-obrigado-vendedor" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Obrigado! <3
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12" style="margin-top: 30px;">
			Após a realização das medições pelo vendedor, estaremos<br/>
			com todas as informações para realizar o <strong>projeto que se adapta ao seu desejo.</strong>
		</div>
		
		<div class="col-xs-12" style="margin-top: 30px;">
			Num prazo de 48h após a medição você receberá a apresentação dos projetos e orçamento.
		</div>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-fechar pull-right">FECHAR</button>
	</div>
</div>

<div id="briefing-obrigado-arquivos" class="briefing-complemento-step">
	<div class="col-1 col-xs-12">
		Obrigado! <3
	</div>
	
	<div class="col-2 col-xs-12">
		<div class="col-xs-12" style="margin-top: 30px;">
			Agora temos as informações para poder fazer<br/>
			<strong>o projeto que se adapta ao seu desejo.</strong>
		</div>
	</div>
	
	<div class="col-3 col-xs-12">
		<button class="btn btn-primary btn-fechar pull-right">FECHAR</button>
	</div>
</div>
-->

<div class="modal fade" id="briefing-obrigado-vendedor" tabindex="-1" role="dialog" aria-labelledby="modalbriefing-obrigadovenderoLabel" data-backdrop="static" data-keyboard="false">
  	<div class="modal-dialog" role="document">
    	<div class="modal-content">
      		<div class="modal-header">
      			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h2 id="modalbriefing-obrigadovenderoLabel">Obrigado! :)</h2>
				<p class="p1">Após a realização das medições pelo vendedor, estaremos com todas as informações para realizar o projeto que se adapta ao seu desejo.</p>
				<p class="p2">Em um prazo de 48h após a medição você receberá a apresentação dos projetos e orçamento.</p>
      		</div>
	  		<div class="modal-footer">
			  	<button class="btn btn-default btn-fechar" data-dismiss="modal" aria-label="Close">FECHAR</button>
      		</div>
    	</div>
  	</div>
</div>
 
<div class="modal fade" id="briefing-obrigado-arquivos" tabindex="-1" role="dialog" aria-labelledby="modalbriefing-obrigadoarquivosLabel" data-backdrop="static" data-keyboard="false">
  	<div class="modal-dialog" role="document">
    	<div class="modal-content">
      		<div class="modal-header">
      			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h2 id="modalbriefing-obrigadoarquivosLabel">Obrigado! :)</h2>
				<p class="p1">Agora temos as informações necessárias para poder realizar o projeto que se adapta ao seu desejo e a sua necessidade.</p>
				<p class="p2">Em um prazo de 48h após a medição você receberá a apresentação dos projetos e orçamento.</p>
      		</div>
	  		<div class="modal-footer">
			  	<button class="btn btn-default btn-fechar" data-dismiss="modal" aria-label="Close">FECHAR</button>
      		</div>
    	</div>
  	</div>
</div>
 
<div id="section-confirmar-mobile">
	<?php include __DIR__ . '/confirmar-mobile.phtml'; ?>
</div> 

<!-- iframeCadastroForm -->
<iframe name="iframeCadastroForm" id="iframeCadastroForm" class="hide"></iframe>

<!-- iframeArquivosBriefings -->
<iframe name="iframeArquivosBriefings" id="iframeArquivosBriefings" class="hide"></iframe>

<!-- iframeVideosYoutube -->
<div id="btn-fechar-youtube"><button class="btn btn-primary pull-right">FECHAR VIDEO</button></div>
<iframe name="iframeVideosYoutube" id="iframeVideosYoutube" frameborder="0" allowfullscreen></iframe>


<!-- datepicker -->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" 
	integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  		crossorigin="anonymous"></script>
<!-- timepicker -->
<link rel="stylesheet" href="<?php echo $this->basePath('lib/timepicker/jquery.timepicker.css'); ?>" />
<script src="<?php echo $this->basePath('lib/timepicker/jquery.timepicker.min.js'); ?>"></script>

<script type="text/javascript">
$(document).ready(function(){
	ajustaWidHei = function(){
		if($(window).width() < 800){

			var menuHeight = ($(window).height() * 0.60) + 'px';
			$('.section-background img').css('height', menuHeight);
		}else{
			$('body').css('overflow', 'hidden');
			$('#section-content').css('overflow-x', 'hidden');

			var menuHeight = $('#menu-nav-left').outerHeight() + 'px';
			$('.section-background img').css('height', menuHeight);
		}
	};

	// ajustes iniciais
	ajustaWidHei();

	// ajusta dimensoes em monitoramento
	setInterval(function(){
		ajustaWidHei();
	}, 300);
});
</script>

<script type="text/javascript">
	modalCadastroCallback = null;
	showModalCadastro = function(callback){
		modalCadastroCallback = callback;
		$.post(
			'<?=$this->url('clientes', array('action' => 'completaCadastro'));?>',
			{acao: 'checa-cadastro'},
			function(resp){
				//modalCadastroCallback();
				if(resp.data == true){
					modalCadastroCallback();					
				}else{
					$('#modalCadastroForm input[name="nome"]').val(resp.data.nome);
					$('#modalCadastroForm input[name="email"]').val(resp.data.email);
					$('#modalCadastroForm input[name="fone_cel"]').val(resp.data.fone_cel);

					$('#briefing-cadastro').modal('show');
				}
			},
			'json'
		);
	};
$(function(){
	// ajusta switchs
	$('.cmn-toggle:checked').prop('checked',false);

	// apresenta conteudo
	if($(window).width() > 800){
		$('.briefing-complemento-step').hide();
		$('#section-briefings').hide();
		if(!$('#briefing-complemento').is(':visible')){
			$('#briefing-complemento').fadeIn();
		}
	}

	$('#briefing-cadastro .btn-voltar').click(function(){
		$('#briefing-complemento .cmn-toggle').prop('checked', false);
		$('.briefing-complemento-step').hide();
		$('#briefing-complemento').show();
	});
	
	$('#briefing-cadastro .close').click(function(){
		$('#briefing-complemento .cmn-toggle').prop('checked', false);
		$('.briefing-complemento-step').hide();
		$('#briefing-complemento').show();
	});
	
	$('#cmn-toggle-step1').on('click', function(){
		if($(this).parents('.switch').find('input:checkbox').is(':checked')){
			var callback = function(){
				$('.briefing-complemento-step').hide();
				$('#briefing-vendedor').fadeIn();
				$('#briefing-cadastro').modal('hide');
			};
			showModalCadastro(callback);
		}
	});
	$('#briefing-vendedor .btn-voltar').click(function(){
		$('#cmn-toggle-step1').prop('checked', false);
		$('.briefing-complemento-step').hide();
		$('#briefing-complemento').fadeIn();
	});
	
	$('#cmn-toggle-step2').on('click', function(){
		if($(this).parents('.switch').find('input:checkbox').is(':checked')){
			var callback = function(){
				$('.briefing-complemento-step').hide();
				$('#briefing-arquivos1').fadeIn();
			};
			showModalCadastro(callback);
		}
	});
	$('#briefing-arquivos1 .btn-voltar').click(function(){
		$('#cmn-toggle-step2').prop('checked', false);
		$('.briefing-complemento-step').hide();
		$('#briefing-complemento').fadeIn();
	});
	
	$('#cmn-toggle-step4').on('click', function(){
		if($(this).parents('.switch').find('input:checkbox').is(':checked')){
			var callback = function(){
				$('.briefing-complemento-step').hide();
				$('#briefing-videos').fadeIn();
			};
			showModalCadastro(callback);
		}
	});
	$('#briefing-videos .btn-voltar').click(function(){
		$('#cmn-toggle-step4').prop('checked', false);
		$('.briefing-complemento-step').hide();
		$('#briefing-complemento').fadeIn();
	});

	$('#briefing-obrigado-vendedor .btn-fechar').click(function(){
		window.location = "<?php echo $this->url('home'); ?>"
	});

	$('#briefing-obrigado-vendedor .close').click(function(){
		window.location = "<?php echo $this->url('home'); ?>"
	});

	$('#briefing-obrigado-arquivos .btn-fechar').click(function(){
		window.location = "<?php echo $this->url('home'); ?>"
	});

	$('#briefing-obrigado-arquivos .close').click(function(){
		window.location = "<?php echo $this->url('home'); ?>"
	});

	$('#briefing-cadastro .btn-avancar').click(function(e){
		$('#modalCadastroForm').submit();	
	});

	$('#modalCadastroForm').validator().on('submit', function (e) {
		if (e.isDefaultPrevented()) {
			// handle the invalid form...
			return false;
		} else {
			$(this).attr('action', '<?=$this->url('clientes', array('action' => 'completaCadastro'));?>');
			return true;
		}
	});
	$('#iframeCadastroForm').on('load', function (e) {
		var response = JSON.parse($(this).contents().find('body').get(0).innerHTML);
		if(response.data == true){
			$('#briefing-cadastro').hide();
			$('.modal-backdrop').hide();
			modalCadastroCallback();
		}else{
			alert(response.data);
		}
	});

	$('#briefing-vendedor .btn-avancar').click(function(e){
		$('#agendaMedicao').submit();	
	});

	$('#agendaMedicao').validator().on('submit', function (e) {
		if (e.isDefaultPrevented()) {
			// handle the invalid form...
		} else {
			$.post(
				'<?=$this->url('clientes', array('action' => 'agendaMedicao'));?>',
				$(this).serialize(),
				function(resp){
					if(resp.data == true){
						$('.briefing-complemento-step input:checkbox').prop('checked', false);
						//$('.briefing-complemento-step').hide();
						//$('#briefing-obrigado-vendedor').fadeIn();
						$('#briefing-obrigado-vendedor').modal('show');
					}else{
						alert(resp.data);
					}
				},
				'json'
			);
		}
		return false;
	});

	$('#briefing-arquivos1 .btn-avancar').click(function(e){
		$('#formArquivosBriefings').submit();	
	});

	$('#iframeArquivosBriefings').on('load', function (e) {
		var response = JSON.parse($(this).contents().find('body').get(0).innerHTML);
		// caso nenhum arquivo tenha sido enviado
		// ou ocorreu um erro
		if(response.files == 0){
			alert(response.data);
		}else{
			$('.briefing-complemento-step input:checkbox').prop('checked', false);
			//$('.briefing-complemento-step').hide();
			//$('#briefing-obrigado-arquivos').fadeIn();
			$('#briefing-obrigado-arquivos').modal('show');
		}
	});

	$('#briefing-videos .youtube a').click(function(e){
		e.stopPropagation();

		var linkHref = $(this).attr('data-href');
		var iframe = $('#iframeVideosYoutube');
			iframe.attr('src', 'https://www.youtube.com/embed/' + linkHref.replace(/(.*)v\=/, ""));
		
		$('#background-frames').css('z-index', 100002);
		$('#btn-fechar-youtube').fadeIn();
		$(iframe).fadeIn();

		return false;
	});

	$('#btn-fechar-youtube button').click(function(){
		var iframe = $('#iframeVideosYoutube');
			iframe.attr('src','about:blank');
		
		$(iframe).fadeOut();
		$('#btn-fechar-youtube').fadeOut();
		$('#background-frames').css('z-index', 100000);
	});

	$('body').on('click', '.pesquisar-arquivo', function(){
		$(this).parent().find('input:file').click();
	});
	$('body').on('change', '#formArquivosBriefings .form-group input:file', function(){
		var arquivoPath = $(this).val();
			arquivoPath = arquivoPath.replace(/^.*(\/|\\)/, "");
			
			$(this).parents('.form-group').find('input:text').val(arquivoPath);
	});
	$('body').on('click', '.adicionar-arquivo', function(){
		var clonaArquivo = $(this).parents('.form-group').clone();
		// esconde botao add
		$(this).parents('.form-group').find('.adicionar-arquivo').hide();
		
		// limpa campos
		$(clonaArquivo).find('input:file').val('');
		$(clonaArquivo).find('input:text').val('');
		$(clonaArquivo).find('.adicionar-arquivo').show();

		// clona input
		$(this).parents('.col-md-12').append(clonaArquivo);
	});

	// mascaras medicao vendedor
	$('input[name="dia"]').datepicker({
        dateFormat: 'dd/mm/yy',
        dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
        dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
        dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
        monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
        monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']
    });
	$('input[name="dia"]').mask('99/99/9999');
	$('input[name="dia"]').blur(function(){
		if(/^([0-9]{2})\/([0-9]{2})\/([0-9]{4})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
	$('input[name="horas"]').timepicker({ 'timeFormat': 'H:i' });
	$('input[name="horas"]').mask('99:99');
	$('input[name="horas"]').blur(function(){
		if(/^([0-9]{2})\:([0-9]{2})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});

	// mascaras complemento cadastro
	$('input[name="cpf"]').mask('999.999.999-99');
	$('input[name="cpf"]').blur(function(){
		if(/^([0-9]{3})\.([0-9]{3})\.([0-9]{3})\-([0-9]{2})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
	$('input[name="datanascimento"]').mask('99/99/9999');
	$('input[name="datanascimento"]').blur(function(){
		if(/^([0-9]{2})\/([0-9]{2})\/([0-9]{4})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
	$('input[name="cep"]').mask('99999-999');
	$('input[name="cep"]').blur(function(){
		if(/^([0-9]{5})\-([0-9]{3})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
	$('input[name="fone_com"]').mask('(99) 99999-9999');
	$('input[name="fone_com"]').blur(function(){
		if(/^\([0-9]{2}\) ([0-9]{5})\-([0-9]{3,4})$/.test($(this).val()) == false){
			$(this).val('');	
		}
	});
});
</script>