<div id="brief-confirmar-inical" class="brief-telas col-xs-12">
    <div class="brief-telas-title col-xs-12">
        <h2>Como você deseja nos passar as medidas de seus ambientes?</h2>
        <p>
            Precisamos das <b>medidas físicas disponíveis para acomodar o seu projeto</b> 
            Por favor, selecione uma das opções abaixo:
        </p>
    </div>
    
    <div class="brief-confirmar-item">
        <button id="brief-confirmar-vendedor" style="padding-left: 50px;">
            Desejo que um <br /> vendedor faça as <br /> medições.
        </button>
    </div>

    <div class="brief-confirmar-item">
        <button id="brief-confirmar-arquivos">
            Enviarei os arquivos <br /> das medidas e fotos. <br />
            <span>
                Planta baixa, folders <br />
                com medidas do espaço, etc.
            </span>
        </button>
    </div>

    <div class="brief-confirmar-item">
        <button id="brief-confirmar-videos">
            Eu farei <br /> a medição. <br />
            <span>
                Mas quero assitir o <br />
                vídeo com orientação antes.
            </span>
        </button>
    </div>
</div>

<script type="text/javascript">
    $('.btn-voltar-mobile').on('click', function(){
        $('.briefing-complemento-step').hide();
        $('#brief-confirmar-inical').fadeIn();
    });
    $('#brief-confirmar-vendedor').on('click', function(){
		var callback = function(){
            $('#brief-confirmar-inical').hide();
            $('#briefing-vendedor').fadeIn();
            $('#briefing-cadastro').modal('hide');
            $(window).scrollTop(0);
        };
        showModalCadastro(callback);
	});
    $('#brief-confirmar-arquivos, #briefing-videos .btn-avancar').on('click', function(){
		var callback = function(){
            $('#brief-confirmar-inical, .briefing-complemento-step').hide();
            $('#briefing-arquivos1').fadeIn();
            $('#briefing-cadastro').modal('hide');
            $(window).scrollTop(0);
        };
        showModalCadastro(callback);
	});
    $('#brief-confirmar-videos').on('click', function(){
		var callback = function(){
            $('#brief-confirmar-inical').hide();
            $('#briefing-videos').fadeIn();
            $('#briefing-videos .col-md-4 .col-xs-12:last').css('margin-top', '15px');
            $('#briefing-videos .show-mobile:first').css('margin-top', '-10px');
            $('#briefing-cadastro').modal('hide');
            $(window).scrollTop(0);
        };
        showModalCadastro(callback);
	});
</script>