<div id="section-briefings" class="section section-8-4 col-lg-12">
	<div class="col-md-8">
		<div class="section-background">
			<img src="<?= $this->basePath('img/layout/B2.png'); ?>" />
		</div>
		
		<div class="col-xs-9">
			<h2>Conte mais <br /> sobre o que você <br /> procura.</h2>
			<p>Daqui, começaremos a levantar informações sobre o <b>projeto que você deseja realizar.</b>
				É muito importante que você nos repasse suas necessidades e desejos com atenção, para que possamos
				transformá-los no seu sonho, dentro da sua casa.</p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="col-lg-12">
			<h2>Quais ambientes <br /> você gostaria de planejar?</h2>
		</div>
				
		<?php if($this->success):?>
			<div class="alert alert-success col-xs-12" role="alert"><?= $this->success; ?></div>
		<?php endif;?>
				
		<?php if($this->error):?>
			<div class="alert alert-danger col-xs-12" role="alert"><?= $this->error; ?></div>
		<?php endif;?>
		
		<!-- Cozinha -->
		<div class="briefing-item col-xs-12">
			<div class="col-xs-8"> 
				Cozinha
			</div>
			<div class="col-xs-4">
				<div class="switch">
					<input id="cmn-toggle-cozinha" class="cmn-toggle cmn-toggle-round" type="checkbox" <?php echo (count($this->listaCozinha) > 0)? 'checked': null; ?>>
					<label for="cmn-toggle-cozinha"></label>
				</div>
			</div>
			
			<div class="briefing-grid col-xs-12">
				<?php foreach($this->listaCozinha as $item): ?>
					<div class="briefing-grid-item col-xs-12">
						<div class="col-xs-8">
							<?= $item->descricao; ?>
						</div>
						<div class="col-xs-4">
							<a onclick="return alterarBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Alterar</a>
							<a onclick="return removerBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Excluir</a>
						</div>
					</div>
				<?php endforeach;?>
				<!-- adicionar -->
				<div class="col-xs-12">
					<a role="button" onclick="return criarBriefing('cozinha')">+ Adicionar Cozinha</a>
				</div>
			</div>
		</div>
		
		<!-- Área de Serviço -->
		<div class="briefing-item col-xs-12">
			<div class="col-xs-8">
				Área de Serviço
			</div>
			<div class="col-xs-4">
				<div class="switch">
					<input id="cmn-toggle-areaServico" class="cmn-toggle cmn-toggle-round" type="checkbox" <?php echo (count($this->listaAreaServico) > 0)? 'checked': null; ?>>
					<label for="cmn-toggle-areaServico"></label>
				</div>
			</div>
			
			<div class="briefing-grid col-xs-12">
				<?php foreach($this->listaAreaServico as $item): ?>
					<div class="briefing-grid-item col-xs-12">
						<div class="col-xs-8">
							<?= $item->bas_descricao; ?>
						</div>
						<div class="col-xs-4">
							<a onclick="return alterarBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Alterar</a>
							<a onclick="return removerBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Excluir</a>
						</div>
					</div>
				<?php endforeach;?>
				<!-- adicionar -->
				<div class="col-xs-12">
					<a role="button" onclick="return criarBriefing('areaServico')">+ Adicionar Área de Serviço</a>
				</div>
			</div>
		</div>
		
		<!-- Dormitório Casal -->
		<div class="briefing-item col-xs-12">
			<div class="col-xs-8">
				Dormitório Casal
			</div>
			<div class="col-xs-4">
				<div class="switch">
					<input id="cmn-toggle-dormitoriocasal" class="cmn-toggle cmn-toggle-round" type="checkbox" <?php echo (count($this->listaDormitorioCasal) > 0)? 'checked': null; ?>>
					<label for="cmn-toggle-dormitoriocasal"></label>
				</div>
			</div>
			
			<div class="briefing-grid col-xs-12">
				<?php foreach($this->listaDormitorioCasal as $item): ?>
					<div class="briefing-grid-item col-xs-12">
						<div class="col-xs-8">
							<?= $item->bdc_descricao; ?>
						</div>
						<div class="col-xs-4">
							<a onclick="return alterarBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Alterar</a>
							<a onclick="return removerBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Excluir</a>
						</div>
					</div>
				<?php endforeach;?>
				<!-- adicionar -->
				<div class="col-xs-12">
					<a role="button" onclick="return criarBriefing('dormitoriocasal')">+ Adicionar Dormitório Casal</a>
				</div>
			</div>
		</div>
		
		<!-- Dormitório Solteiro -->
		<div class="briefing-item col-xs-12">
			<div class="col-xs-8">
				Dormitório Solteiro
			</div>
			<div class="col-xs-4">
				<div class="switch">
					<input id="cmn-toggle-dormitoriosolteiro" class="cmn-toggle cmn-toggle-round" type="checkbox" <?php echo (count($this->listaDormitorioSolteiro) > 0)? 'checked': null; ?>>
					<label for="cmn-toggle-dormitoriosolteiro"></label>
				</div>
			</div>
			
			<div class="briefing-grid col-xs-12">
				<?php foreach($this->listaDormitorioSolteiro as $item): ?>
					<div class="briefing-grid-item col-xs-12">
						<div class="col-xs-8">
							<?= $item->bds_descricao; ?>
						</div>
						<div class="col-xs-4">
							<a onclick="return alterarBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Alterar</a>
							<a onclick="return removerBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Excluir</a>
						</div>
					</div>
				<?php endforeach;?>
				<!-- adicionar -->
				<div class="col-xs-12">
					<a role="button" onclick="return criarBriefing('dormitoriosolteiro')">+ Adicionar Dormitório Solteiro</a>
				</div>
			</div>
		</div>
		
		<!-- Closet -->
		<div class="briefing-item col-xs-12">
			<div class="col-xs-8">
				Closet
			</div>
			<div class="col-xs-4">
				<div class="switch">
					<input id="cmn-toggle-closet" class="cmn-toggle cmn-toggle-round" type="checkbox" <?php echo (count($this->listaCloset) > 0)? 'checked': null; ?>>
					<label for="cmn-toggle-closet"></label>
				</div>
			</div>
			
			<div class="briefing-grid col-xs-12">
				<?php foreach($this->listaCloset as $item): ?>
					<div class="briefing-grid-item col-xs-12">
						<div class="col-xs-8">
							<?= $item->bcl_descricao; ?>
						</div>
						<div class="col-xs-4">
							<a onclick="return alterarBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Alterar</a>
							<a onclick="return removerBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Excluir</a>
						</div>
					</div>
				<?php endforeach;?>
				<!-- adicionar -->
				<div class="col-xs-12">
					<a role="button" onclick="return criarBriefing('closet')">+ Adicionar Closet</a>
				</div>
			</div>
		</div>
		
		<!-- Banheiro -->
		<div class="briefing-item col-xs-12">
			<div class="col-xs-8">
				Banheiro
			</div>
			<div class="col-xs-4">
				<div class="switch">
					<input id="cmn-toggle-banheiro" class="cmn-toggle cmn-toggle-round" type="checkbox" <?php echo (count($this->listaBanheiro) > 0)? 'checked': null; ?>>
					<label for="cmn-toggle-banheiro"></label>
				</div>
			</div>
			
			<div class="briefing-grid col-xs-12">
				<?php foreach($this->listaBanheiro as $item): ?>
					<div class="briefing-grid-item col-xs-12">
						<div class="col-xs-8">
							<?= $item->ban_descricao; ?>
						</div>
						<div class="col-xs-4">
							<a onclick="return alterarBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Alterar</a>
							<a onclick="return removerBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Excluir</a>
						</div>
					</div>
				<?php endforeach;?>
				<!-- adicionar -->
				<div class="col-xs-12">
					<a role="button" onclick="return criarBriefing('banheiro')">+ Adicionar Banheiro</a>
				</div>
			</div>
		</div>
		
		<!-- Home Theater -->
		<div class="briefing-item col-xs-12">
			<div class="col-xs-8">
				Home Theater
			</div>
			<div class="col-xs-4">
				<div class="switch">
					<input id="cmn-toggle-hometheater" class="cmn-toggle cmn-toggle-round" type="checkbox" <?php echo (count($this->listaHomeTheater) > 0)? 'checked': null; ?>>
					<label for="cmn-toggle-hometheater"></label>
				</div>
			</div>
			
			<div class="briefing-grid col-xs-12">
				<?php foreach($this->listaHomeTheater as $item): ?>
					<div class="briefing-grid-item col-xs-12">
						<div class="col-xs-8">
							<?= $item->bht_descricao; ?>
						</div>
						<div class="col-xs-4">
							<a onclick="return alterarBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Alterar</a>
							<a onclick="return removerBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Excluir</a>
						</div>
					</div>
				<?php endforeach;?>
				<!-- adicionar -->
				<div class="col-xs-12">
					<a role="button" onclick="return criarBriefing('hometheater')">+ Adicionar Home Theater</a>
				</div>
			</div>
		</div>
		
		<!-- Home Office -->
		<div class="briefing-item col-xs-12">
			<div class="col-xs-8">
				Home Office
			</div>
			<div class="col-xs-4">
				<div class="switch">
					<input id="cmn-toggle-homeoffice" class="cmn-toggle cmn-toggle-round" type="checkbox" <?php echo (count($this->listaHomeOffice) > 0)? 'checked': null; ?>>
					<label for="cmn-toggle-homeoffice"></label>
				</div>
			</div>
			
			<div class="briefing-grid col-xs-12">
				<?php foreach($this->listaHomeOffice as $item): ?>
					<div class="briefing-grid-item col-xs-12">
						<div class="col-xs-8">
							<?= $item->bho_descricao; ?>
						</div>
						<div class="col-xs-4">
							<a onclick="return alterarBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Alterar</a>
							<a onclick="return removerBriefing('<?= strtolower($item->tp)?>', <?= $item->idbriefing?>);">Excluir</a>
						</div>
					</div>
				<?php endforeach;?>
				<!-- adicionar -->
				<div class="col-xs-12">
					<a role="button" onclick="return criarBriefing('homeoffice')">+ Adicionar Home Office</a>
				</div>
			</div>
		</div>
		
		<div class="briefing-item col-xs-12">
			<button class="btn btn-default" id="btn-confirmar-ambientes">Confirmar Ambientes</button> 
		</div>				
	</div>

	<div id="section-briefings-mobile">
		<?php include __DIR__ . '/index-mobile.phtml'; ?>
	</div>

	<!-- Modal formulário-->
	<?php include __DIR__ . '/_modalAreaServico.phtml'; ?>
	<?php include __DIR__ . '/_modalBanheiro.phtml'; ?>
	<?php include __DIR__ . '/_modalCloset.phtml'; ?>
	<?php include __DIR__ . '/_modalCozinha.phtml'; ?>
	<?php include __DIR__ . '/_modalDormitorioCasal.phtml'; ?>
	<?php include __DIR__ . '/_modalDormitorioSolteiro.phtml'; ?>
	<?php include __DIR__ . '/_modalDormitorioInfantil.phtml'; ?>
	<?php include __DIR__ . '/_modalHomeTheater.phtml'; ?>
	<?php include __DIR__ . '/_modalHomeOffice.phtml'; ?>
	
</div>

<script type="text/javascript">
$(document).ready(function(){
	ajustaWidHei = function(){
		$('body').css('overflow', 'hidden');
		$('#section-content').css('overflow-x', 'hidden');
		
		if($(window).width() < 800){
		}else{
			var menuHeight = $('#menu-nav-left').outerHeight() + 'px';
			$('.section-background img').css('height', menuHeight);
		}
	};

	// ajustes iniciais
	ajustaWidHei();

	// ajusta dimensoes em monitoramento
	setInterval(function(){
		ajustaWidHei();
	}, 300);
});
</script>

<script type="text/javascript">
$(function(){
	// ajusta scroll ao carregar
	$('body').scrollTop(0);

	// controle do grid
	$('.briefing-item .cmn-toggle').click(function(){
		$(this).parents('.briefing-item').find('.briefing-grid').slideToggle();
	});

	// complementar briefings
	$('#btn-confirmar-ambientes, #btn-confirmar-ambientes-mobile').on('click', function(){
		window.location = "<?php echo $this->url('clientes', array('action' => 'confirmar')); ?>"
	});
	
	
	$('#concluirCozinha').click(function(){
		$('#modalCozinhaForm').submit();
	});

	$('#concluirAreaServico').click(function(){
		$('#modalAreaServicoForm').submit();
	});

	$('#concluirDormitorioCasal').click(function(){
		$('#modalDormitorioCasalForm').submit();
	});

	$('#concluirDormitorioSolteiro').click(function(){
		$('#modalDormitorioSolteiroForm').submit();
	});

	$('#concluirCloset').click(function(){
		$('#modalClosetForm').submit();
	});

	//$('#concluirDormitorioInfantil').click(function(){
	//	$('#modalDormitorioInfantilForm').submit();
	//});

	$('#concluirBanheiro').click(function(){
		$('#modalBanheiroForm').submit();
	});

	$('#concluirHomeTheater').click(function(){
		$('#modalHomeTheaterForm').submit();
	});

	$('#concluirHomeOffice').click(function(){
		$('#modalHomeOfficeForm').submit();
	});
/*
	$('.block-subitem-cond').change(function(){
		var formGroup = $(this).parents('.form-group');
		
		if($(this).val() == '1'){
			$(formGroup).find('.block-subitem').fadeIn();
			$(formGroup).find('.block-subitem').find('input,select').attr('required', 'required');
		}else{
			$(formGroup).find('.block-subitem').fadeOut();
			$(formGroup).find('.block-subitem').find('input,select').removeAttr('required');
		}
	});
*/
	$('.block-subitem-cond').click(function(){
		var formGroup = $(this).parents('.form-group');
		
		if($(this).val() == '1'){
			$(formGroup).find('.block-subitem').fadeIn();
			$(formGroup).find('.block-subitem').find('.ss-item-required').find('input,select').attr('required', 'required');
		}else{
			$(formGroup).find('.block-subitem').slideUp();
			$(formGroup).find('.block-subitem').find('input,select').removeAttr('required');
		}
	});

	criarBriefing = function(tp){
		if(tp == 'cozinha'){
			// abre a modal de briefing da cozinha
			$('#modalCozinhaForm').find('input').each(function(){
				if($(this).attr('type') == 'radio'){
					if($(this).val() == 0){
						$(this).prop('checked', true);
						$(this).click();
					}
				} else if($(this).attr('name') != 'acao' && $(this).attr('name') != 'preferenciacores[]'){
					$(this).val('');
				}
				else if($(this).attr('name') == 'preferenciacores[]'){
					$(this).prop('checked', false);
				}
			});
			$('#modalCozinhaForm').find('select').each(function(){
				$(this).val(0);
			});

			$('input[name="id"]').val('');
			$('#modalCozinhaForm').find('.box-imagem .col-xs-6').html('');
			$('#modalCozinha').modal('show');
			
		} else if(tp == 'areaServico'){
			// abre a modal de briefing de área de serviço
			$('#modalAreaServicoForm').find('input').each(function(){
				if($(this).attr('type') == 'radio'){
					if($(this).val() == 0){
						$(this).prop('checked', true);
						$(this).click();
					}
				} else if($(this).attr('name') != 'acao' && $(this).attr('name') != 'bas_preferenciacores[]'){
					$(this).val('');
				}
				else if($(this).attr('name') == 'bas_preferenciacores[]'){
					$(this).prop('checked', false);
				}
			});
			$('#modalAreaServicoForm').find('select').each(function(){
				$(this).val(0);
			});
			$('input[name="id"]').val('');
			$('#modalAreaServicoForm').find('.box-imagem .col-xs-6').html('');
			$('#modalAreaServico').modal('show');
		} else if(tp == 'dormitoriocasal'){
			// abre a modal de briefing de dormitório de casal
			$('#modalDormitorioCasalForm').find('input').each(function(){
				if($(this).attr('type') == 'radio'){
					if($(this).val() == 0){
						$(this).prop('checked', true);
						$(this).click();
					}
				} else if($(this).attr('name') != 'acao' && $(this).attr('name') != 'bdc_preferenciacores[]'){
					$(this).val('');
				}
				else if($(this).attr('name') == 'bdc_preferenciacores[]'){
					$(this).prop('checked', false);
				}
			});
			$('#modalDormitorioCasalForm').find('select').each(function(){
				$(this).val(0);
			});
			$('input[name="id"]').val('');
			$('#modalDormitorioCasalForm').find('.box-imagem .col-xs-6').html('');
			$('#modalDormitorioCasal').modal('show');
		} else if(tp == 'dormitoriosolteiro'){
			// abre a modal de briefing de dormitório de solteiro
			$('#modalDormitorioSolteiroForm').find('input').each(function(){
				if($(this).attr('type') == 'radio'){
					if($(this).val() == 0){
						$(this).prop('checked', true);
						$(this).click();
					}
				} else if($(this).attr('name') != 'acao' && $(this).attr('name') != 'bds_preferenciacores[]'){
					$(this).val('');
				}
				else if($(this).attr('name') == 'bds_preferenciacores[]'){
					$(this).prop('checked', false);
				}
			});
			$('#modalDormitorioSolteiroForm').find('select').each(function(){
				$(this).val(0);
			});
			$('input[name="id"]').val('');
			$('#modalDormitorioSolteiroForm').find('.box-imagem .col-xs-6').html('');
			$('#modalDormitorioSolteiro').modal('show');
		} /*else if(tp == 'dormitorioinfantil'){
			var callback = function(){
				// abre a modal de briefing de dormitório infantil
				$('#modalDormitorioInfantilForm').find('input').each(function(){
					if($(this).attr('name') != 'acao' && $(this).attr('name') != 'bdi_preferenciacores[]'){
						$(this).val('');
					}
					else if($(this).attr('name') != 'bdi_preferenciacores[]'){
						$(this).prop('checked', false);
					}
				});
				$('#modalDormitorioInfantilForm').find('select').each(function(){
					$(this).val(0);
				});
				$('input[name="id"]').val('');
				$('#modalDormitorioInfantilForm').find('.box-imagem .col-xs-6').html('');
				$('#modalDormitorioInfantil').modal('show');
			};

			showModalCadastro(callback);
		}*/ else if(tp == 'closet'){
			// abre a modal de briefing de closet
			$('#modalClosetForm').find('input').each(function(){
				if($(this).attr('type') == 'radio'){
					if($(this).val() == 0){
						$(this).prop('checked', true);
						$(this).click();
					}
				} else if($(this).attr('name') != 'acao' && $(this).attr('name') != 'bcl_preferenciacores[]'){
					$(this).val('');
				}
				else if($(this).attr('name') == 'bcl_preferenciacores[]'){
					$(this).prop('checked', false);
				}
			});
			$('#modalClosetForm').find('select').each(function(){
				$(this).val(0);
			});
			$('input[name="id"]').val('');
			$('#modalClosetForm').find('.box-imagem .col-xs-6').html('');
			$('#modalCloset').modal('show');
		} else if(tp == 'banheiro'){
			// abre a modal de briefing de banheiro
			$('#modalBanheiroForm').find('input').each(function(){
				if($(this).attr('type') == 'radio'){
					if($(this).val() == 0){
						$(this).prop('checked', true);
						$(this).click();
					}
				} else if($(this).attr('name') != 'acao' && $(this).attr('name') != 'ban_preferenciacores[]'){
					$(this).val('');
				}
				else if($(this).attr('name') == 'ban_preferenciacores[]'){
					$(this).prop('checked', false);
				}
			});
			$('#modalBanheiroForm').find('select').each(function(){
				$(this).val(0);
			});
			$('input[name="id"]').val('');
			$('#modalBanheiroForm').find('.box-imagem .col-xs-6').html('');
			$('#modalBanheiro').modal('show');
		} else if(tp == 'hometheater'){
			// abre a modal de briefing de home theater
			$('#modalHomeTheaterForm').find('input').each(function(){
				if($(this).attr('type') == 'radio'){
					if($(this).val() == 0){
						$(this).prop('checked', true);
						$(this).click();
					}
				} else if($(this).attr('name') != 'acao' && $(this).attr('name') != 'bht_preferenciacores[]'){
					$(this).val('');
				}
				else if($(this).attr('name') == 'bht_preferenciacores[]'){
					$(this).prop('checked', false);
				}
			});
			$('#modalHomeTheaterForm').find('select').each(function(){
				$(this).val(0);
			});
			$('input[name="id"]').val('');
			$('#modalHomeTheaterForm').find('.box-imagem .col-xs-6').html('');
			$('#modalHomeTheater').modal('show');
		} else if(tp == 'homeoffice'){
			// abre a modal de briefing de home office
			$('#modalHomeOfficeForm').find('input').each(function(){
				if($(this).attr('type') == 'radio'){
					if($(this).val() == 0){
						$(this).prop('checked', true);
						$(this).click();
					}
				} else if($(this).attr('name') != 'acao' && $(this).attr('name') != 'bho_preferenciacores[]'){
					$(this).val('');
				}
				else if($(this).attr('name') == 'bho_preferenciacores[]'){
					$(this).prop('checked', false);
				}
			});
			$('#modalHomeOfficeForm').find('select').each(function(){
				$(this).val(0);
			});
			$('input[name="id"]').val('');
			$('#modalHomeOfficeForm').find('.box-imagem .col-xs-6').html('');
			$('#modalHomeOffice').modal('show');
		}

		return false;
	};
	
	alterarBriefing = function(tp, id){
		$.post(
			'<?=$this->url('clientes', array('action' => 'carregaBriefing'));?>',
			{tipo: tp, id: id},
			function(resp){
				if(tp == 'cozinha'){
					// carrega a modal de cozinha
					$('#modalCozinhaForm').find('input,select').each(function(){
						var name = $(this).attr('name');
						if(name != 'acao' && name != 'preferenciacores[]' && name != 'imagem'){
							if($(this).attr('type') == 'radio'){
								if($(this).val() == resp.data[name]){
									$(this).click();
								}
							}else{
								$(this).val(resp.data[name]);
								$(this).change();
							}
						}
						// preferencia de cores
						if(name == 'preferenciacores[]'){
							if($.inArray($(this).val(), resp.data['preferenciacores']) > -1){
								$(this).prop('checked', true);
							}
						}
					});

					if(resp.data['idbriefing'] != null){
						$('input[name="id"]').val(resp.data['idbriefing']);
					}
					
					if(resp.data['imagem'] != null){
						var pathImg = '<img src="<?=$this->basePath('upload/briefing/');?>'+resp.data['imagem']+'" class="img-responsive" style="width: 100%; margin-top: 10px;"/>'
						$('#modalCozinhaForm').find('.box-imagem .col-xs-10').html(pathImg);
					}
					
					$('#modalCozinha').modal('show');
				} else if(tp == 'areaservico'){
					// carrega a modal de área de serviço
					$('#modalAreaServicoForm').find('input,select').each(function(){
						var name = $(this).attr('name');
						if(name != 'acao' && name != 'bas_preferenciacores[]' && name != 'bas_imagem'){
							if($(this).attr('type') == 'radio'){
								if($(this).val() == resp.data[name]){
									$(this).click();
								}
							}else{
								$(this).val(resp.data[name]);
								$(this).change();
							}
						}
						// preferencia de cores
						if(name == 'bas_preferenciacores[]'){
							if($.inArray($(this).val(), resp.data['bas_preferenciacores']) > -1){
								$(this).prop('checked', true);
							}
						}
					});

					if(resp.data['idbriefing'] != null){
						$('input[name="id"]').val(resp.data['idbriefing']);
					}
					
					if(resp.data['bas_imagem'] != null){
						var pathImg = '<img src="<?=$this->basePath('upload/briefing/');?>'+resp.data['bas_imagem']+'" class="img-responsive" style="width: 100%; margin-top: 10px;"/>'
						$('#modalAreaServicoForm').find('.box-imagem .col-xs-10').html(pathImg);
					}
					
					$('#modalAreaServico').modal('show');
				} else if(tp == 'dormitoriocasal'){
					// carrega a modal de dormitório casal
					$('#modalDormitorioCasalForm').find('input,select').each(function(){
						var name = $(this).attr('name');
						if(name != 'acao' && name != 'bdc_preferenciacores[]' && name != 'bdc_imagem'){
							if($(this).attr('type') == 'radio'){
								if($(this).val() == resp.data[name]){
									$(this).click();
								}
							}else{
								$(this).val(resp.data[name]);
								$(this).change();
							}
						}
						// preferencia de cores
						if(name == 'bdc_preferenciacores[]'){
							if($.inArray($(this).val(), resp.data['bdc_preferenciacores']) > -1){
								$(this).prop('checked', true);
							}
						}
					});

					if(resp.data['idbriefing'] != null){
						$('input[name="id"]').val(resp.data['idbriefing']);
					}
					
					if(resp.data['bdc_imagem'] != null){
						var pathImg = '<img src="<?=$this->basePath('upload/briefing/');?>'+resp.data['bdc_imagem']+'" class="img-responsive" style="width: 100%; margin-top: 10px;"/>'
						$('#modalDormitorioCasalForm').find('.box-imagem .col-xs-10').html(pathImg);
					}
					
					$('#modalDormitorioCasal').modal('show');
				} else if(tp == 'dormitoriosolteiro'){
					// carrega a modal de dormitório solteiro
					$('#modalDormitorioSolteiroForm').find('input,select').each(function(){
						var name = $(this).attr('name');
						if(name != 'acao' && name != 'bds_preferenciacores[]' && name != 'bds_imagem'){
							if($(this).attr('type') == 'radio'){
								if($(this).val() == resp.data[name]){
									$(this).click();
								}
							}else{
								$(this).val(resp.data[name]);
								$(this).change();
							}
						}
						// preferencia de cores
						if(name == 'bds_preferenciacores[]'){
							if($.inArray($(this).val(), resp.data['bds_preferenciacores']) > -1){
								$(this).prop('checked', true);
							}
						}
					});

					if(resp.data['idbriefing'] != null){
						$('input[name="id"]').val(resp.data['idbriefing']);
					}
					
					if(resp.data['bds_imagem'] != null){
						var pathImg = '<img src="<?=$this->basePath('upload/briefing/');?>'+resp.data['bds_imagem']+'" class="img-responsive" style="width: 100%; margin-top: 10px;"/>'
						$('#modalDormitorioSolteiroForm').find('.box-imagem .col-xs-10').html(pathImg);
					}
					
					$('#modalDormitorioSolteiro').modal('show');
				} else if(tp == 'dormitorioinfantil'){
					// carrega a modal de dormitório infantil
					$('#modalDormitorioInfantilForm').find('input,select').each(function(){
						var name = $(this).attr('name');
						if(name != 'acao' && name != 'bdi_preferenciacores[]' && name != 'bdi_imagem'){
							if($(this).attr('type') == 'radio'){
								if($(this).val() == resp.data[name]){
									$(this).click();
								}
							}else{
								$(this).val(resp.data[name]);
								$(this).change();
							}
						}
						// preferencia de cores
						if(name == 'bdi_preferenciacores[]'){
							if($.inArray($(this).val(), resp.data['bdi_preferenciacores']) > -1){
								$(this).prop('checked', true);
							}
						}
					});

					if(resp.data['idbriefing'] != null){
						$('input[name="id"]').val(resp.data['idbriefing']);
					}
					
					if(resp.data['bdi_imagem'] != null){
						var pathImg = '<img src="<?=$this->basePath('upload/briefing/');?>'+resp.data['bdi_imagem']+'" class="img-responsive" style="width: 100%; margin-top: 10px;"/>'
						$('#modalDormitorioInfantilForm').find('.box-imagem .col-xs-10').html(pathImg);
					}
					
					$('#modalDormitorioInfantil').modal('show');
				} else if(tp == 'closet'){
					// carrega a modal de closet
					$('#modalClosetForm').find('input,select').each(function(){
						var name = $(this).attr('name');
						if(name != 'acao' && name != 'bcl_preferenciacores[]' && name != 'bcl_imagem'){
							if($(this).attr('type') == 'radio'){
								if($(this).val() == resp.data[name]){
									$(this).click();
								}
							}else{
								$(this).val(resp.data[name]);
								$(this).change();
							}
						}
						// preferencia de cores
						if(name == 'bcl_preferenciacores[]'){
							if($.inArray($(this).val(), resp.data['bcl_preferenciacores']) > -1){
								$(this).prop('checked', true);
							}
						}
					});

					if(resp.data['idbriefing'] != null){
						$('input[name="id"]').val(resp.data['idbriefing']);
					}
					
					if(resp.data['bcl_imagem'] != null){
						var pathImg = '<img src="<?=$this->basePath('upload/briefing/');?>'+resp.data['bcl_imagem']+'" class="img-responsive" style="width: 100%; margin-top: 10px;"/>'
						$('#modalClosetForm').find('.box-imagem .col-xs-10').html(pathImg);
					}
					
					$('#modalCloset').modal('show');
				} else if(tp == 'banheiro'){
					// carrega a modal de banheiro
					$('#modalBanheiroForm').find('input,select').each(function(){
						var name = $(this).attr('name');
						if(name != 'acao' && name != 'ban_preferenciacores[]' && name != 'ban_imagem'){
							if($(this).attr('type') == 'radio'){
								if($(this).val() == resp.data[name]){
									$(this).click();
								}
							}else{
								$(this).val(resp.data[name]);
								$(this).change();
							}
						}
						// preferencia de cores
						if(name == 'ban_preferenciacores[]'){
							if($.inArray($(this).val(), resp.data['ban_preferenciacores']) > -1){
								$(this).prop('checked', true);
							}
						}
					});

					if(resp.data['idbriefing'] != null){
						$('input[name="id"]').val(resp.data['idbriefing']);
					}
					
					if(resp.data['ban_imagem'] != null){
						var pathImg = '<img src="<?=$this->basePath('upload/briefing/');?>'+resp.data['ban_imagem']+'" class="img-responsive" style="width: 100%; margin-top: 10px;"/>'
						$('#modalBanheiroForm').find('.box-imagem .col-xs-10').html(pathImg);
					}
					
					$('#modalBanheiro').modal('show');
				} else if(tp == 'hometheater'){
					// carrega a modal de home theater
					$('#modalHomeTheaterForm').find('input,select').each(function(){
						var name = $(this).attr('name');
						if(name != 'acao' && name != 'bht_preferenciacores[]' && name != 'bht_imagem'){
							if($(this).attr('type') == 'radio'){
								if($(this).val() == resp.data[name]){
									$(this).click();
								}
							}else{
								$(this).val(resp.data[name]);
								$(this).change();
							}
						}
						// preferencia de cores
						if(name == 'bht_preferenciacores[]'){
							if($.inArray($(this).val(), resp.data['bht_preferenciacores']) > -1){
								$(this).prop('checked', true);
							}
						}
					});

					if(resp.data['idbriefing'] != null){
						$('input[name="id"]').val(resp.data['idbriefing']);
					}
					
					if(resp.data['bht_imagem'] != null){
						var pathImg = '<img src="<?=$this->basePath('upload/briefing/');?>'+resp.data['bht_imagem']+'" class="img-responsive" style="width: 100%; margin-top: 10px;"/>'
						$('#modalHomeTheaterForm').find('.box-imagem .col-xs-10').html(pathImg);
					}
					
					$('#modalHomeTheater').modal('show');
				} else if(tp == 'homeoffice'){
					// carrega a modal de home office
					$('#modalHomeOfficeForm').find('input,select').each(function(){
						var name = $(this).attr('name');
						if(name != 'acao' && name != 'bho_preferenciacores[]' && name != 'bho_imagem'){
							if($(this).attr('type') == 'radio'){
								if($(this).val() == resp.data[name]){
									$(this).click();
								}
							}else{
								$(this).val(resp.data[name]);
								$(this).change();
							}
						}
						// preferencia de cores
						if(name == 'bho_preferenciacores[]'){
							if($.inArray($(this).val(), resp.data['bho_preferenciacores']) > -1){
								$(this).prop('checked', true);
							}
						}
					});

					if(resp.data['idbriefing'] != null){
						$('input[name="id"]').val(resp.data['idbriefing']);
					}
					
					if(resp.data['bho_imagem'] != null){
						var pathImg = '<img src="<?=$this->basePath('upload/briefing/');?>'+resp.data['bho_imagem']+'" class="img-responsive" style="width: 100%; margin-top: 10px;"/>'
						$('#modalHomeOfficeForm').find('.box-imagem .col-xs-10').html(pathImg);
					}
					
					$('#modalHomeOffice').modal('show');
				}
			},
			'json'
		);

		return false;
	};

	removerBriefing = function(tp, id){
		if(confirm("Deseja remover o briefing?")){
			$.post(
				'<?=$this->url('clientes', array('action' => 'removeBriefing'));?>',
				{tipo: tp, id: id},
				function(resp){
					window.location = "<?=$this->url('clientes');?>/index/" + resp.data;
				},
				'json'
			);
		}

		return false;
	};

	<?php echo (count($this->listaCozinha))? "$('#cmn-toggle-cozinha').parents('.briefing-item').find('.briefing-grid').slideToggle();": ''; ?>
	<?php echo (count($this->listaAreaServico))? "$('#cmn-toggle-areaServico').parents('.briefing-item').find('.briefing-grid').slideToggle();": ''; ?>
	<?php echo (count($this->listaDormitorioCasal))? "$('#cmn-toggle-dormitoriocasal').parents('.briefing-item').find('.briefing-grid').slideToggle();": ''; ?>
	<?php echo (count($this->listaDormitorioSolteiro))? "$('#cmn-toggle-dormitoriosolteiro').parents('.briefing-item').find('.briefing-grid').slideToggle();": ''; ?>
	<?php echo (count($this->listaCloset))? "$('#cmn-toggle-closet').parents('.briefing-item').find('.briefing-grid').slideToggle();": ''; ?>
	<?php echo (count($this->listaBanheiro))? "$('#cmn-toggle-banheiro').parents('.briefing-item').find('.briefing-grid').slideToggle();": ''; ?>
	<?php echo (count($this->listaHomeTheater))? "$('#cmn-toggle-hometheater').parents('.briefing-item').find('.briefing-grid').slideToggle();": ''; ?>
	<?php echo (count($this->listaHomeOffice))? "$('#cmn-toggle-homeoffice').parents('.briefing-item').find('.briefing-grid').slideToggle();": ''; ?>
	
});
</script>