<div id="brief-boas-vindas" class="brief-telas col-xs-12">
    <h2>Conte mais sobre o que você procura.</h2>
    <p>
        Precisamos conhecer as suas <b>preferências e necessidades</b> para
        que os nossos especialistas em projeto possam aproveitar o que temos 
        de melhor para deixar o seu ambiente <b>adequado a sua necessidade.</b> :)
    </p>
    <p>
        Daqui, começaremos a levantar informações sobre o projeto que você deseja realizar.
        É muito importante que você nos repasse suas necessidades e desejos com atenção, para que possamos
        transformá-los no seu sonho, dentro da sua casa.
    </p>

    <div class="col-xs-12">
        <a href="javascript:void(0)" onclick="proximaTela('#brief-tela-inicio');">
            VAMOS LÁ!
        </a>
    </div>
</div>

<div id="brief-tela-inicio" class="brief-telas col-xs-12">
    <h2>Quais ambientes você gostaria de planejar?</h2>
    
    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Cozinha</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('cozinha')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button <?php echo count($this->listaCozinha)? 'onclick="proximaTela(\'#brief-grid-cozinha\');"': ''; ?> class="inicio-item-total <?php echo count($this->listaCozinha)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaCozinha); ?>
            </button>
        </div>
    </div>

    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Área de serviço</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('areaServico')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button <?php echo count($this->listaAreaServico)? 'onclick="proximaTela(\'#brief-grid-areaServico\');"': ''; ?> class="inicio-item-total <?php echo count($this->listaAreaServico)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaAreaServico); ?>
            </button>
        </div>
    </div>

    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Dormitório Casal</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('dormitoriocasal')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button <?php echo count($this->listaDormitorioCasal)? 'onclick="proximaTela(\'#brief-grid-dormitorioCasal\');"': ''; ?> class="inicio-item-total <?php echo count($this->listaDormitorioCasal)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaDormitorioCasal); ?>
            </button>
        </div>
    </div>

    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Dormitório Solteiro</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('dormitoriosolteiro')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button <?php echo count($this->listaDormitorioSolteiro)? 'onclick="proximaTela(\'#brief-grid-dormitorioSolteiro\');"': ''; ?> class="inicio-item-total <?php echo count($this->listaDormitorioSolteiro)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaDormitorioSolteiro); ?>
            </button>
        </div>
    </div>

    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Closet</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('closet')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button <?php echo count($this->listaCloset)? 'onclick="proximaTela(\'#brief-grid-closet\');"': ''; ?> class="inicio-item-total <?php echo count($this->listaCloset)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaCloset); ?>
            </button>
        </div>
    </div>

    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Banheiro</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('banheiro')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button <?php echo count($this->listaBanheiro)? 'onclick="proximaTela(\'#brief-grid-banheiro\');"': ''; ?> class="inicio-item-total <?php echo count($this->listaBanheiro)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaBanheiro); ?>
            </button>
        </div>
    </div>

    <!--
    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Banheiro Suíte</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('banheirosuite')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button class="inicio-item-total <?php echo count($this->listaCozinha)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaCozinha); ?>
            </button>
        </div>
    </div>
    -->

    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Home Theater</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('hometheater')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button <?php echo count($this->listaHomeTheater)? 'onclick="proximaTela(\'#brief-grid-homeTheater\');"': ''; ?> class="inicio-item-total <?php echo count($this->listaHomeTheater)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaHomeTheater); ?>
            </button>
        </div>
    </div>

    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Home Office</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('homeoffice')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button <?php echo count($this->listaHomeOffice)? 'onclick="proximaTela(\'#brief-grid-homeOffice\');"': ''; ?> class="inicio-item-total <?php echo count($this->listaHomeOffice)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaHomeOffice); ?>
            </button>
        </div>
    </div>

    <!--
    <div class="tela-inicio-item">
        <div class="pull-left">
            <p>Outros</p>
        </div>

        <div class="pull-right">
            <button class="inicio-item-novo" onclick="return criarBriefing('homeoffice')">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
            <button class="inicio-item-total <?php echo count($this->listaCozinha)? 'inicio-item-total-red': ''; ?>">
                <?php echo count($this->listaCozinha); ?>
            </button>
        </div>
    </div>
    -->

    <div class="col-xs-12">
        <a href="javascript:void(0)" id="btn-confirmar-ambientes-mobile">
            CONFIRMAR AMBIENTES
        </a>
    </div>
</div>

<div id="brief-grid-cozinha" class="brief-telas brief-telas-grid col-xs-12">
    <h2>Você já possui <?php echo count($this->listaCozinha); ?> briefings de Cozinha em andamento.</h2>
    <p>
        Deseja continuar de onde parou?
    </p>

    <?php foreach($this->listaCozinha as $item): ?>
        <div class="brief-telas-grid-item col-xs-12">
            <?php echo $item->descricao ?>
        </div>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="col-xs-6"></div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-iniciar-novo" onclick="criarBriefing('cozinha');">INICIAR NOVO</button>			
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-voltar-mobile" onclick="proximaTela('#brief-tela-inicio');">VOLTAR</button>
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-avancar">CONCLUIR</button>			
        </div>
    </div>
</div>

<div id="brief-grid-areaServico" class="brief-telas brief-telas-grid col-xs-12">
    <h2>Você já possui <?php echo count($this->listaAreaServico); ?> briefings de Área de Serviço em andamento.</h2>
    <p>
        Deseja continuar de onde parou?
    </p>

    <?php foreach($this->listaAreaServico as $item): ?>
        <div class="brief-telas-grid-item col-xs-12">
            <?php echo $item->bas_descricao ?>
        </div>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="col-xs-6"></div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-iniciar-novo" onclick="criarBriefing('areaServico');">INICIAR NOVO</button>			
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-voltar-mobile" onclick="proximaTela('#brief-tela-inicio');">VOLTAR</button>
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-avancar">CONCLUIR</button>			
        </div>
    </div>
</div>

<div id="brief-grid-dormitorioCasal" class="brief-telas brief-telas-grid col-xs-12">
    <h2>Você já possui <?php echo count($this->listaDormitorioCasal); ?> briefings de Dormitório Casal em andamento.</h2>
    <p>
        Deseja continuar de onde parou?
    </p>

    <?php foreach($this->listaDormitorioCasal as $item): ?>
        <div class="brief-telas-grid-item col-xs-12">
            <?php echo $item->bdc_descricao ?>
        </div>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="col-xs-6"></div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-iniciar-novo" onclick="criarBriefing('dormitoriocasal');">INICIAR NOVO</button>			
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-voltar-mobile" onclick="proximaTela('#brief-tela-inicio');">VOLTAR</button>
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-avancar">CONCLUIR</button>			
        </div>
    </div>
</div>

<div id="brief-grid-dormitorioSolteiro" class="brief-telas brief-telas-grid col-xs-12">
    <h2>Você já possui <?php echo count($this->listaDormitorioSolteiro); ?> briefings de Dormitório Solteiro em andamento.</h2>
    <p>
        Deseja continuar de onde parou?
    </p>

    <?php foreach($this->listaDormitorioSolteiro as $item): ?>
        <div class="brief-telas-grid-item col-xs-12">
            <?php echo $item->bds_descricao ?>
        </div>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="col-xs-6"></div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-iniciar-novo" onclick="criarBriefing('dormitoriosolteiro');">INICIAR NOVO</button>			
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-voltar-mobile" onclick="proximaTela('#brief-tela-inicio');">VOLTAR</button>
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-avancar">CONCLUIR</button>			
        </div>
    </div>
</div>

<div id="brief-grid-closet" class="brief-telas brief-telas-grid col-xs-12">
    <h2>Você já possui <?php echo count($this->listaCloset); ?> briefings de Closet em andamento.</h2>
    <p>
        Deseja continuar de onde parou?
    </p>

    <?php foreach($this->listaCloset as $item): ?>
        <div class="brief-telas-grid-item col-xs-12">
            <?php echo $item->bcl_descricao ?>
        </div>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="col-xs-6"></div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-iniciar-novo" onclick="criarBriefing('closet');">INICIAR NOVO</button>			
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-voltar-mobile" onclick="proximaTela('#brief-tela-inicio');">VOLTAR</button>
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-avancar">CONCLUIR</button>			
        </div>
    </div>
</div>

<div id="brief-grid-banheiro" class="brief-telas brief-telas-grid col-xs-12">
    <h2>Você já possui <?php echo count($this->listaBanheiro); ?> briefings de Banheiro em andamento.</h2>
    <p>
        Deseja continuar de onde parou?
    </p>

    <?php foreach($this->listaBanheiro as $item): ?>
        <div class="brief-telas-grid-item col-xs-12">
            <?php echo $item->ban_descricao ?>
        </div>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="col-xs-6"></div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-iniciar-novo" onclick="criarBriefing('banheiro');">INICIAR NOVO</button>			
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-voltar-mobile" onclick="proximaTela('#brief-tela-inicio');">VOLTAR</button>
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-avancar">CONCLUIR</button>			
        </div>
    </div>
</div>

<div id="brief-grid-homeTheater" class="brief-telas brief-telas-grid col-xs-12">
    <h2>Você já possui <?php echo count($this->listaHomeTheater); ?> briefings de Home Theater em andamento.</h2>
    <p>
        Deseja continuar de onde parou?
    </p>

    <?php foreach($this->listaHomeTheater as $item): ?>
        <div class="brief-telas-grid-item col-xs-12">
            <?php echo $item->bht_descricao ?>
        </div>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="col-xs-6"></div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-iniciar-novo" onclick="criarBriefing('hometheater');">INICIAR NOVO</button>			
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-voltar-mobile" onclick="proximaTela('#brief-tela-inicio');">VOLTAR</button>
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-avancar">CONCLUIR</button>			
        </div>
    </div>
</div>

<div id="brief-grid-homeOffice" class="brief-telas brief-telas-grid col-xs-12">
    <h2>Você já possui <?php echo count($this->listaHomeOffice); ?> briefings de Home Office em andamento.</h2>
    <p>
        Deseja continuar de onde parou?
    </p>

    <?php foreach($this->listaHomeOffice as $item): ?>
        <div class="brief-telas-grid-item col-xs-12">
            <?php echo $item->bho_descricao ?>
        </div>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="col-xs-6"></div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-iniciar-novo" onclick="criarBriefing('homeoffice');">INICIAR NOVO</button>			
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-voltar-mobile" onclick="proximaTela('#brief-tela-inicio');">VOLTAR</button>
        </div>
        <div class="col-xs-6">
            <button type="button" class="btn btn-block btn-avancar">CONCLUIR</button>			
        </div>
    </div>
</div>

<script type="text/javascript">
$(function(){
    // show tela inicial
    $('#brief-boas-vindas').fadeIn();
    
    proximaTela = function(selector){
        $('.brief-telas').hide();
        $(selector).fadeIn();
    }
});
</script>