<?= $this->doctype() ?>

<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('TutteMob')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= 
        	$this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
        ?>
        
        <link rel="shortcut icon" href="<?= $this->basePath('img/layout/logo2-128x129-78.png') ?>" type="image/x-icon">
        
		<!-- Bootstrap core CSS -->
	    <link href="<?= $this->basePath('lib/bootstrap/dist/css/bootstrap.min.css') ?>" rel="stylesheet">
	
	    <!-- Custom styles -->
	    <link href="<?= $this->basePath('css/style.css') ?>" rel="stylesheet">
	    <link rel="stylesheet" href="<?= $this->basePath('lib/duplob/css/style-custom.css') ?>">
	
	    <!-- jQuery -->
	    <script src="<?= $this->basePath('lib/jquery/dist/jquery.min.js') ?>"></script>
	    <script src="<?= $this->basePath('lib/mask/jquery.mask.min.js') ?>"></script>
    </head>
    <body>
    	<nav class="navbar navbar-default navbar-fixed-top">
	      <div class="container-fluid">
	        <div class="navbar-header">
	          <a class="navbar-brand" href="<?= $this->url('home'); ?>">
	            <img alt="TutteMob" src="<?= $this->basePath('img/layout/logo-menu.png') ?>" class="img-responsive" />
	          </a>
	        </div>
	
	        <ul class="nav navbar-nav navbar-right">
	        <?php if(!$this->usuario): ?>  
	          <li>
	            <a href="#section-1" title="Quem somos">
	              <img src="<?= $this->basePath('img/layout/quem-somos.png') ?>" class="img-responsive" />
	            </a>
	          </li>
	          <li>
	            <a href="<?= $this->url('home', array('action' => 'ambientes')); ?>" title="Ambientes">
	              <img src="<?= $this->basePath('img/layout/ambientes.png') ?>" class="img-responsive" />
	            </a>
	          </li>
	          <li>
	            <a href="#section-3" title="Franquias Físicas">
	              <img src="<?= $this->basePath('img/layout/franquias-fisicas.png') ?>" class="img-responsive" />
	            </a>
	          </li>
	          <li>
	            <a href="#section-4" title="Experiências de Clientes">
	              <img src="<?= $this->basePath('img/layout/experiencia-clientes.png') ?>" class="img-responsive" />
	            </a>
	          </li>
	          <li>
	            <a href="#section-5" title="Contato">
	              <img src="<?= $this->basePath('img/layout/contato.png') ?>" class="img-responsive" />
	            </a>
	          </li>
	          <li>
	            <a href="<?= $this->url('login'); ?>" title="Login">
	              <img src="<?= $this->basePath('img/layout/login.png') ?>" class="img-responsive" />
	            </a>
	          </li>
	          <li>
	            <a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>" title="Iniciar minha experiência TutteMob">
	              <img src="<?= $this->basePath('img/layout/iniciar-experiencia.png') ?>" class="img-responsive" />
	            </a>
	          </li>
	        <?php else: ?>  
	          <li class="dropdown">
	            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
	            	<img src="<?= $this->basePath('img/layout/menu-login.png') ?>" class="img-responsive" />
	            </a>
	            <ul class="dropdown-menu">
	               
	              <li><a href="<?= $this->url('clientes'); ?>">Orçamentos</a></li>
	              
	              <li role="separator" class="divider"></li>
	              <li><a href="#">Quem Somos?</a></li>
	              <li role="separator" class="divider"></li>
	              <li><a href="<?= $this->url('home', array('action' => 'ambientes')); ?>">Ambientes</a></li>
	              <li role="separator" class="divider"></li>
	              <li><a href="#">Franquias Físicas</a></li>
	              <!-- <li><a href="javascript:void(0)">Experiência de clientes</a></li> -->
	              <li role="separator" class="divider"></li>
	              <li><a href="#">Contato</a></li>
	              <li role="separator" class="divider"></li>
	              <li><a href="<?= $this->url('login', array('action' => 'logout')); ?>">Sair</a></li>
	            </ul>
	          </li>
	        <?php endif;?>
	        </ul>
	      </div>
	    </nav>
	
	    <div id="section-0" class="section col-lg-12"></div>
	
		<?= $this->layout()->content; ?>    
	
	
	<?php if($_SERVER['REQUEST_URI'] != '/tuttemob/public/cadastrar' &&
			$_SERVER['REQUEST_URI'] != '/tuttemob/public/login/'): ?>	
		  
	
	    <div id="section-footer" class="section col-lg-12">
	        <a class="navbar-brand" href="<?= $this->url('home'); ?>">
	            <img alt="TutteMob" src="<?= $this->basePath('img/layout/logo-menu.png') ?>" class="img-responsive" />
	        </a>
	
	        <div id="footer-links" class="pull-right">
	            <ul class="nav navbar-nav navbar-right">
	              <li>
	                <a href="#section-1" title="Facebook">
	                  <img src="<?= $this->basePath('img/layout/facebook.png') ?>" class="img-responsive" />
	                </a>
	              </li>
	              <li>
	                <a href="#section-1" title="Twitter">
	                  <img src="<?= $this->basePath('img/layout/twitter.png') ?>" class="img-responsive" />
	                </a>
	              </li>
	              <li>
	                <a href="#section-1" title="Youtube">
	                  <img src="<?= $this->basePath('img/layout/youtube.png') ?>" class="img-responsive" />
	                </a>
	              </li>
	              <li>
	                <a href="#section-1" title="Instagram">
	                  <img src="<?= $this->basePath('img/layout/instagram.png') ?>" class="img-responsive" />
	                </a>
	              </li>
	              
	              <!-- 
	              <h2>
	              	URL: <?php
	              		$dominio= $_SERVER['HTTP_HOST'];
 						$url = "http://" . $dominio. $_SERVER['REQUEST_URI'];
 						$url2 = " " . $dominio;
 						$url3 = $_SERVER['REQUEST_URI'];
						echo $url3;?>
				  </h2>
				  -->
	              
	              <!-- 
	              <li>
	                <a href="#section-1" title="Email">
	                  <img src="<?= $this->basePath('img/layout/email.png') ?>" class="img-responsive" />
	                </a>
	              </li>
	               -->
	            </ul>
	        </div>
	    </div>  
	    
	    <?php endif;?>
	    
	
	    <!-- Bootstrap core JavaScript
	    ================================================== -->
	    <script src="<?= $this->basePath('lib/bootstrap/dist/js/bootstrap.min.js') ?>"></script>
	    <script src="<?= $this->basePath('lib/smooth-scroll/SmoothScroll.js') ?>"></script>
	    <script src="<?= $this->basePath('lib/duplob/js/bootstrap-validator.js') ?>"></script>
	
	    <!-- smooth scroll -->
	    <script type="text/javascript">
	      $(function(){
	          $('a').attr('href', function() {
	              if(/\#/.test(this.href)){
	                  var hrefParts = this.href.split(/#/);

	                  if('slideCarousel' != hrefParts[1]){
	                	  hrefParts[1] = 'smoothScroll' + hrefParts[1];	
	                  }
	                  
	                  return hrefParts.join('#');
	              }else{
	                  return this.href;
	              }
	          });
	
	          // executa ao carregar
	          var reSmooth = /^#smoothScroll/;
	          if (reSmooth.test(location.hash)) {
	              // Strip the "#smoothScroll" part off (and put "#" back on the beginning)
	              var id = '#' + location.hash.replace(reSmooth, '');
	              $.smoothScroll({scrollTarget: id});
	          }
	
	          $('a').on('click', function(){
	              var reSmooth = /#smoothScroll/;
	              if (reSmooth.test(this.href)) {
	                  var hrefParts = this.href.split(/#/);
	
	                  var id = '#' + ('#' + hrefParts[1]).replace(reSmooth, '');
	                  $.smoothScroll({scrollTarget: id});
	              }
	          });
	      });
	    </script>
    </body>
</html>
