<div id="section-slide" class="section col-lg-12">
	<div id="slideCarousel" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#slideCarousel" data-slide-to="0" class="active"></li>
	    <li data-target="#slideCarousel" data-slide-to="1" ></li>
	    <li data-target="#slideCarousel" data-slide-to="2" ></li>
	  </ol>
	
	  <!-- Wrapper for slides -->
	  <div class="carousel-inner">
	    <div class="item active">
	    	<img src="<?= $this->basePath('img/ambientes/slide-12.jpg'); ?>" alt="Ambientes">
	    </div>
	    
	    <div class="item">
	    	<img src="<?= $this->basePath('img/ambientes/slide-13.jpg'); ?>" alt="Ambientes">
	    </div>
	  </div>
	
	  <!-- Left and right controls -->
	  <a class="left carousel-control" href="#slideCarousel" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#slideCarousel" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
</div>