<?php if(!$this->layout()->usuario): ?>
	<div id="experiencia-tuttemob">
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			EXPERIÊNCIA TUTTEMOB
		</a>
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			INICIE AGORA!
		</a>
	</div>
<?php endif; ?>

<div id="section-ambientes-tela1" class="section section-8-4 section-ambientes col-lg-12">
	<div class="col-md-12">
		<div class="section-background">
			<img src="<?= $this->basePath('img/paginas/6.png'); ?>" />
		</div>
		
		<div class="col-xs-9">
			<h2>Nossa <br /> inspiração é você.</h2>
		</div>
	</div>
</div>

<div id="section-ambientes-tela2" class="section section-8-4 section-ambientes col-lg-12">
	<div class="col-md-12">
		<div class="section-background"></div>
		
		<div class="col-xs-9">
			<h2>Móveis Planejados <br /> que se ajustam a sua <br /> necessidade.</h2>
			<p>
				Nós estamos cansados de projetos de móveis Planejados
				que não atendem de forma plena a necessidade das pessoas.
				Por isso, todos os nossos ambientes foram inspirados
				<b>na vida real</b>, com medidas reais e para usuários reais,
				do jeito que você sonha.
			</p>
		</div>
	</div>
</div>

<div id="section-ambientes-tela3" class="section section-8-4 section-ambientes col-lg-12">
	<div class="col-md-4">
		<h2>Quem disse que para morar em um lugar incrível é necessário investir muito?</h2>
	</div>
	<div class="col-md-8">
		<div class="section-background">
			<img src="<?= $this->basePath('img/paginas/9.png'); ?>" />
		</div>
	</div>

	<div class="section-ambientes-link">
		<div class="col-xs-11">
			INSPIRAÇÃO PARA APARTAMENTOS DE UM
			DORMITÓRIO, QUITINETES OU ESTÚDIOS.
		</div>
		<div class="col-xs-1">
			<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
		</div>
	</div>
</div>

<div id="section-ambientes-tela4" class="section section-8-4 section-ambientes col-lg-12">
	<div class="col-md-4">
		<h2>
			Seja qual <br />
			for o tamanho da sua familía, nós podemos planejar espaços para todos!
		</h2>
	</div>
	<div class="col-md-8">
		<div class="section-background">
			<img src="<?= $this->basePath('img/paginas/8.png'); ?>" />
		</div>
	</div>

	<div class="section-ambientes-link">
		<div class="col-xs-1">
			<span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
		</div>
		<div class="col-xs-11">
			INSPIRAÇÃO PARA APARTAMENTOS <br />
			DE DOIS DORMITÓRIOS OU MAIS.
		</div>
	</div>
</div>

<div id="section-ambientes-tela5" class="section section-8-4 section-ambientes col-lg-12">
	<div class="col-md-4">
		<h2>
			Criatividade por aqui não falta. <br />
			E a inspiração está no que você procura.
		</h2>
	</div>
	<div class="col-md-8">
		<div class="section-background">
			<img src="<?= $this->basePath('img/paginas/10.png'); ?>" />
		</div>
	</div>

	<div class="section-ambientes-link">
		<div class="col-xs-11">
			INSPIRAÇÃO PARA APARTAMENTOS AUTÊNTICOS
			E CHEIOS DE PERSONALIDADE.
		</div>
		<div class="col-xs-1">
			<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
		</div>
	</div>
</div>

<div id="section-ambientes-tela6" class="section section-8-4 section-ambientes col-lg-12">
	<div class="col-md-12">
		<div class="section-background"></div>
		
		<div class="col-xs-9">
			<h2>
				Venha também fazer <br />
				parte da revolução na nova <br />
				experiência de compra de <br />
				móveis planejados.	
			</h2>
			
			<?php if(!$this->layout()->usuario): ?>
				<div id="experiencia-tuttemob2">
					<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
						INICIE AGORA!
					</a>
				</div>
			<?php else: ?>
				<div>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
				</div>
			<?php endif; ?>

			<p style="line-height:50px">&nbsp;</p>
		</div>
	</div>
</div>

<div id="section-ambientes-gallery-tela3" class="section-ambientes-gallery">
	<a href="<?= $this->basePath('img/paginas/10.png'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/10.png'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/9.png'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/9.png'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/8.png'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/8.png'); ?>" width="75" height="75"></a>
</div>

<div id="section-ambientes-gallery-tela4" class="section-ambientes-gallery">
	<a href="<?= $this->basePath('img/paginas/cozinha2.jpg'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/cozinha2.jpg'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/dormitoriocasal01.jpg'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/dormitoriocasal01.jpg'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/dormitoriocasal02.jpg'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/dormitoriocasal02.jpg'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/dormitorioinfantil.jpg'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/dormitorioinfantil.jpg'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/homefrontal.jpg'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/homefrontal.jpg'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/homelateral.jpg'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/homelateral.jpg'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/banheirosocial.jpg'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/banheirosocial.jpg'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/lavanderia.jpg'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/lavanderia.jpg'); ?>" width="75" height="75"></a>
</div>

<div id="section-ambientes-gallery-tela5" class="section-ambientes-gallery">
	<a href="<?= $this->basePath('img/paginas/10.png'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/10.png'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/9.png'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/9.png'); ?>" width="75" height="75"></a>
	<a href="<?= $this->basePath('img/paginas/8.png'); ?>" title="Tuttemob"><img src="<?= $this->basePath('img/paginas/8.png'); ?>" width="75" height="75"></a>
</div>

<script type="text/javascript">
$(document).ready(function(){
	ajustaWidHei = function(){
		$('body').css('overflow', 'hidden');
		$('#section-content').css('overflow', 'hidden');
		$('#section-content').css('overflow-y', 'auto');
		
		if($(window).width() < 800){
		}else{
			var menuHeight = $('#menu-nav-left').outerHeight() + 'px';
			$('.section-background img').css('height', menuHeight);
			$('#section-ambientes-tela3 .section-background').css('height', menuHeight);
			$('#section-ambientes-tela3 .col-md-4').css('height', menuHeight);
			$('#section-ambientes-tela4 .section-background').css('height', menuHeight);
			$('#section-ambientes-tela4 .col-md-4').css('height', menuHeight);
			$('#section-ambientes-tela5 .section-background').css('height', menuHeight);
			$('#section-ambientes-tela5 .col-md-4').css('height', menuHeight);
		}
	};

	// ajustes iniciais
	ajustaWidHei();

	// ajusta dimensoes em monitoramento
	setInterval(function(){
		ajustaWidHei();
	}, 300);
});
</script>

<link rel="stylesheet" href="<?= $this->basePath('lib/magnific-popup/dist/magnific-popup.css'); ?>">
<script src="<?= $this->basePath('lib/magnific-popup/dist/jquery.magnific-popup.min.js'); ?>" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function(){
	$('#section-ambientes-gallery-tela3').magnificPopup({
		delegate: 'a',
		type: 'image',
		tLoading: 'Loading image #%curr%...',
		gallery: {
			enabled: true,
			navigateByImgClick: true,
			preload: [0,1] // Will preload 0 - before current, and 1 after the current image
		},
		image: {
			tError: '<a href="%url%">The image #%curr%</a> could not be loaded.'
		}
	});

	$('#section-ambientes-gallery-tela4').magnificPopup({
		delegate: 'a',
		type: 'image',
		tLoading: 'Loading image #%curr%...',
		gallery: {
			enabled: true,
			navigateByImgClick: true,
			preload: [0,1] // Will preload 0 - before current, and 1 after the current image
		},
		image: {
			tError: '<a href="%url%">The image #%curr%</a> could not be loaded.'
		}
	});

	$('#section-ambientes-gallery-tela5').magnificPopup({
		delegate: 'a',
		type: 'image',
		tLoading: 'Loading image #%curr%...',
		gallery: {
			enabled: true,
			navigateByImgClick: true,
			preload: [0,1] // Will preload 0 - before current, and 1 after the current image
		},
		image: {
			tError: '<a href="%url%">The image #%curr%</a> could not be loaded.'
		}
	});

	$('#section-ambientes-tela3 .section-ambientes-link, #section-ambientes-tela3 .section-background').click(function(){
		$('#section-ambientes-gallery-tela3 a:first').click();
	});
	$('#section-ambientes-tela4 .section-ambientes-link, #section-ambientes-tela4 .section-background').click(function(){
		$('#section-ambientes-gallery-tela4 a:first').click();
	});
	$('#section-ambientes-tela5 .section-ambientes-link, #section-ambientes-tela5 .section-background').click(function(){
		$('#section-ambientes-gallery-tela5 a:first').click();
	});
});
</script>