<div id="section-ambientes" class="section col-lg-12">
	<div class="col-md-5">
		<h1>AMBIENTES TUTTEMOB</h1>
		
		<p>O que temos de melhor?</p>
		<p>Uma linha de <b>produtos próprios</b>, desenvolvidos de <b>maneira inteligente</b> para <b>caber no seu bolso</b>,
			<br /> e toda disposição para entregar e montar na sua casa enquanto você navega. :)</p>
	</div>
	<div class="col-md-7">
		<div class="col-xs-4">
			<img class="img-responsive" src="<?= $this->basePath('img/layout/ambientes-cozinha.png'); ?>" />
		</div>
		
		<div class="col-xs-4">
			<img class="img-responsive" src="<?= $this->basePath('img/layout/ambientes-quarto.png'); ?>" />
		</div>
		
		<div class="col-xs-4">
			<a href="<?= $this->url('home', array('action' => 'ambientes-home-theater')); ?>" title="Home Theater">
				<img class="img-responsive" src="<?= $this->basePath('img/layout/ambientes-home-theater.png'); ?>" />
			</a>
		</div>
		
		<div class="col-xs-4">
			<img class="img-responsive" src="<?= $this->basePath('img/layout/ambientes-servico.png'); ?>" />
		</div>
		
		<div class="col-xs-4">
			<img class="img-responsive" src="<?= $this->basePath('img/layout/ambientes-banheiro.png'); ?>" />
		</div>
		
		<div class="col-xs-4">
			<img class="img-responsive" src="<?= $this->basePath('img/layout/ambientes-home-office.png'); ?>" />
		</div>
	</div>
</div>