<div id="section-login" class="section section-8-4 col-lg-12">
	
	<!-- 
	<div class="col-md-12">
		<?php if($this->success):?>
			<div class="alert alert-success" role="alert"><?= $this->success; ?></div>
	    <?php endif;?>

	    <?php if($this->error):?>
	    	<div class="alert alert-danger" role="alert"><?= $this->error; ?></div>
	    <?php endif;?>
    </div>
     -->
           
	<div class="col-md-8">
		<div class="section-background">
			<img src="<?= $this->basePath('img/layout/B1.png'); ?>" />
		</div>
		
		<div class="col-xs-9">
			<h2>O novo já <br /> chegou.</h2>
			<p>A partir de agora vamos guiá-lo a</p>
			<p>uma <b>nova experiência de compra</b> em</p>
			<p>móveis planejados.</p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="cadastro">
			<form id="formLogin" method="post" data-toggle="validator">
				<input type="hidden" name="acao" value="cadastrar" />
				<input type="hidden" name="fone_cel" value="0">
				
				<div class="form-group">
	            	<label for="nome">Nos conte o seu nome completo:</label>
					<input type="text" class="form-control" name="nome" value="<?php echo isset($_SESSION['nome'])? $_SESSION['nome']: '';?>" required>
				</div>
						
				<div class="form-group">
					<label for="email">Nos conte o seu e-mail:</label>
					<input type="email" class="form-control" name="email" value="<?php echo $_SESSION['email'];?>" required>
				</div>
					
				<div class="form-group">
	            	<label for="senha">Escolha uma senha:</label>
				   	<input type="password" class="form-control" name="senha" value="<?php echo $_SESSION['senha'];?>" required>
				</div>
				
				<div class="form-group">
	            	<label for="senharepeat">Repita a senha:</label>
				   	<input type="password" class="form-control" name="senharepeat" value="<?php echo $_SESSION['senharepeat'];?>" required>
				</div>
	
				<div class="form-group" style="text-align: right">
					<a href="<?= $this->url('login'); ?>" title="Login" id="a-ja-sou-cadastrado">Já sou cadastrado</a>
				</div>
			            			
			    <?php if($this->error):?>
			    	<div class="alert alert-danger" role="alert"><?= $this->error; ?></div>
			    <?php endif;?>
				
				<div class="form-group">
					<button type="submit" class="btn btn-block">Cadastrar</button>
	            </div>
				
				<div class="form-group">
					<button type="button" id="loginComFacebok" class="btn btn-block">Entrar com o Facebook</button>
	            </div>
			</form>
		</div>
		
		<?php 
			unset($_SESSION["nome"]);
			unset($_SESSION["email"]);
			unset($_SESSION["senha"]);
			unset($_SESSION["senharepeat"]);
		?>
	</div>
</div>

<div class="modal fade" id="briefing-cadastro-sucesso" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <h2>Feito!</h2>
                <p>
                    Seu cadastro foi concluído com sucesso<br>
                    e enviamos um e-mail de confirmação para você :)
                </p>
                <br>
                <p>
                    Aguardamos o seu retorno para que juntos<br>
                    possamos fazer parte da nova experiência na<br>
                    compra dos seus móveis planejados
                </p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-dismiss="modal">OK, ENTENDI!</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(function(){
	$('#cadastrar').click(function(){
		$('#modalClienteForm').submit();
	});
});

$(document).ready(function(){
	  $('.date').mask('11/11/1111');
	  $('.time').mask('00:00:00');
	  $('.date_time').mask('99/99/9999 00:00:00');
	  $('.cep').mask('99999-999');
	  $('.phone').mask('(99) 99999-9999');
	  $('.phone_with_ddd').mask('(99) 9999-9999');
	  $('.phone_us').mask('(999) 999-9999');
	  $('.mixed').mask('AAA 000-S0S');
});

jQuery(function($){
	$("#campoData").mask("99/99/9999");
	$("#campoTelefone").mask("(999) 09999-9999");
	$("#campoSenha").mask("***-****");
});		
</script>

<script type="text/javascript">
$(document).ready(function(){
	ajustaWidHei = function(){
		$('body').css('overflow', 'hidden');
		$('#section-content').css('overflow', 'hidden');
		
		if($(window).width() < 800){
		}else{
			var menuHeight = $('#menu-nav-left').outerHeight() + 'px';
			$('.section-background img').css('height', menuHeight);
		}
	};

	// ajustes iniciais
	ajustaWidHei();

	// ajusta dimensoes em monitoramento
	setInterval(function(){
		ajustaWidHei();
	}, 300);

    <?php if($this->success): ?>
        $('#briefing-cadastro-sucesso').modal('show');
    <?php endif; ?>
});
</script>