<div id="section-login" class="section col-lg-12">
	
	<!-- 
	<div class="col-md-12">
		<?php if($this->success):?>
			<div class="alert alert-success" role="alert"><?= $this->success; ?></div>
	    <?php endif;?>
	            			
	    <?php if($this->error):?>
	    	<div class="alert alert-danger" role="alert"><?= $this->error; ?></div>
	    <?php endif;?>
    </div>
     -->
           
	<div class="col-md-8">
		<div class="col-xs-3">
			<img src="<?= $this->basePath('img/layout/seta-conteudo.png'); ?>" />
		</div>
		
		<div class="col-xs-9">
			<p>A partir de agora vamos guiá-lo a uma <b>nova</b></p>
			<p><b>experiência de compra</b> em móveis planejados.</p>
			<p>&nbsp;</p>
			<p>Precisamos conhecer as suas <b>preferências e necessidades</b></p>
			<p>para que os nossos especialistas em projeto possam aproveitar</p>
			<p>o que temos de melhor para deixar o seu ambiente</p>
			<p><b>adequado ao que você procura. :)</b></p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="login-title">
			<h4>Para isso, precisamos de alguns dados pessoais. Enviaremos a confirmação para o e-mail cadastrado.</h4>
		</div>

		
		<form id="formLogin" method="post" data-toggle="validator">
			<input type="hidden" name="acao" value="cadastrar" />
			<input type="hidden" name="fone_cel" value="0">
			
			<div class="form-group">
            	<label for="nome">Nos conte o seu nome completo:</label>
				<input type="text" class="form-control" name="nome" value="<?php echo isset($_SESSION['nome'])? $_SESSION['nome']: '';?>" placeholder="Nome completo" required>
			</div>
					
			<div class="form-group">
				<label for="email">Nos conte o seu e-mail:</label>
				<input type="email" class="form-control" name="email" value="<?php echo $_SESSION['email'];?>" placeholder="E-mail" required>
			</div>
				
			<div class="form-group">
            	<label for="senha">Escolha uma senha:</label>
			   	<input type="password" class="form-control" name="senha" value="<?php echo $_SESSION['senha'];?>" placeholder="Senha" required>
			</div>
			
			<div class="form-group">
            	<label for="senharepeat">Repita a senha:</label>
			   	<input type="password" class="form-control" name="senharepeat" value="<?php echo $_SESSION['senharepeat'];?>" placeholder="Senha" required>
			</div>

			<?php if($this->success):?>
				<div class="alert alert-success" role="alert"><?= $this->success; ?></div>
		    <?php endif;?>
		            			
		    <?php if($this->error):?>
		    	<div class="alert alert-danger" role="alert"><?= $this->error; ?></div>
		    <?php endif;?>
			
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
            </div>
			
			<div class="form-group">
				<button type="button" id="loginComFacebok" class="btn btn-primary btn-block">Entrar com Facebook</button>
            </div>
		</form>
		
		<?php 
			unset($_SESSION["nome"]);
			unset($_SESSION["email"]);
			unset($_SESSION["senha"]);
			unset($_SESSION["senharepeat"]);
		?>
	</div>
</div>

<script type="text/javascript">
$(function(){
	$('#cadastrar').click(function(){
		$('#modalClienteForm').submit();
	});
});

$(document).ready(function(){
	  $('.date').mask('11/11/1111');
	  $('.time').mask('00:00:00');
	  $('.date_time').mask('99/99/9999 00:00:00');
	  $('.cep').mask('99999-999');
	  $('.phone').mask('(99) 99999-9999');
	  $('.phone_with_ddd').mask('(99) 9999-9999');
	  $('.phone_us').mask('(999) 999-9999');
	  $('.mixed').mask('AAA 000-S0S');
});

jQuery(function($){
	$("#campoData").mask("99/99/9999");
	$("#campoTelefone").mask("(999) 09999-9999");
	$("#campoSenha").mask("***-****");
});		
</script>