<?php if(!$this->layout()->usuario): ?>
	<div id="experiencia-tuttemob">
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			EXPERIÊNCIA TUTTEMOB
		</a>
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			INICIE AGORA!
		</a>
	</div>
<?php endif; ?>

<div id="section-depoimentos-tela1" class="section section-depoimentos col-lg-12">
	<div class="col-md-12">
		<div class="section-background"></div>
		
		<div class="col-xs-12">
			<h2>Facilitamos a sua <br /> vida.</h2>
			<p>
				Através de um sistema digital, inteligente e eficiente, <br />
				o que buscamos é proporcionar a você uma experiência de compra <br />
				diferente, com segurança e confiabilidade. <br />				
			</p>
			<p class="p-mobile hide">
				Através de um sistema digital, inteligente e eficiente,
				o que buscamos é proporcionar a você uma experiência de compra
				diferente, com segurança e confiabilidade.		
			</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
		</div>
	</div>
</div>

<div id="section-depoimentos-tela2" class="section section-depoimentos col-lg-12">
	<!-- Carousel
		================================================== -->
		<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel" data-slide-to="1"></li>
			<li data-target="#myCarousel" data-slide-to="2"></li>
		  </ol>
		  <div class="carousel-inner" role="listbox">
			<div class="item active">
			  <img class="first-slide" src="<?= $this->basePath('img/paginas/foto-cliente2.png'); ?>" alt="First slide">
			  <div class="container">
				<div class="carousel-caption text-left">
					<!--
					<h1>Example headline.</h1>
					<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
					-->
					<div class="box">
						<p class="p1">
							Fulano de Tal
						</p>
						<p class="p2">
							@FulanodeTal.<br />
							&nbsp;<br />
							aaaaaaa aaaaaaaa<br />
							aaaaa aaaaaaa aaaaaaaaaa<br />
							aaaaaaaaaaa<br />
							aaaa aa aaaa aaaa aaaaaa aaaa aaa<br />
							aaaaaaaaaa aaaaa<br />
							aaaaaaaaa aaaaaaaaa aaaaaaa<br />
						</p>
					</div>

					<!--<p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>-->
				</div>
			  </div>
			</div>
			<div class="item">
			  <img class="second-slide" src="<?= $this->basePath('img/paginas/descubra1.png'); ?>" alt="Second slide">
			  <div class="container">
				<div class="carousel-caption text-left">
						<!--
						<h1>Another example headline.</h1>
						<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
						<p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
						-->
						<div class="box">
							<p class="p1">
								Fulano de Tal2
							</p>
							<p class="p2">
								@FulanodeTal2.<br />
								&nbsp;<br />
								bbbb bbbbbbb bbbbbbbbbbbbbbbb bbbb bbbb<br />
								bbbbbbbb bbbbbbbb<br />
								bbbbbb bbbbbbbbbbbbb bbbbbb<br />
								bbbbb<br />
								bbbbbbbbbbb bbb<br />
							</p>
						</div>
					  </div>
			  </div>
			</div>
			<div class="item">
			  <img class="third-slide" src="<?= $this->basePath('img/paginas/descubra2.png'); ?>" alt="Third slide">
			  <div class="container">
				<div class="carousel-caption text-left">
						<!--
						<h1>One more for good measure.</h1>
						<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
						<p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
						-->
						<div class="box">
							<p class="p1">
								Ciclano de Tal
							</p>
							<p class="p2">
								@CiclanodeTal.<br />
								&nbsp;<br />
								ccccc<br />
								ccc cccccccc<br />
								cccccc ccccccccccc<br />
								ccccccccc<br />
								cccc ccccccccccccccc ccccc ccccccc ccccc<br />
								ccccc cccccccccc<br />
							</p>
						</div>						
					  </div>
			  </div>
			</div>
		  </div>
		  <!-- <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		  </a> -->
		</div><!-- /.carousel -->
	
</div>
 

<div id="section-depoimentos-tela3" class="section section-depoimentos col-lg-12">
	<div class="col-md-12">
		<div class="section-background"></div>
		
		<div class="col-xs-9">
			<h2>
				Vem fazer parte<br />
				da nova experiência em <br />
				móveis planejados!
				<p>&nbsp;</p>				
			</h2>
		</div>
		<div class="col-xs-12">
			<?php if(!$this->layout()->usuario): ?>
				<div id="experiencia-tuttemob2">
					<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
						INICIE AGORA!
					</a>
				</div>
				
				<p>&nbsp;</p>
				<p>&nbsp;</p>
			<?php else: ?>
				<div>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
				</div>
			<?php endif; ?>

			<p style="line-height:50px">&nbsp;</p>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	ajustaWidHei = function(){
		if($(window).width() < 800){
			$('body').css('overflow', 'hidden');
			$('#section-content').css('overflow', 'auto');
			$('#section-content').css('padding-bottom', '80px');

			$('.carousel').css('height', ($(window).height() * 0.50) + 'px');
			$('.carousel .item').css('height', ($(window).height() * 0.50) + 'px');
			$('.carousel .item .box').css('height', (($(window).height() * 0.50) - 20) + 'px');
			$('.carousel .item img').css('transform', 'translate(-20%, 0%)');
		}
	};

	// ajustes iniciais
	ajustaWidHei();

	// ajusta dimensoes em monitoramento
	setInterval(function(){
		ajustaWidHei();
	}, 300);
});
</script>