<?php if(!$this->layout()->usuario): ?>
	<div id="experiencia-tuttemob">
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			EXPERIÊNCIA TUTTEMOB
		</a>
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			INICIE AGORA!
		</a>
	</div>
<?php endif; ?>

<div id="section-desktop-descubra">
	<div class="section-descubra1-link1 section col-lg-12">
		<div class="section-background">
			<img src="<?= $this->basePath('img/paginas/inicial-2-bg.png'); ?>" class="img-responsive" />
		</div>
		<div class="section-page">
			<div id="p2">
				A tuttemob é o
			</div>
			<div id="p3">
				novo, com todas as <br /> 
				vantagens de comprar <br />
				via internet.
			</div>
			<div id="p4">
				 Descubra
				<div class="link-border"></div>
			</div>
		</div>

		<div class="box">
			<div class="p1">
				<div class="col-md-4">
					O Novo
					<div class="link-border"></div>
				</div>
				<div class="col-md-4">
					<a href="<?= $this->url('home', array('action' => 'descubra-link-dois')); ?>">
						Custo x Benefício
					</a>
				</div>
				<div class="col-md-4">
					<a href="<?= $this->url('home', array('action' => 'descubra-link-tres')); ?>">
						Móveis Inteligentes
					</a>
				</div>
			</div>
		</div>							
	</div>
	
	<div class="section-descubra2-link1 section col-lg-12">
		<div class="col-md-4">
		</div>
		<div class="col-md-8">
			<div class="section-background">
				<img src="<?= $this->basePath('img/paginas/descubra1.png'); ?>" class="img-responsive" />
			</div>
		</div>
	</div>	

	<div class="section-descubra2-link1 section col-lg-12">
		<div class="section-page">
			<div class="box">
				<p class="p1">
					Nós somos diferentes de tudo o que você já conhece sobre móveis planejados.
				</p>
			</div>
		</div>
	</div>

	<div class="section-descubra3-link1 section col-lg-12">
		<div class="section-page">
			<p class="p1">
				Os serviços de uma loja física, como: <br />
				<b>medição, projeto, apresentação, entrega e montagem</b> <br />
				também sao feitos pela gente, porém de uma maneira <br />
				mais eficiente do que a você conhece, experimentou <br />
				ou ouviu falar.
			</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
		</div>
	</div>

	<div class="section-descubra4-link1 section col-lg-12">
		<div class="section-page">
			<div>
				<p class="p1">
					Venha também fazer <br />
					parte da revolução na nova <br />
					experiência de compra de<br />
					móveis planejados.
				</p>
			<p>&nbsp;</p>
			</div>
			
			<?php if(!$this->layout()->usuario): ?>
				<div id="experiencia-tuttemob2">
					<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
						INICIE AGORA!
					</a>
				</div>

				<p>&nbsp;</p>
				<p>&nbsp;</p>
			<?php else: ?>
				<div>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
				</div>				
			<?php endif; ?>
			<!-- 
			<div>
				<br />
				<p class="p2">
					<a href="#">Ou baixe o App já disponível na Apple Store <br />
					e na Google Store.</a> 
				</p>
				<br />
			</div>
			 -->
		</div>		
	</div>
</div>

<div id="section-mobile-descubra" style="visibility: hidden; position: relative; margin: 0 auto;
									top: 0px; left: 0px; width: 0; height: 0; overflow: hidden;">

	<!-- Slides Container -->
	<div u="slides" style="cursor:move;position: absolute; left: 0px; top: 0px; width: 0; height: 0; overflow: hidden;">
		<div>
			<div class="section-descubra1-link1 section col-lg-12">
				<div class="section-background">
					<img src="<?= $this->basePath('img/paginas/inicial-2-bg.png'); ?>" />
				</div>
				<div class="section-page">
					<div id="p2">
						A tuttemob é o
					</div>
					<div id="p3">
						novo, com <br />
						todas <br />
						as vantagens <br />
						de comprar <br />
						via internet.
					</div>
				</div>

				<!--
				<a class="pbutton" href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">DESCUBRA</a>
				 -->
				 <a class="pbutton">DESCUBRA</a>
			</div>
		</div>
		<div>
			<div class="section-descubra2-link1 section col-lg-12">
				<div class="section-background">
					<img src="<?= $this->basePath('img/paginas/inicial-3-bg.png'); ?>" />
				</div>
				<div class="section-page">
					<div id="p3">
						Não <br />
						somos apenas <br />
						digitais.
					</div>
				</div>

				<a class="pbutton" href="<?= $this->url('home', array('action' => 'franquias')); ?>">ENCONTRE</a>
			</div>
		</div>
		<div>
			<div class="section-descubra1-link1 section-descubra3-link1 section col-lg-12">
				<div class="section-background">
					<img src="<?= $this->basePath('img/paginas/inicial-4-bg.png'); ?>" />
				</div>
				<div class="section-page">
					<div id="p2">
						O que nos move é a
					</div>
					<div id="p3">
						satisfação de <br /> 
						quem já passou <br />
						por aqui.
					</div>
				</div>

				<a class="pbutton" href="<?= $this->url('home', array('action' => 'experiencia-clientes')); ?>">VEJA</a>
			</div>
		</div>
	</div>

	<!-- Bullet Navigator -->
	<div data-u="navigator" id="navigator" style="position:absolute;bottom:12px;right:12px;" data-autocenter="1" data-scale="0.5" data-scale-bottom="0.75">
		<div data-u="prototype" class="i" style="width:16px;height:16px;">
			<svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
				<circle class="b" cx="8000" cy="8000" r="5800"></circle>
			</svg>
		</div>
	</div>
</div>

<style>
@media screen and (max-width: 800px){
	#menu-nav-left {
	  position: absolute !important;
	}
}
</style>

<script src="<?= $this->basePath('lib/jssor/jssor.slider.min.js') ?>"></script>

<script type="text/javascript">
$(document).ready(function(){
	ajustaWidHei = function(){
		if($(window).width() < 800){
			$('body').css('overflow', 'hidden');
			$('#section-content').css('overflow', 'hidden');
		}else{
			$('body').css('overflow', 'auto');
			$('#section-content').css('overflow', 'auto');
		}

		var winWidth = $(window).width() + 'px';
		var winHeight = ($(window).height()) + 'px';
		$('#section-mobile-descubra').attr('style', $('#section-mobile-descubra').attr('style').replace(/(width: )([0-9]{1,4})(px)?/, 'width: ' + winWidth));
		$('#section-mobile-descubra').attr('style', $('#section-mobile-descubra').attr('style').replace(/(height: )([0-9]{1,4})(px)?/, 'height: ' + winHeight));
		$('#section-mobile-descubra div').each(function(){
			if(	$(this).attr('style') != undefined 
				&& $(this).parents('#navigator').length == 0
				&& $(this).attr('id') != 'navigator')
			{
				$(this).attr('style', $(this).attr('style').replace(/(width: )([0-9]{1,4})(px)?/, 'width: ' + winWidth));
				$(this).attr('style', $(this).attr('style').replace(/(height: )([0-9]{1,4})(px)?/, 'height: ' + winHeight));
				if($(this).find('#navigator').length > 0){
					$(this).attr('style', $(this).attr('style').replace(/(height: )([0-9]{1,4})(px)?/, 'height: 30px'));
					$(this).css('left', 0);
				}
			}
		});
		$('#section-mobile-descubra div.section-background img').css('height',winHeight);
		$('#section-mobile-descubra div.section-background img').css('transform', 'translate(-35%, 0%)');
	};

	// ajustes iniciais
	ajustaWidHei();

	// inicia o slide
	setTimeout(function() {
		var options = {
            $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$,
                $ChanceToShow: 2
            }
        };
		var jssor_slider1 = new $JssorSlider$("section-mobile-descubra", options);	
	}, 100);

	// ajusta dimensoes em monitoramento
	setInterval(function(){
		ajustaWidHei();
	}, 300);
});
</script>