<?php if(!$this->layout()->usuario): ?>
	<div id="experiencia-tuttemob">
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			EXPERIÊNCIA TUTTEMOB
		</a>
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			INICIE AGORA!
		</a>
	</div>
<?php endif; ?>

<div id="section-desktop-franquias">
	<div id="section-franquias-tela1" class="section section-franquias col-lg-12">
		<div class="col-md-12">
			<div class="section-background">
				<img src="<?= $this->basePath('img/paginas/franquias.png'); ?>" />
			</div>
			
			<div class="col-xs-9">
				<h2>A TutteMob possui <br />
				lojas físicas nas regiões onde <br />
				oferece a venda online.</h2>
			</div>
		</div>
	</div>

	<div id="section-franquias-tela2" class="section section-franquias col-lg-12">
		<div class="col-md-12">
			<div class="section-background"></div>
			
			<div class="col-xs-9">
				<p>
					Aqui você faz tudo via internet e ainda <br />
					pode conhecer o produto antes de finalizar a compra. <br/>
					Na TutteMob é fácil assim! <br />
					Buscamos a inovação a todo custo, <br />
					em respeito ao seu tempo <br />
					e a segurança do seu investimento.
				</p>
				<h2>Encontre a Tutte mais <br />
				próxima de você :)</h2>
			</div>
		</div>
	</div>
	
	<div id="section-franquias-tela3" class="section section-franquias col-lg-12">
		<div id="section-mapa-interno">
			<!-- Google MAP -->
		</div>

		<form name="formMapa" id="formMapa" class="form-horizontal" enctype="multipart/form-data">	
			<div class="form-group col-xs-12">
				<label for="pais" class="col-sm-2">País</label>	
				<div class="col-sm-10">			   	
					<select class="form-control" id="pais" disabled>
						<option value="">Selecione...</option>
						<option value="1" selected>Brasil</option>
						<option value="2">Argentina</option>
					</select>
				</div>
			</div>
			<div class="form-group col-xs-12">
				<label for="estado" class="col-sm-2">Estado</label>
				<div class="col-sm-10">				   	
					<select class="form-control" id="estado" disabled>
						<option value="">Selecione...</option>
						<option value="1" selected>Rio Grande do Sul</option>
						<option value="2">Santa Catarina</option>
						<option value="2">Paraná</option>
					</select>
				</div>
			</div>
			<div class="form-group col-xs-12">
				<label for="cidade" class="col-sm-2">Cidade</label>
				<div class="col-sm-10">				   	
					<select class="form-control" id="cidade" disabled>
						<option value="">Selecione...</option>
						<option value="1" selected>Passo Fundo</option>
						<option value="2">Bento Gonçalves</option>
						<option value="2">Caxias do Sul</option>
					</select>
				</div> 
			</div>   
		</form>
		
		<div>
			<div class="box">
				<div class="col-sm-4">
					<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
				</div>
				<div class="col-sm-8">
					<p class="p1">
						E onde fica a <br />
						Central de Projetos<br />
						da TutteMob? <br />
					</p>
					<p class="p2">
						Rua xxx, 123 - Centro <br />
						Passo Fundo - RS<br />
					</p>
				</div>
			</div>
		</div>
		
	</div>
</div>
<div id="section-mobile-franquias" class="section-mobile" style="visibility: hidden; position: relative; margin: 0 auto; top: 0px; left: 0px; width: 0; height: 0; overflow: hidden;">

	<!-- Slides Container -->
	<div u="slides" style="cursor:move;position: absolute; left: 0px; top: 0px; width: 0; height: 0; overflow: hidden;">
		<div>
			<div class="section-1 section col-lg-12">
				<div>
					<div class="section-background">
						<img src="<?= $this->basePath('img/paginas/franquias.png'); ?>" />
					</div>
					
					<div class="section-page">
						A TutteMob <br /> 
						possui lojas <br />
						físicas nas regiões <br />
						onde oferece <br />
						a venda online.
					</div>
				</div>
				<div class="section-1-content">
					<p>
						Aqui você faz tudo via internet e ainda
						pode conhecer o produto antes de finalizar a compra.
						Na TutteMob é fácil assim! Buscamos a inovação a todo custo,
						em respeito ao seu tempo e a segurança do seu investimento.
					</p>
				</div>
			</div>
		</div>
		<div>
			<div class="section-2 section col-lg-12">
				<div class="section-2-form col-lg-12">
					<h2>Encontre a Tutte mais próxima de você :)</h2>

					<form class="form-horizontal" enctype="multipart/form-data">	
						<div class="form-group">
							<label for="pais" class="col-sm-2">País</label>	
							<div class="col-sm-10">			   	
								<select class="form-control" id="pais" disabled>
									<option value="">Selecione...</option>
									<option value="1" selected>Brasil</option>
									<option value="2">Argentina</option>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label for="estado" class="col-sm-2">Estado</label>
							<div class="col-sm-10">				   	
								<select class="form-control" id="estado" disabled>
									<option value="">Selecione...</option>
									<option value="1" selected>Rio Grande do Sul</option>
									<option value="2">Santa Catarina</option>
									<option value="2">Paraná</option>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label for="cidade" class="col-sm-2">Cidade</label>
							<div class="col-sm-10">				   	
								<select class="form-control" id="cidade" disabled>
									<option value="">Selecione...</option>
									<option value="1" selected>Passo Fundo</option>
									<option value="2">Bento Gonçalves</option>
									<option value="2">Caxias do Sul</option>
								</select>
							</div> 
						</div>   
					</form>
				</div>
				<div id="section-2-googlemap">
					<!-- Google MAP -->
				</div>
				<div class="section-2-central">
					<div class="col-xs-2">
						<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
					</div>
					<div class="col-xs-10">
						<p class="p1">
							E onde fica a Central de Projetos da TutteMob?
						</p>
						<p class="p2">
							Rua xxx, 123 - Centro - Passo Fundo - RS
						</p>
					</div>
					<div class="col-xs-12">
						<?php if(!$this->layout()->usuario): ?>
							<div id="experiencia-tuttemob2">
								<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
									INICIE AGORA!
								</a>
							</div>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Bullet Navigator -->
	<div data-u="navigator" id="navigator" style="position:absolute;bottom:12px;right:12px;" data-autocenter="1" data-scale="0.5" data-scale-bottom="0.75">
		<div data-u="prototype" class="i" style="width:16px;height:16px;">
			<svg viewbox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
				<circle class="b" cx="8000" cy="8000" r="5800"></circle>
			</svg>
		</div>
	</div>
</div>

<script src="<?= $this->basePath('lib/jssor/jssor.slider.min.js') ?>"></script>


<script type="text/javascript">
$(document).ready(function(){
	ajustaWidHei = function(){
		if($(window).width() < 800){
			$('body').css('overflow', 'hidden');
			$('#section-content').css('overflow', 'hidden');
		}else{
			$('body').css('overflow', 'hidden');
			$('#section-content').css('overflow', 'hidden');
			$('#section-content').css('overflow-y', 'auto');
		}
		
		// mobile
		var winWidth = $(window).width() + 'px';
		var winHeight = ($(window).height()) + 'px';
		$('#section-mobile-franquias').attr('style', $('#section-mobile-franquias').attr('style').replace(/(width: )([0-9]{1,4})(px)?/, 'width: ' + winWidth));
		$('#section-mobile-franquias').attr('style', $('#section-mobile-franquias').attr('style').replace(/(height: )([0-9]{1,4})(px)?/, 'height: ' + winHeight));
		$('#section-mobile-franquias div').each(function(){
			if(	$(this).attr('style') != undefined 
				&& ($(this).parents('#navigator').length == 0 && $(this).attr('id') != 'navigator')
				&& ($(this).parents('#section-2-googlemap').length == 0 && $(this).attr('id') != 'section-2-googlemap'))
			{
				$(this).attr('style', $(this).attr('style').replace(/(width: )([0-9]{1,4})(px)?/, 'width: ' + winWidth));
				$(this).attr('style', $(this).attr('style').replace(/(height: )([0-9]{1,4})(px)?/, 'height: ' + winHeight));
				if($(this).find('#navigator').length > 0){
					$(this).attr('style', $(this).attr('style').replace(/(height: )([0-9]{1,4})(px)?/, 'height: 30px'));
					$(this).css('left', 0);
				}
			}
		});
		$('#section-mobile-franquias div.section-background img').css('height', ($(window).height() * 0.75) + 'px');
		$('#section-mobile-franquias .section-1 .section-background img').css('transform', 'translate(-45%, 0%)');

		$('#section-mobile-franquias .section-2').parent().css('overflow', 'auto');
		
		if($(window).width() > 800){
			var menuHeight = $('#menu-nav-left').outerHeight() + 'px';
			$('.section-background img').css('height', menuHeight);
		}
	};

	// ajustes iniciais
	ajustaWidHei();

	// inicia o slide
	setTimeout(function() {
		var options = {
            $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$,
                $ChanceToShow: 2
            }
        };
		var jssor_slider1 = new $JssorSlider$("section-mobile-franquias", options);	
	}, 100);

	// ajusta dimensoes em monitoramento
	setInterval(function(){
		ajustaWidHei();
	}, 300);
});
</script>

<script>
function myMap() {

	var contentString = '<div id="contentString">' + 
		'<p>Faça-nos uma visita!</p>' +
		'<a href="https://www.google.com/maps/dir/Rua+Morom,+3081+-+Boqueir%C3%A3o,+Passo+Fundo+-+RS,+Brasil//@-28.2685421,-52.4225509,17z/data=!3m1!4b1!4m8!4m7!1m5!1m1!1s0x94e2bf61376873cd:0xaf96e89e6f68519a!2m2!1d-52.4203622!2d-28.2685421!1m0?hl=pt-BR" target="_blank">Loja Passo Fundo</a>' +								 
		'</div>';
		
	var mapCanvas = document.getElementById("section-mapa-interno");
	var myCenter = new google.maps.LatLng(-28.268499,-52.420467); 
	var mapOptions = {center: myCenter, zoom: 18/*, disableDefaultUI: true*/};
	var map = new google.maps.Map(mapCanvas,mapOptions);
	var marker = new google.maps.Marker({
		position: myCenter,
		//animation: google.maps.Animation.BOUNCE
	});
	marker.setMap(map);

	var infowindow = new google.maps.InfoWindow({
		content: contentString
	});
	infowindow.open(map,marker);

	// Map Mobile
	var mapCanvasMobile = document.getElementById("section-2-googlemap");
	var myCenterMobile = new google.maps.LatLng(-28.268499,-52.420467); 
	var mapOptionsMobile = {center: myCenterMobile, zoom: 18/*, disableDefaultUI: true*/};
	var mapMobile = new google.maps.Map(mapCanvasMobile,mapOptionsMobile);
	var markerMobile = new google.maps.Marker({
		position: myCenterMobile,
	});
	markerMobile.setMap(mapMobile);

	var infowindowMobile = new google.maps.InfoWindow({
		content: contentString
	});
	infowindowMobile.open(mapMobile,markerMobile);
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCt6Q5NYmV8Pi-LX1GRnffZP3anE4pu4ek&callback=myMap"></script>
 