<div id="experiencia-tuttemob">
	<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
		EXPERIÊNCIA TUTTEMOB
	</a>
	<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
		INICIE AGORA!
	</a>
</div>
<div id="section-apresentacao" class="section col-lg-12">
	<div class="section-background">
		<img src="<?= $this->basePath('img/paginas/inicial-1-bg.png'); ?>" class="img-responsive" />
	</div>
	<div class="section-page">
		<div id="p1">
			<img src="<?= $this->basePath('img/paginas/inicial-1-logo.png'); ?>" />
		</div>
		<div id="p2">
			Móveis planejados
		</div>
		<div id="p3">
			na palma <br /> da mão.
		</div>
	</div>
</div>

<div id="section-apresentacao2" class="section col-lg-12">
	<div class="section-background">
		<img src="<?= $this->basePath('img/paginas/inicial-2-bg.png'); ?>" class="img-responsive" />
	</div>
	<div class="section-page">
		<div id="p2">
			A tuttemob é o
		</div>
		<div id="p3">
			novo, com todas as <br /> 
			vantagens de comprar <br />
			via internet.
		</div>
		<div id="p4">
			<a href="#">Descubra</a>
			<div class="link-border"></div>
		</div>
	</div>
</div>

<div id="section-apresentacao3" class="section col-lg-12">
	<div class="section-background">
		<img src="<?= $this->basePath('img/paginas/inicial-3-bg.png'); ?>" class="img-responsive" />
	</div>
	<div class="section-page">
		<div id="p3">
			Não <br />
			somos apenas <br />
			digitais.
		</div>
		<div id="p4">
			<a href="#">Encontre</a>
			<div class="link-border"></div>
		</div>
	</div>
</div>

<div id="section-apresentacao2" class="section col-lg-12">
	<div class="section-background">
		<img src="<?= $this->basePath('img/paginas/inicial-4-bg.png'); ?>" class="img-responsive" />
	</div>
	<div class="section-page">
		<div id="p2">
			O que nos move é a
		</div>
		<div id="p3">
			satisfação <br /> 
			de quem já passou <br />
			por aqui.
		</div>
		<div id="p4">
			<a href="#">Veja</a>
			<div class="link-border"></div>
		</div>
	</div>
</div>