<section class="mbr-slider mbr-section mbr-section__container carousel slide mbr-section-nopadding mbr-after-navbar" data-ride="carousel" data-keyboard="false" data-wrap="true" data-pause="false" data-interval="5000" id="slider-16" style="background-color: rgb(154, 91, 144);">
    <div class=" container boxed-slider" style="padding-top: 120px; padding-bottom: 120px;">
        <div>
            <div>
                <ol class="carousel-indicators">
                    <li data-app-prevent-settings="" data-target="#slider-16" data-slide-to="0" class="active"></li><li data-app-prevent-settings="" data-target="#slider-16" data-slide-to="1"></li><li data-app-prevent-settings="" data-target="#slider-16" data-slide-to="2"></li><li data-app-prevent-settings="" data-target="#slider-16" data-slide-to="3"></li><li data-app-prevent-settings="" data-target="#slider-16" data-slide-to="4"></li><li data-app-prevent-settings="" data-target="#slider-16" data-slide-to="5"></li><li data-app-prevent-settings="" data-target="#slider-16" data-slide-to="6"></li><li data-app-prevent-settings="" data-target="#slider-16" class="" data-slide-to="7"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="mbr-section mbr-section-hero carousel-item dark center active" data-bg-video-slide="false">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide">
                                <img src="assets/images/007485c7-0c62-42ff-94b3-4ad9a19d6f9d-2000x1330-62.jpg">
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        
                                        

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center" data-bg-video-slide="false">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide">
                                <img src="assets/images/48175da8-a691-43c0-9469-38889a6b5c3e2-2000x1330-43.jpg">
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        
                                        

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center" data-bg-video-slide="false">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide">
                                <img src="assets/images/37445619-4bbd-4f08-954f-5832670ece4d-2000x1330-87.jpg">
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        
                                        

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center" data-bg-video-slide="false">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide">
                                <img src="assets/images/b31b40ff-a845-4d72-ba61-4c1dcd1d73f9-2000x1330-48.jpg">
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        
                                        

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center" data-bg-video-slide="false">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide">
                                <img src="assets/images/c008be76-6ef3-4015-8497-1ae264e0544b-2000x1330-53.jpg">
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        
                                        

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center" data-bg-video-slide="false">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide">
                                <img src="assets/images/cfc04fb2-af5b-4384-8260-2d89c704d4da-2000x1330-61.jpg">
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        
                                        

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center" data-bg-video-slide="false">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide">
                                <img src="assets/images/d987b4a5-e178-4420-8c9f-be014a19c5d6-2000x1330-6.jpg">
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        
                                        

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center" data-bg-video-slide="false">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide">
                                <img src="assets/images/ddf58272-7317-4e5b-8b1d-cef14bf83a68-2000x1330-10.jpg">
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        
                                        

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <a data-app-prevent-settings="" class="left carousel-control" role="button" data-slide="prev" href="#slider-16">
                    <span class="icon-prev" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a data-app-prevent-settings="" class="right carousel-control" role="button" data-slide="next" href="#slider-16">
                    <span class="icon-next" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</section>

<section class="mbr-slider mbr-section mbr-section__container carousel slide mbr-section-nopadding" data-ride="carousel" data-keyboard="false" data-wrap="true" data-pause="false" data-interval="5000" id="slider-2">
    <div>
        <div>
            <div>
                <ol class="carousel-indicators">
                    <li data-app-prevent-settings="" data-target="#slider-2" data-slide-to="0" class="active"></li><li data-app-prevent-settings="" data-target="#slider-2" data-slide-to="1"></li><li data-app-prevent-settings="" data-target="#slider-2" class="" data-slide-to="2"></li><li data-app-prevent-settings="" data-target="#slider-2" data-slide-to="3"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="mbr-section mbr-section-hero carousel-item dark center mbr-section-full active" data-bg-video-slide="false" style="background-image: url(assets/images/cena-87-home-theater-01-blond-diamant-variacao-de-cena-2000x1166.jpg);">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay" style="opacity: 0;"></div>
                            <div class="container-slide container">
                                
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-2 text-xs-center">
                                        <h2 class="mbr-section-title display-1"></h2>
                                        <p class="mbr-section-lead lead"></p>

                                        <div class="mbr-section-btn"><a class="btn btn-lg btn-success" href="#features3-9">CONHEÇA NOSSAS LOJAS</a> <a class="btn btn-lg btn-danger" href="#content2-6">GALERIA</a> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center mbr-section-full" data-bg-video-slide="false" style="background-image: url(assets/images/berlin-2000x1000.jpg);">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide container">
                                
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        <h2 class="mbr-section-title display-1">Experiências. &nbsp;</h2>
                                        <p class="mbr-section-lead lead">Venha participar e viva momentos inesquecíveis.</p>

                                        <div class="mbr-section-btn"><a class="btn btn-lg btn-info" href="https://mobirise.com"><span class="mbri-right mbr-iconfont mbr-iconfont-btn"></span>Saiba Mais...</a> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center mbr-section-full" data-bg-video-slide="false" style="background-image: url(assets/images/design-europeu-com-preciso-alema-2000x966.jpg);">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay" style="opacity: 0;"></div>
                            <div class="container-slide container">
                                
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-1">
                                        <h2 class="mbr-section-title display-1"></h2>
                                        <p class="mbr-section-lead lead"></p>

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><div class="mbr-section mbr-section-hero carousel-item dark center mbr-section-full" data-bg-video-slide="false" style="background-image: url(assets/images/cena-102-cozinha-01-basalt-diamante-painel-stark-2000x1166.jpg);">
                        <div class="mbr-table-cell">
                            <div class="mbr-overlay"></div>
                            <div class="container-slide container">
                                
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-3 text-xs-right">
                                        <h2 class="mbr-section-title display-1">Móveis planejados</h2>
                                        <p class="mbr-section-lead lead">Para você!!</p>

                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <a data-app-prevent-settings="" class="left carousel-control" role="button" data-slide="prev" href="#slider-2">
                    <span class="icon-prev" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a data-app-prevent-settings="" class="right carousel-control" role="button" data-slide="next" href="#slider-2">
                    <span class="icon-next" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section article mbr-section__container" id="content2-6" style="background-color: rgb(154, 91, 144); padding-top: 40px; padding-bottom: 40px;">

    <div class="container">
        <div class="row">
            <div class="col-xs-12 lead"><blockquote><p><strong><br></strong></p><p><strong>QUEM SOMOS</strong></p><p><br></p><p>Como diz o poeta, sonho que se sonha junto é realidade. A Tutte é fruto da soma de muito empenho e dedicação sob a necessidade do consumidor de hoje: a praticidade e a funcionalidade no seu cotidiano. O resultado dessa nova matemática na forma de fazer móvel é poder te entregar teu sonho enquanto você assiste isso acontecer.</p><p><br></p></blockquote></div>
        </div>
    </div>

</section>

<section class="mbr-section mbr-section__container article" id="header3-h" style="background-color: rgb(247, 63, 128); padding-top: 20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2">Cozinha!</h3>
                <small class="mbr-section-subtitle"></small>
            </div>
        </div>
    </div>
</section>

<section class="mbr-gallery mbr-section mbr-section-nopadding mbr-slider-carousel" id="gallery3-g" data-filter="false" style="background-color: rgb(0, 0, 0); padding-top: 0rem; padding-bottom: 0rem;">
    <!-- Filter -->
    

    <!-- Gallery -->
    <div class="mbr-gallery-row">
        <div class=" mbr-gallery-layout-default">
            <div>
                <div>
                    <div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Animated" data-video-url="false">
                        <div href="#lb-gallery3-g" data-slide-to="0" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/9a430c4c-f221-476c-b789-ac3d10940248-2000x851-58-2000x851-89.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Animated1" data-video-url="false">
                        <div href="#lb-gallery3-g" data-slide-to="1" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/01c4c58d-ed51-4516-affe-391c9c402678-2000x851-97-2000x851-79.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Animated2" data-video-url="false">
                        <div href="#lb-gallery3-g" data-slide-to="2" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/c701a471-c0ad-4656-a27a-17aafdecc3a1-2000x851-58-2000x851-67.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Animated3" data-video-url="false">
                        <div href="#lb-gallery3-g" data-slide-to="3" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/36c76e1e-7c78-4500-a906-fc12ad43575b-2000x851-5-2000x851-5.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Animated5" data-video-url="false">
                        <div href="#lb-gallery3-g" data-slide-to="4" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/b31f5872-cfb7-42cc-b595-9d35931c4d4d-2000x851-43-2000x851-66.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <!-- Lightbox -->
    <div data-app-prevent-settings="" class="mbr-slider modal fade carousel slide" tabindex="-1" data-keyboard="true" data-interval="false" id="lb-gallery3-g">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <ol class="carousel-indicators">
                        <li data-app-prevent-settings="" data-target="#lb-gallery3-g" data-slide-to="0"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-g" data-slide-to="1"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-g" data-slide-to="2"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-g" data-slide-to="3"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-g" class=" active" data-slide-to="4"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item">
                            <img alt="" src="assets/images/9a430c4c-f221-476c-b789-ac3d10940248-2000x851-58.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/01c4c58d-ed51-4516-affe-391c9c402678-2000x851-97.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/c701a471-c0ad-4656-a27a-17aafdecc3a1-2000x851-58.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/36c76e1e-7c78-4500-a906-fc12ad43575b-2000x851-5.jpg">
                        </div><div class="carousel-item active">
                            <img alt="" src="assets/images/b31f5872-cfb7-42cc-b595-9d35931c4d4d-2000x851-43.jpg">
                        </div>
                    </div>
                    <a class="left carousel-control" role="button" data-slide="prev" href="#lb-gallery3-g">
                        <span class="icon-prev" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" role="button" data-slide="next" href="#lb-gallery3-g">
                        <span class="icon-next" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                    <a class="close" href="#" role="button" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section mbr-section__container article" id="header3-i" style="background-color: rgb(247, 63, 128); padding-top: 20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2">Banho!</h3>
                <small class="mbr-section-subtitle"></small>
            </div>
        </div>
    </div>
</section>

<section class="mbr-gallery mbr-section mbr-section-nopadding mbr-slider-carousel" id="gallery3-n" data-filter="false" style="background-color: rgb(0, 0, 0); padding-top: 0rem; padding-bottom: 0rem;">
    <!-- Filter -->
    

    <!-- Gallery -->
    <div class="mbr-gallery-row">
        <div class=" mbr-gallery-layout-default">
            <div>
                <div>
                    <div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Awesome" data-video-url="false">
                        <div href="#lb-gallery3-n" data-slide-to="0" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-88-banheiro-01-glatt-magoni-variacao-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Beautiful" data-video-url="false">
                        <div href="#lb-gallery3-n" data-slide-to="1" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-89-banheiro-2-perle-e-vanille-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Responsive" data-video-url="false">
                        <div href="#lb-gallery3-n" data-slide-to="2" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-90-banheiro-3-grass-e-essenz-variacao-de-cena-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Animated" data-video-url="false">
                        <div href="#lb-gallery3-n" data-slide-to="3" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/djyj6e5je65j6-2000x1168-800x467.png">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <!-- Lightbox -->
    <div data-app-prevent-settings="" class="mbr-slider modal fade carousel slide" tabindex="-1" data-keyboard="true" data-interval="false" id="lb-gallery3-n">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <ol class="carousel-indicators">
                        <li data-app-prevent-settings="" data-target="#lb-gallery3-n" data-slide-to="0"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-n" data-slide-to="1"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-n" data-slide-to="2"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-n" class=" active" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item">
                            <img alt="" src="assets/images/cena-88-banheiro-01-glatt-magoni-variacao-2000x1166.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/cena-89-banheiro-2-perle-e-vanille-2000x1166.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/cena-90-banheiro-3-grass-e-essenz-variacao-de-cena-2000x1166.jpg">
                        </div><div class="carousel-item active">
                            <img alt="" src="assets/images/djyj6e5je65j6-2000x1168.png">
                        </div>
                    </div>
                    <a class="left carousel-control" role="button" data-slide="prev" href="#lb-gallery3-n">
                        <span class="icon-prev" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" role="button" data-slide="next" href="#lb-gallery3-n">
                        <span class="icon-next" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                    <a class="close" href="#" role="button" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section mbr-section__container article" id="header3-j" style="background-color: rgb(247, 63, 128); padding-top: 20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2">Home!</h3>
                <small class="mbr-section-subtitle"></small>
            </div>
        </div>
    </div>
</section>

<section class="mbr-gallery mbr-section mbr-section-nopadding mbr-slider-carousel" id="gallery3-o" data-filter="false" style="background-color: rgb(0, 0, 0); padding-top: 0rem; padding-bottom: 0rem;">
    <!-- Filter -->
    

    <!-- Gallery -->
    <div class="mbr-gallery-row">
        <div class=" mbr-gallery-layout-default">
            <div>
                <div>
                    <div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Awesome" data-video-url="false">
                        <div href="#lb-gallery3-o" data-slide-to="0" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-110-home-theater-2-stark-fraktal-paprika-kya-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Beautiful" data-video-url="false">
                        <div href="#lb-gallery3-o" data-slide-to="1" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-106-home-theater-03-safir-painel-stark-amarula-chocolate-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Responsive" data-video-url="false">
                        <div href="#lb-gallery3-o" data-slide-to="2" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-101-home-theater-klino-kristall-fallen-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Animated" data-video-url="false">
                        <div href="#lb-gallery3-o" data-slide-to="3" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-87-home-theater-01-blond-diamant-variacao-de-cena-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <!-- Lightbox -->
    <div data-app-prevent-settings="" class="mbr-slider modal fade carousel slide" tabindex="-1" data-keyboard="true" data-interval="false" id="lb-gallery3-o">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <ol class="carousel-indicators">
                        <li data-app-prevent-settings="" data-target="#lb-gallery3-o" data-slide-to="0"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-o" data-slide-to="1"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-o" data-slide-to="2"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-o" class=" active" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item">
                            <img alt="" src="assets/images/cena-110-home-theater-2-stark-fraktal-paprika-kya-2000x1166.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/cena-106-home-theater-03-safir-painel-stark-amarula-chocolate-2000x1166.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/cena-101-home-theater-klino-kristall-fallen-2000x1166.jpg">
                        </div><div class="carousel-item active">
                            <img alt="" src="assets/images/cena-87-home-theater-01-blond-diamant-variacao-de-cena-2000x1166.jpg">
                        </div>
                    </div>
                    <a class="left carousel-control" role="button" data-slide="prev" href="#lb-gallery3-o">
                        <span class="icon-prev" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" role="button" data-slide="next" href="#lb-gallery3-o">
                        <span class="icon-next" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                    <a class="close" href="#" role="button" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section mbr-section__container article" id="header3-k" style="background-color: rgb(247, 63, 128); padding-top: 20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2">&nbsp; Dormitório!</h3>
                <small class="mbr-section-subtitle"></small>
            </div>
        </div>
    </div>
</section>

<section class="mbr-gallery mbr-section mbr-section-nopadding mbr-slider-carousel" id="gallery3-p" data-filter="false" style="background-color: rgb(0, 0, 0); padding-top: 0rem; padding-bottom: 0rem;">
    <!-- Filter -->
    

    <!-- Gallery -->
    <div class="mbr-gallery-row">
        <div class=" mbr-gallery-layout-default">
            <div>
                <div>
                    <div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Awesome" data-video-url="false">
                        <div href="#lb-gallery3-p" data-slide-to="0" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-103-closet-1-metall-e-faser-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Beautiful" data-video-url="false">
                        <div href="#lb-gallery3-p" data-slide-to="1" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-104-dormitorio-01-nassau-blat-e-kline-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Responsive" data-video-url="false">
                        <div href="#lb-gallery3-p" data-slide-to="2" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-105-closet-2-dolomit-e-basalt-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Animated" data-video-url="false">
                        <div href="#lb-gallery3-p" data-slide-to="3" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-108-dormitorio-03-kastan-rose-sand-e-stark-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <!-- Lightbox -->
    <div data-app-prevent-settings="" class="mbr-slider modal fade carousel slide" tabindex="-1" data-keyboard="true" data-interval="false" id="lb-gallery3-p">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <ol class="carousel-indicators">
                        <li data-app-prevent-settings="" data-target="#lb-gallery3-p" data-slide-to="0"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-p" data-slide-to="1"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-p" class=" active" data-slide-to="2"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-p" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item">
                            <img alt="" src="assets/images/cena-103-closet-1-metall-e-faser-2000x1166.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/cena-104-dormitorio-01-nassau-blat-e-kline-2000x1166.jpg">
                        </div><div class="carousel-item active">
                            <img alt="" src="assets/images/cena-105-closet-2-dolomit-e-basalt-2000x1166.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/cena-108-dormitorio-03-kastan-rose-sand-e-stark-2000x1166.jpg">
                        </div>
                    </div>
                    <a class="left carousel-control" role="button" data-slide="prev" href="#lb-gallery3-p">
                        <span class="icon-prev" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" role="button" data-slide="next" href="#lb-gallery3-p">
                        <span class="icon-next" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                    <a class="close" href="#" role="button" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section mbr-section__container article" id="header3-m" style="background-color: rgb(247, 63, 128); padding-top: 20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2">Lavanderia!</h3>
                <small class="mbr-section-subtitle"></small>
            </div>
        </div>
    </div>
</section>

<section class="mbr-gallery mbr-section mbr-section-nopadding mbr-slider-carousel" id="gallery3-q" data-filter="false" style="background-color: rgb(0, 0, 0); padding-top: 0rem; padding-bottom: 0rem;">
    <!-- Filter -->
    

    <!-- Gallery -->
    <div class="mbr-gallery-row">
        <div class=" mbr-gallery-layout-default">
            <div>
                <div>
                    <div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Awesome" data-video-url="false">
                        <div href="#lb-gallery3-q" data-slide-to="0" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-91-lavanderia-01-branco-variacao-de-cena-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Animated" data-video-url="false">
                        <div href="#lb-gallery3-q" data-slide-to="1" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-93-lavanderia-03-mandel-silber-glatt-e-vidro-acidato-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Beautiful" data-video-url="false">
                        <div href="#lb-gallery3-q" data-slide-to="2" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-92-lavanderia-02-essenz-land-variacao-de-cena-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div><div class="mbr-gallery-item mbr-gallery-item__mobirise3 mbr-gallery-item--p1" data-tags="Responsive" data-video-url="false">
                        <div href="#lb-gallery3-q" data-slide-to="3" data-toggle="modal">
                            
                            

                            <img alt="" src="assets/images/cena-93-lavanderia-03-glatt-variacao-de-cena-2000x1166-800x466.jpg">
                            
                            <span class="icon-focus"></span>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <!-- Lightbox -->
    <div data-app-prevent-settings="" class="mbr-slider modal fade carousel slide" tabindex="-1" data-keyboard="true" data-interval="false" id="lb-gallery3-q">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <ol class="carousel-indicators">
                        <li data-app-prevent-settings="" data-target="#lb-gallery3-q" data-slide-to="0"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-q" class=" active" data-slide-to="1"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-q" data-slide-to="2"></li><li data-app-prevent-settings="" data-target="#lb-gallery3-q" data-slide-to="3"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item">
                            <img alt="" src="assets/images/cena-91-lavanderia-01-branco-variacao-de-cena-2000x1166.jpg">
                        </div><div class="carousel-item active">
                            <img alt="" src="assets/images/cena-93-lavanderia-03-mandel-silber-glatt-e-vidro-acidato-2000x1166.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/cena-92-lavanderia-02-essenz-land-variacao-de-cena-2000x1166.jpg">
                        </div><div class="carousel-item">
                            <img alt="" src="assets/images/cena-93-lavanderia-03-glatt-variacao-de-cena-2000x1166.jpg">
                        </div>
                    </div>
                    <a class="left carousel-control" role="button" data-slide="prev" href="#lb-gallery3-q">
                        <span class="icon-prev" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" role="button" data-slide="next" href="#lb-gallery3-q">
                        <span class="icon-next" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                    <a class="close" href="#" role="button" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section" id="testimonials1-b" style="background-color: rgb(154, 91, 144); padding-top: 120px; padding-bottom: 120px;">

    

        <div class="mbr-section mbr-section__container mbr-section__container--middle">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 text-xs-center">
                        <h3 class="mbr-section-title display-2">Depoimentos de nossos clientes</h3>
                        <small class="mbr-section-subtitle">Saiba o que nossos clientes acharam do nosso produto.</small>
                    </div>
                </div>
            </div>
        </div>


    <div class="mbr-testimonials mbr-section mbr-section-nopadding">
        <div class="container">
            <div class="row">

                <div class="col-xs-12 col-lg-4">

                    <div class="mbr-testimonial card mbr-testimonial-lg">
                        <div class="card-block"><p>“Como toda dona de casa, eu sempre tive o sonho de ter uma cozinha planejada, ao meu gosto, e isso foi possível depois que conheci os móveis planejados da TutteMob....”</p></div>
                        <div class="mbr-author card-footer">
                            <div class="mbr-author-img"><img src="assets/images/face3.jpg" class="img-circle"></div>
                            <div class="mbr-author-name">Maria Antonieta</div>
                            <small class="mbr-author-desc">Cliente de Pernambuco</small>
                        </div>
                    </div>
                </div><div class="col-xs-12 col-lg-4">

                    <div class="mbr-testimonial card mbr-testimonial-lg">
                        <div class="card-block"><p>“Material fantástico, de alta qualidade, entrega no prazo, atendimento impecável, serei uma cliente enterna da TutteMob, indico e sempre indicarei .......”</p></div>
                        <div class="mbr-author card-footer">
                            <div class="mbr-author-img"><img src="assets/images/face1.jpg" class="img-circle"></div>
                            <div class="mbr-author-name">Carla da Silva.</div>
                            <small class="mbr-author-desc">Cliente da Paraíba</small>
                        </div>
                    </div>
                </div><div class="col-xs-12 col-lg-4">

                    <div class="mbr-testimonial card mbr-testimonial-lg">
                        <div class="card-block"><p>“A TutteMob me surprendeu, design impecável, moderno, bonito e por um preço justo. Quem quiser realizar seu sonho, a TutteMob com certeza é a melhor opção ....”</p></div>
                        <div class="mbr-author card-footer">
                            <div class="mbr-author-img"><img src="assets/images/face2.jpg" class="img-circle"></div>
                            <div class="mbr-author-name">Lizete Neitzke</div>
                            <small class="mbr-author-desc">Cliente de Porto Alegre</small>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

</section>

<section class="mbr-section mbr-section__container article" id="header3-a" style="background-color: rgb(247, 63, 128); padding-top: 20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2">Nossas lojas!</h3>
                <small class="mbr-section-subtitle"></small>
            </div>
        </div>
    </div>
</section>

<!--
<section class="mbr-cards mbr-section mbr-section-nopadding" id="features3-9" style="background-color: rgb(154, 91, 144);">

    

    <div class="mbr-cards-row row">
        <div class="mbr-cards-col col-xs-12 col-lg-4" style="padding-top: 40px; padding-bottom: 0px;">
            <div class="container">
              <div class="card cart-block">
                  <div class="card-img"><img src="assets/images/boaviagem-600x600.jpg" class="card-img-top"></div>
                  <div class="card-block">
                    <h4 class="card-title">Boa Viagem</h4>
                    <h5 class="card-subtitle"></h5>
                    <p class="card-text"><strong>Endereço:</strong><br>Av. Fernando Simões Barbosa, nº 572 - Boa Viagem - Recife/PE<br><strong>E-mail:</strong><br>contato@boaviagem.com.br<br><strong>Telefone:</strong><br>(81) 3463-4899</p>
                    <div class="card-btn"><a href="index.html" class="btn btn-success">SAIBA MAIS...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-4" style="padding-top: 40px; padding-bottom: 0px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/casaforte-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">Caruaru</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Av. Agamenon Magalhães, nº 1363 - Mauricio de Nassau - Caruaru/PE<br><strong>E-mail:</strong><br>falecomoproprietario@casaforte.com.br<br><strong>Telefone:</strong><br>(81) 3719-6940<br></p>
                        <div class="card-btn"><a href="index.html" class="btn btn-success">SAIBA MAIS...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-4" style="padding-top: 40px; padding-bottom: 0px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/piedade-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">Piedade</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Av. Bernado Vieira de Melo, nº 2191 - Piedade - Jaboatão dos Guararapes/PE<br><strong>E-mail:</strong><br>xxx@xxxxpiedade.com.br<br><strong>Telefone:</strong><br>(81) 3361-1650</p>
                        <div class="card-btn"><a href="index.html" class="btn btn-success">SAIBA MAIS...</a></div>
                    </div>
                </div>
            </div>
        </div>
        
        
        
    </div>
</section> 

<section class="mbr-cards mbr-section mbr-section-nopadding" id="features3-r" style="background-color: rgb(154, 91, 144);">

    

    <div class="mbr-cards-row row">
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 0px;">
            <div class="container">
              <div class="card cart-block">
                  <div class="card-img"><img src="assets/images/casaforte-1-600x600.jpg" class="card-img-top"></div>
                  <div class="card-block">
                    <h4 class="card-title">&nbsp;Casa Forte</h4>
                    <h5 class="card-subtitle"></h5>
                    <p class="card-text"><strong>Endereço:</strong><br>Av. Dezessete de Agosto, nº 863 - Casa Forte - Recife/PE<strong><br>E-mail:<br></strong>falecomoproprietario@casaforte.com.br<br><strong>Telefone:</strong><br>(81) 3034-1449</p>
                    <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 0px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/olinda-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">Olinda</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Rua Dr. Pedro de Assis Rocha, nº 75 - Bairro Novo - Olinda/PE<br><strong>E-mail:</strong><br>helderqa@hotmail.com<br><strong>Telefone</strong>:<br>(81) 3494-2755</p>
                        <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 0px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/pina-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">Pina</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Av. Engenheiro Domingos Ferreira, nº 256 - Pina - Recife/PE<br><strong>E-mail:</strong><br>adl.planejados@uol.com.br<br><strong>Telefone:</strong><br>(81) 3466-3611</p>
                        <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 0px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/casaforte-1-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">S. C. do Capibaribe</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Av. 29 de Dezembro, nº 756 - São Cristóvão - Santa Cruz do Capibaribe/PE<br><strong>E-mail:</strong><br>ianaramartins@hotmail.com<br><strong>Telefone:</strong><br>(81) 3731-3003</p>
                        <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
</section>
-->

<section class="mbr-cards mbr-section mbr-section-nopadding" id="features3-u" style="background-color: rgb(154, 91, 144);">

    

    <div class="mbr-cards-row row">
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 0px;">
            <div class="container">
              <div class="card cart-block">
                  <div class="card-img"><img src="assets/images/giardinni-imbiribeira-600x600.jpg" class="card-img-top"></div>
                  <div class="card-block">
                    <h4 class="card-title">Campina Grande</h4>
                    <h5 class="card-subtitle"></h5>
                    <p class="card-text"><strong>Endereço:</strong><br>Av. Dr. Elpidio de Almeida, nº 320 - Catolé - Campina Grande/PB<br><strong>E-mail:</strong><br>xxxcampinagrande@xxxfranquias.com.br<br><strong>Telefone:</strong><br>(83) 3065-2020</p>
                    <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 0px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/giardinni-boaviagem-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">Arcoverde</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Av. José Magalhães França, nº 99 - Centro - Arcoverde/PE<br><strong>E-mail:</strong><br>romildofraga@ig.com.br<br><strong>Telefone:</strong><br>(87) 3822-2201</p>
                        <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 0px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/giardinni-gracas-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">João Pessoa</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Av. Presidente Epitácio Pessoa, nº 2668 - Bairro dos Estados - João Pessoa/PB<br><strong>E-mail:</strong><br>fabianapb@gmail.com<br><strong>Telefone:</strong><br>(83) 3247-7273</p>
                        <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 0px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/giardinni-imbiribeira-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">Natal</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço</strong>:<br>Av. Senador Salgado Filho, nº 2850 - Candelária - Natal/RN<br><strong>E-mail</strong>:<br>natal@xxxfranquias.com.br<br><strong>Telefone</strong>:<br>(84) 3234-2120</p>
                        <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
</section>

<section class="mbr-cards mbr-section mbr-section-nopadding" id="features3-v" style="background-color: rgb(154, 91, 144);">

    

    <div class="mbr-cards-row row">
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 40px;">
            <div class="container">
              <div class="card cart-block">
                  <div class="card-img"><img src="assets/images/giardinni-imbiribeira-600x600.jpg" class="card-img-top"></div>
                  <div class="card-block">
                    <h4 class="card-title">Giardinni C. Grande</h4>
                    <h5 class="card-subtitle"></h5>
                    <p class="card-text"><strong>Endereço</strong>:<br>Av. Prefeito Severino Bezerra Cabral, nº 369 - José Pinheiro - Campina Grande/PB<br><strong>E-mail</strong>:<br>arnobiofontes@uol.com.br<br><strong>Telefone:</strong><br>(83) 3077-1766</p>
                    <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 40px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/giardinni-boaviagem-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">Giardinni Boa Viagem</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Rua Alfredo Marcondes, 615 - Imbiribeira - Recife/PE<br><strong>E-mail:</strong><br>boaviagem@giardinni.com<br><strong>Telefone:</strong><br>(81) 3048-2862</p>
                        <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 40px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/giardinni-gracas-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">Giardinni Graças</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Av. Conselheiro Rosa e Silva, 1117 - Graças - Recife/PE<br><strong>E-mail:</strong><br>gracas@giardinni.com<br><strong>Telefone:</strong><br>(81) 3038-5098</p>
                        <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 0px; padding-bottom: 40px;">
            <div class="container">
                <div class="card cart-block">
                    <div class="card-img"><img src="assets/images/giardinni-imbiribeira-600x600.jpg" class="card-img-top"></div>
                    <div class="card-block">
                        <h4 class="card-title">Giardinni Natal</h4>
                        <h5 class="card-subtitle"></h5>
                        <p class="card-text"><strong>Endereço:</strong><br>Av. Sen. Salgado Filho, 2850 - Loja 05 - Natal/RN - Natal/RN<br><strong>E-mail:</strong><br>natal@giardinni.com<br><strong>Telefone:</strong><br>(84) 2010-3492</p>
                        <div class="card-btn"><a href="https://mobirise.com" class="btn btn-success">Saiba Mais...</a></div>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
</section>