<div id="section-quemsomos-bg">
	<div id="section-quemsomos" class="section col-lg-12">
		<h1><strong>SOBRE NÓS</strong></h1>
		A TutteMob é um novo conceito no <strong>relacionamento</strong> com consumidores de móveis planejados.<br>
		Esta será a sua primeira experiência na compra de móveis planejados de forma <strong>totalmente on line</strong>.<br>
		Os móveis que produzimos são vendidos de forma <strong>direta ao consumidor</strong>.<br>
		Você terá toda a comodidade dos serviços de uma loja física <strong>sem sair de casa</strong>.<br><br>
		<div id="section-quemsomos-interno">
			<!-- <div class="container"> -->
				<strong>Somos novo conceito no relacionamento</strong><br>
				<strong>Com consumidores de móveis planejados.</strong><br>
			<!-- </div> -->				
		</div>
	</div>
</div>