<?php if(!$this->layout()->usuario): ?>
	<div id="experiencia-tuttemob">
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			EXPERIÊNCIA TUTTEMOB
		</a>
		<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
			INICIE AGORA!
		</a>
	</div>
<?php endif; ?>

<div id="section-desktop-sobrenos">
	<div class="section section-sobrenos col-lg-12">
			<div class="section-background">
				<img src="<?= $this->basePath('img/paginas/7.png'); ?>" class="img-responsive" />
			</div>
			<div class="section-page">
				<div>
					<p class="p1">O padrão fora <br />
					do padrão.</p>
				</div>
			</div>
	</div>

	<div class="section-sobrenos2 section col-lg-12">
		<div class="section-page">
			<div>
				<div class="col-sm-9">
					<p class="p1">
						Acreditamos que <br />
						o segmento de móveis <br />
						planejados pode ter um <br />
						serviço de excelência.
					</p>
				</div>
				<div class="col-sm-3">
				</div>
				<div class="col-sm-9">
					<p class="p2">
						Hoje, os consumidores de móveis planejados no Brasil 
						pagam um preço elevado pelos seus móveis, e recebem,
						normalmente, serviços de baixa qualidade.
					</p>
				</div>
				<div class="col-sm-3">
				</div>
			</div>
		</div>
	</div>

	<div class="section-sobrenos3 section col-lg-12">
		<div class="section-page">
			<div>
				<p class="p1">
					Pagam pela ineficiência do serviço, por estruturas e
					pontos de venda tradicionais com altos custos, que impactam
					consideravelmente no preço final mesmo sem necessariamente
					ter relação com a qualidade do produto ofertado.
				</p>

				<p class="p2">
					Nós criamos um <br /> 
					sistema para <br />
					revolucionar essa <br />
					cultura.
				</p>
			</div>
		</div>
	</div>

	<div class="section-sobrenos4 section col-lg-12">
		<div class="section-page">
			<div>
				<div class="box">
					<p class="p1">
						Nosso objetivo? oferecer produtos de alta qualidade com preço justo
						e inteligente, essa é a verdadeira e melhor relação custo x benefício.
					</p>
				</div>

				<p class="p2">
					Nosso sistema de venda é <b>via internet</b>,
					que abandona a forma tradicional
					da venda de móveis planejados, sem 
					perder a <b style="font-weight: 800 !important">comodidade</b> dos serviços
					de medição, projeto e instalação.
					<br /><br />
					Queremos que o consumidor só pague
					por aquilo que gere <b>valor real</b> ao seu produto.
				</p>
			</div>
		</div>
	</div>

	<div class="section-sobrenos5 section col-lg-12">
		<div class="section-page">
			<div>
				<p class="p1">
					Aqui, o cliente <br />
					tem o monitoramento <br />
					de cada etapa do <br />
					processo de compra na <br />
					palma da mão.
				</p>

				<p class="p2">
					Além de atendimento e serviços com qualidades <br /> 
					superiores e a possibilidade de avaliar e visualizar a experiência <br />
					de outros clientes com a marca e o produto.
				</p>
			</div>
		</div>
	</div>

	<div class="section-sobrenos6 section col-lg-12">
		<div class="section-page">
			<div>
				<p class="p1">
					Venha também fazer <br />
					parte da revolução na nova <br />
					experiência de compra de<br />
					móveis planejados.
				</p>
			<p>&nbsp;</p>
			</div>
			
			<?php if(!$this->layout()->usuario): ?>
				<div id="experiencia-tuttemob2">
					<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
						INICIE AGORA!
					</a>
				</div>

				<p>&nbsp;</p>
				<p>&nbsp;</p>
			<?php else: ?>
				<div>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
				</div>				
			<?php endif; ?>
			<!-- 
			<div>
				<br />
				<p class="p2">
					<a href="#">Ou baixe o App já disponível na Apple Store <br />
					e na Google Store.</a> 
				</p>
				<br />
			</div>
			 -->
		</div>		
	</div>

</div>

<div id="section-mobile-sobrenos" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 0; height: 0; overflow-x: hidden;">
	<div class="section-1 section col-lg-12">
		<div class="section-background">
			<img src="<?= $this->basePath('img/paginas/7.png'); ?>" />
		</div>
		<div class="section-page">
			<div>
				<p class="p1">O padrão <br />
				 fora do padrão.</p>
				<p class="p2">
					Acreditamos que
					o segmento de móveis
					planejados pode ter um
					serviço de excelência.
				</p>
				<p class="p3">
					Hoje, os consumidores de móveis planejados no Brasil 
					pagam um preço elevado pelos seus móveis, e recebem,
					normalmente, serviços de baixa qualidade.
				</p>
				<p class="p4">
					Pagam pela ineficiência do serviço, por estruturas e
					pontos de venda tradicionais com altos custos, que impactam
					consideravelmente no preço final do produto.
				</p>
				<div class="box">
					<p class="p5">
						Nós criamos um 
						sistema para
						revolucionar essa
						cultura.
					</p>
					<p class="p6">
						Nosso sistema de venda é <b>via internet</b>,
						que abandona a forma tradicional
						da venda de móveis planejados, sem 
						perder a <b style="font-weight: 800 !important">comodidade</b> dos serviços
						de medição, projeto e instalação.
						<br />
						Queremos que o consumidor só pague
						por aquilo que gere <b>valor real</b> ao seu produto.
					</p>
					<p class="p7">
						Nosso objetivo?
					</p>
					<p class="p8">
						Oferecer produtos de alta qualidade com preço justo
						e inteligente, essa é a verdadeira e melhor relação custo x benefício.
					</p>
				</div>
				<p class="p9">
					Aqui, o cliente
					tem o monitoramento
					de cada etapa do
					processo de compra na
					palma da mão.
				</p>

				<p class="p10">
					Além de atendimento e serviços com qualidades 
					superiores e a possibilidade de avaliar e visualizar a experiência
					de outros clientes com a marca e o produto.
				</p>
				<p class="p11">
					Venha também fazer
					parte da revolução na nova
					experiência de compra de
					móveis planejados.
				</p>
				
				<?php if(!$this->layout()->usuario): ?>
					<div id="experiencia-tuttemob2">
						<a href="<?= $this->url('home', array('action' => 'cadastrar')); ?>">
							INICIE AGORA!
						</a>
					</div>
				<?php else: ?>
				<?php endif; ?>
				
				<p>&nbsp;</p>
				<p>&nbsp;</p>
			</div>
		</div>
	</div>
</div>

<style>
@media screen and (max-width: 800px){
	#menu-nav-left {
	  position: absolute !important;
	}
}
</style>

<script src="<?= $this->basePath('lib/jssor/jssor.slider.min.js') ?>"></script>

<script type="text/javascript">
$(document).ready(function(){
	ajustaWidHei = function(){
		$('body').css('overflow', 'hidden');
		$('#section-content').css('overflow', 'hidden');

		if($(window).width() < 800){

		}else{
			$('#section-content').css('overflow-y', 'auto');
		}
		
		// mobile
		var winWidth = $(window).width() + 'px';
		var winHeight = ($(window).height()) + 'px';
		$('#section-mobile-sobrenos').attr('style', $('#section-mobile-sobrenos').attr('style').replace(/(width: )([0-9]{1,4})(px)?/, 'width: ' + winWidth));
		$('#section-mobile-sobrenos').attr('style', $('#section-mobile-sobrenos').attr('style').replace(/(height: )([0-9]{1,4})(px)?/, 'height: ' + winHeight));

		$('#section-mobile-sobrenos div.section-background img').css('height', ($(window).height() * 0.65) + 'px');
		$('#section-mobile-sobrenos .section-1 .section-background img').css('transform', 'translate(-40%, 0%)');

		$('#section-mobile-sobrenos .section-2').parent().css('overflow', 'auto');
		
		//if($(window).width() > 800){
		//	var menuHeight = $('#menu-nav-left').outerHeight() + 'px';
		//	$('.section-background img').css('height', menuHeight);
		//}
	};

	// ajustes iniciais
	ajustaWidHei();

	// ajusta dimensoes em monitoramento
	setInterval(function(){
		ajustaWidHei();
	}, 300);
});
</script>
